### ISSUE TITLE
Visibility Toggle is unclear

### ISSUE THREAD

**Issue by FausticSun** [nusmodifications/nusmods#1045]
### Describe the bug

The visibility toggle for each module currently shows the next state it will change to. This make it unclear to the users if the modules are visible or not if the user is only looking at the modules panel.

![2018-07-13 11_23_58-timetable - nusmods 2](https://user-images.githubusercontent.com/3937996/42670758-646f85d8-868f-11e8-87b5-c6d735eb7dfd.png)

### Expected behavior

This is up for discussion. One option is to follow Photoshop's style of showing the state of the layer in the toggle. Since Photoshop is widely used it would be more natural for users to expect the same behavior from a visibility toggle.

![2018-07-13 11_27_07-mockup psd 25 stuff rgb_16 _ 2](https://user-images.githubusercontent.com/3937996/42670848-d01cca70-868f-11e8-90bd-322e35f1c77c.png)

More discussion on how toggles should be handled can be found in this [UX stack exchange thread](https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan).

**Comment by yangshun** [comment]
@FausticSun Sounds reasonable. Would you like to submit a PR for this?

**Comment by FausticSun** [comment]
@yangshun Yea sure! I'll try to get around to it by this weekend.

**Comment by ZhangYiJiang** [comment]
Sorry, I'll have to disagree. There are two buttons there - one for delete and the other for toggling visibility. The delete button is obviously not a toggle, nor does it show the current state. If you change the hide button to show the current state, the two icons would mean different things even though they are next to each other, which is rather undesirable. 

A better way to show hidden state would be to show the color as per https://github.com/nusmodifications/nusmods/issues/473#issuecomment-341328513 - either in a dashed outline form or with a bar through the middle to show the module is invisible.

**Comment by FausticSun** [comment]
@ZhangYiJiang I agree with your suggestion on showing the hidden state of the modules with colors, and tried to do a mockup of what it would look like:
![showsactiongrayedout](https://user-images.githubusercontent.com/3937996/42743740-32821718-88f9-11e8-9250-57d70a3c39cc.png)
Another possible addition is to change the module color of the hidden modules to grey since those are not shown in the timetable anyway.

When it comes down to what the toggle itself to show, I looked into it a bit more [here ](https://ux.stackexchange.com/questions/54162/icon-for-unmasking-passwords-open-or-closed-to-begin-with)and [here](https://ux.stackexchange.com/questions/92178/volume-control-and-pause-play-toggles-are-inconsistent-why). It does seem like showing the action of the icon is fine as long as the state of the object is clear (as described above).

Perhaps a small addition to make the toggle more clear is a tooltip that says "Hide module" or "Show module". Currently there is a tooltip implemented using the "title" attribute but it takes a second on mouseover to show up (and doesn't look very nice).
![current](https://user-images.githubusercontent.com/3937996/42744130-9e62f904-88fc-11e8-8430-1e9de213b99f.png)
It would be better to have a more modern tooltip as shown below.
![recommended](https://user-images.githubusercontent.com/3937996/42744132-a2b00a38-88fc-11e8-800f-aa5a46f3b36b.png)

**Comment by li-kai** [comment]
Nice mock up. I like it. It is pretty easy to change the color of the text via the onClick: https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/timetable/TimetableModulesTable.jsx#L52
Let us know if you want to take this on 😄 

Tooltips are in the todo, it's not high up in the priority list though...
