### ISSUE TITLE
Unable to view BSP2001 Lesson Timing on Timetable

### ISSUE THREAD

**Issue by KennethChua1995** [nusmodifications/nusmods#1050]
Upon adding BSP2001 Macro and International Economics onto Semester 1 Timetable, the lesson slot does not appear as it should on the daily timetable.

Steps to replicate:
Search "BSP2001 Macro and International Economics" > Add to Semester 1 Timetable > Click on "Timetable" tab at the side

![screen shot 2018-07-17 at 5 15 38 pm](https://user-images.githubusercontent.com/41324835/42808049-eb73d716-89e4-11e8-9ed9-ecd36b2a3c53.png)

**Comment by ZhangYiJiang** [comment]
@taneliang @li-kai [CORS](https://myaces.nus.edu.sg/cors/jsp/report/ModuleDetailedInfo.jsp?acad_y=2018/2019&sem_c=1&mod_c=BSP2001) has the data, but [NUSMods doesn't](https://nusmods.com/modules/BSP2001/macro-and-international-economics). Probably just need another rescrape.

**Comment by KennethChua1995** [comment]
Hi, any updates on this?

**Comment by taneliang** [comment]
Just scraped - the data is now present.

![image](https://user-images.githubusercontent.com/12784593/42985846-bbbccd0a-8c25-11e8-9576-dd1da8be5a7a.png)
