### ISSUE TITLE
Bidding statistics for AY2017/2018 Semester 2 not showing

### ISSUE THREAD

**Issue by yunpengn** [nusmodifications/nusmods#1057]
### Describe the bug

This applies to the details page for all modules. The Bidding statistics for _AY2017/2018 Semester 2_ is current not showing.

### To Reproduce

1. Go to the details page of any module
3. Scroll down to the section `CORS Bidding Stats`
4. AY2017/2018 Semester 2 data is not included

### Expected behavior

Should show AY2017/2018 Semester 2 data since [CORS](http://www.cors.nus.edu.sg/archive.html) already published the data.

### Screenshots

<img width="844" alt="screen shot 2018-07-26 at 09 41 01" src="https://user-images.githubusercontent.com/18503402/43236508-0bd7fada-90b8-11e8-827c-71a78c7c17a5.png">

### Desktop (please complete the following information):

* OS: macOS
* Browser: Safari
* Version: 11.1.2

**Comment by ZhangYiJiang** [comment]
Still not entirely sure why this happened, but CORS is dead, so :man_shrugging: I guess?
