### ISSUE TITLE
Venn diagram display/selector for semesters filter

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#107]
As discussed with @ashrayjain, there might be scenarios where 'Semester 1 only', 'Semester 2 only' and 'Semester 1 AND Semester 2' filters might come in handy. If this set replaced the current filter set, it would take 2 clicks to filter the presumably more common scenario of any modules offered in Semester 1.

A venn diagram representation might be clearer and faster to interact with - tap to select region and drag to select multiple regions. The size/overlap could be adjusted based on the actual module counts. This would probably be done using D3.

[Venn.js](https://github.com/benfred/venn.js) might be handy for this.

**Comment by yangshun** [comment]
Closing in favor of #426
