### ISSUE TITLE
<select> hard to read in night mode using  Safari Mobile

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1130]
`<select>` elements cannot have their background colors changed in Mobile Safari, but their font color can. In night mode this makes them difficult to read as the font color do not have enough contrast with the background. This does not reproduce in Safari Desktop or Chrome Mobile 

![index](https://user-images.githubusercontent.com/445650/44825691-4f1c3a80-ac3e-11e8-860f-6834d4cd9c36.jpeg)

Two options  

1. Use Bowser (which we already use for legacy browser detection, see https://github.com/nusmodifications/nusmods/blob/master/www/src/js/bootstrapping/browser.js) to add a global class to body which we can then use to override `<select>` font color in Safari Mobile only 
2. Use `-webkit-appearance: none` or some other proprietary property, which should turn off native styling. Unfortunately this may also remove the down arrow on the `<select>` and make it harder to recognize, so use this with care 
    - https://stackoverflow.com/questions/21400182/safari-css-font-color-issue
    - https://stackoverflow.com/questions/42157894/style-html-select-tag-on-ios-safari-iphone

**Comment by fllprbt** [comment]
Lovely, could I tackle this one?

**Comment by ZhangYiJiang** [comment]
@fllprbt  Go ahead. You can talk to us on our [Telegram channel](https://telegram.me/nusmods) if you have issue with setting up. Our README should have all the information you need: https://github.com/nusmodifications/nusmods/tree/master/www. For this specific issue it'll be very useful to have an iOS device so you can test this.

**Comment by fllprbt** [comment]
I will VM an iOS image with Xcode.

**Comment by fllprbt** [comment]
According to a mention from @taneliang the select box is not so clear on non-dark mode.

![dada](https://user-images.githubusercontent.com/6865038/46459304-c8b4c480-c7b8-11e8-9a59-05dce3f46421.jpeg)

So should I leave the default ios for non-darks? 

![screenshot from 2018-10-04 09-37-24](https://user-images.githubusercontent.com/6865038/46459406-234e2080-c7b9-11e8-8af2-b41dcec778ee.png)

 or should I do it custom as well. If yes for custom state if you want it similar to chrome non-dark or a completely new styling.
