### ISSUE TITLE
Use a tombstone to represent removed modules

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1136]
Currently when you remove a module from the timetable, we use the snackbar to give the user an 'Undo' button to restore the module, in case they made a mistake. This works well, except 

1. The snackbar disappears after a while 
2. On Safari Mobile, we can't use Snackbar with action because they require two taps, so we use an alert instead, but this is less user friendly 

An alternative is to replace the module with a tombstone - a box that remains at where the removed module is, with a button that allows the user to undo. The tombstone doesn't stay there forever - it's gone the next time you navigate to the timetable, or if you press the close button, but before that it stays on screen, giving the user as much time as they need to undo their action. An example of this is what you get when you dismiss a sidebar ad on YouTube (although YouTube doesn't allow you to dismiss the tombstone). 

Here's where you can start - https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/timetable/TimetableModulesTable.jsx . The tombstone may need to be stored in the Redux store, as adding a module or deleting another module should clear the tombstone. Alternatively using local component State may also work, since the timetable table can check when timetable modules change.

**Comment by jiholim** [comment]
Mockup for reference - 

![banner](https://user-images.githubusercontent.com/25242767/44856825-034ead00-aca1-11e8-839a-4150c8775850.png)

**Comment by mrassili** [comment]
Hi, Marouane here. I'll be working on this issue if you allow me

**Comment by ZhangYiJiang** [comment]
@mrassili  Sure, please go ahead
