### ISSUE TITLE
Integrate Leaflet.GestureHandling into our map components 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1165]
Currently our map used on venue pages uses the default Leaflet touch behaviors. This means that they use single finger scroll, which makes it hard to scroll down the venue pages to see the timetable on phones and tablets. The solution is to use two finger instead of one to scroll the map - this will let us preserve the single finger scroll for scrolling the page.

Fortunately there is a plugin for this already- https://github.com/elmarquis/Leaflet.GestureHandling. Unfortunately we use *React* Leaflet, so compatibility is unknown. Your mission, should you choose to accept it, is to attempt to make the plugin work, or if that is not possible, port the behavior for React Leaflet using the original plugin code.

**Comment by JingYenLoh** [comment]
Hi, is anyone working on this? I would like to give this a shot.
