### ISSUE TITLE
Add filter to hide modules with clashing exam time in module finder 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1184]
Currently the module finder has a filter for no exam date, but wouldn't it be great to also make it hide all exams that clash with the mods you've already picked? 

Unfortunately implementing this is a bit tricky - our current filter system is designed using classes, and are initialized statically, while selected mods are stored in Redux, which means the filters need to be created dynamically instead. This has been done for search filters, so it's not impossible - look at the existing search filter code to see how this can be done, and ping me if you have any questions :)

**Comment by phoenix1796** [comment]
I'd like to work on this!

**Comment by ZhangYiJiang** [comment]
@phoenix1796 Please go ahead. Instructions for setting up can be found in the README: https://github.com/nusmodifications/nusmods/tree/master/www. You can talk to us on Telegram if you have any problems https://telegram.me/nusmods

**Comment by ZhangYiJiang** [comment]
@phoenix1796 Hi there, any updates? If you have any difficulties feel free to ask for help here or in Telegram

**Comment by chaitanyabaranwal** [comment]
Hey, I would like to check out this issue. Unfortunately, I'm a beginner at WebDev, and I'm not familiar with Redux. Is it okay for me to try working on this? If yes, are there resources I can check out before delving into the codebase?

**Comment by ZhangYiJiang** [comment]
This issue doesn’t require a lot of experience with Redux, but I would suggest looking at something simpler if you’ve never written JavaScript before.

**Comment by chaitanyabaranwal** [comment]
I've worked with JavaScript so I'm comfortable with that. In any case, I'll check this out and see for myself if I can do this!

**Comment by andlimey** [comment]
Can I work on this?

**Comment by TanLeYang** [comment]
I would like to try working on this please!

**Comment by zwliew** [comment]
Resolved by #2845
