### ISSUE TITLE
Outdated or unsupported modal is displayed on Firefox on iOS 

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1201]
### To Reproduce

1. Open https://nusmods.com on Firefox on iOS
2. See error

### Screenshots

![img_6c9af2d522f5-1](https://user-images.githubusercontent.com/12784593/46520086-435f0c00-c8ad-11e8-8283-761a07ad0c5e.jpeg)

### Tablet

* Device: iPad Pro
* OS: iOS 12
* Browser: Firefox
* Version: 13.2

### Additional details

As all iOS browsers share the same rendering engine, ideally, we'll try to show the modal based on the iOS version.

**Comment by ZhangYiJiang** [comment]
This is very closely related to #1202 actually. Whatever browser detection fix for #1202 can just be reused here. Might consider changing this to add Chromium based browsers like Brave, Opera and Vivaldi.

**Comment by ZhangYiJiang** [comment]
Fixed by #1338
