### ISSUE TITLE
<select> hard to read in night mode using non-Safari browsers on iOS

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1202]
### Describe the bug

\<select\> elements were styled on Mobile Safari in https://github.com/nusmodifications/nusmods/pull/1189 and https://github.com/nusmodifications/nusmods/pull/1200, both of which together resolved https://github.com/nusmodifications/nusmods/issues/1130. However, other iOS browsers (e.g. Chrome, Firefox) also have this issue as they all use the same rendering engine.

#### Chrome

![img_fea909cc19bb-1](https://user-images.githubusercontent.com/12784593/46520444-a0a78d00-c8ae-11e8-8273-538cb33c8d77.jpeg)

#### Firefox

![img_aec2b5417998-1](https://user-images.githubusercontent.com/12784593/46520453-a43b1400-c8ae-11e8-8e6e-3401851eaeef.jpeg)

**Comment by adityatandon007** [comment]
@taneliang can I try this

**Comment by taneliang** [comment]
Certainly! You may want to branch off from https://github.com/nusmodifications/nusmods/pull/1200 or wait for it to be merged as it has some major changes from master.

**Comment by adityatandon007** [comment]
@taneliang how long will it take to get merged for #1200

**Comment by taneliang** [comment]
Actually now that I think about it, it should be fine to just branch off from master. If you don't touch the stylesheets there shouldn't be any conflict :)

**Comment by adityatandon007** [comment]
@taneliang Ok

**Comment by adityatandon007** [comment]
@taneliang PR sent Please review
