### ISSUE TITLE
Add a fullscreen toggle for venue maps 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1212]
We use a React Leaflet map component to show venue locations (eg. https://nusmods.com/venues/AS1-0207). It would be great if a fullscreen button can be added so the map expands out to fill the whole screen, or at least the entire right side of the page (on desktop). 

This would be even more helpful for the update location form, which can definitely benefit from allowing the map to use the full width / height of the screen instead of just the form. 

![screenshot from 2018-10-11 10-47-38](https://user-images.githubusercontent.com/445650/46777734-23af6400-cd43-11e8-91a3-20b159ae5676.png)

**Comment by schalkneethling** [comment]
Hey @ZhangYiJiang, I will grab this one.

**Comment by ZhangYiJiang** [comment]
@schalkneethling Sure! The component in question is here: https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/venues/VenueLocation/VenueLocation.jsx. You can find instructions for setting up the project at https://github.com/nusmodifications/nusmods/tree/master/www, and if you have problem setting up you can talk to us on Telegram at https://telegram.me/nusmods

**Comment by schalkneethling** [comment]
@ZhangYiJiang Almost there, will have the pull request ready tomorrow(aka Sunday).

**Comment by ZhangYiJiang** [comment]
Fixed by #1216
