### ISSUE TITLE
Correct venue names to use Title Case instead of ALL CAPS 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1213]
ALL OF THE- sorry, my caps lock got stuck. All of the venues pulled from the NUS venue APIs currently have ALL CAPS venue names. This may work for them, but it looks pretty ugly for us. All caps text is also harder to read. 

It should be possible to automatically convert names like "SEMINAR ROOM 2" to "Seminar Room 2". 
Currently we use lodash to capitalize the text on the frontend, and the result is not optimal because things like abbreviations are incorrectly converted to lowercase eg. https://nusmods.com/venues/WS2-01-30. 

A good way to fix this is to write a script to clean up the data in venues.json https://github.com/nusmodifications/nusmods/blob/master/www/src/js/data/venues.json. Doing this offline allows us to use a proper dictionary to correctly determine which words need to be capitalized. Do note that some venue names should not be capitalized, like the i3 building.

**Comment by joshuaswift** [comment]
I'll have a go at this! Running a script seems like the best way to go.

**Comment by ZhangYiJiang** [comment]
@joshuaswift Sure! You can find the scripts for the projects in https://github.com/nusmodifications/nusmods/tree/master/www/scripts

**Comment by joshuaswift** [comment]
@ZhangYiJiang do you think it would be best to make a new script or implement as part of the script at https://github.com/nusmodifications/nusmods/blob/master/www/scripts/update-venues.js ?

**Comment by ZhangYiJiang** [comment]
@joshuaswift Best to implement it separately. We may have different sources for the data in the future.

**Comment by joshuaswift** [comment]
@ZhangYiJiang I've gotten to a point where the venues are correctly title cased for the most part, however I'm not sure how to title case based on a dictionary like you mentioned in the issue. At the moment abbreviations are displayed like so "Sde-Er5" which is obviously not what we're after! Any ideas? Thanks

**Comment by ZhangYiJiang** [comment]
@joshuaswift My idea is to simply title case anything that are actual words, and leave anything that’s not as all caps. We can then manually use a whitelist to catch anything that this misses

**Comment by joshuaswift** [comment]
@ZhangYiJiang Thanks, I'm thinking of using something like [check-word](https://www.npmjs.com/package/check-word) to check they're actual words unless you have any other suggestions?

**Comment by ZhangYiJiang** [comment]
I was actually thinking of just using `/usr/share/dict/words` since this isn't likely going to be run very frequently, but having a more portable solution is nice. The library is GPL though, so I don't know if this is going to cause any issue.

**Comment by ZhangYiJiang** [comment]
@joshuaswift Any updates on this issue? If you have any code that you've worked on but don't have time to complete you can always open a PR with [WIP] in the title and we can take over
