### ISSUE TITLE
Upgrade flow types to use exact types

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#1214]
Currently many of our [types](https://github.com/nusmodifications/nusmods/tree/master/www/src/js/types) look like the following:

```
export type ModuleSearch = {
  term: string,
  tokens: string[],
};
```

We should, however, change them to use [exact object types](https://flow.org/en/docs/types/objects/#toc-exact-object-types) whenever possible:
```
export type ModuleSearch = {|
  term: string,
  tokens: string[],
|};
```

Then, to further make it explicit that these types should be read-only, set them to be [covariant](https://medium.com/@forbeslindesay/covariance-and-contravariance-c3b43d805611):
```
export type ModuleSearch = {|
  +term: string,
  +tokens: string[],
|};
```

This issue is extremely broad. We will accept PRs that fixes any amount types, but please do not split them up just for hacktoberfest contribution.

**Comment by nirmalks** [comment]
I would like to work on this

**Comment by li-kai** [comment]
@nirmalks All yours for now!

**Comment by nirmalks** [comment]
Hi, 
Any pointers on what sort of tests should be made? Should I include test cases?

**Comment by li-kai** [comment]
@nirmalks As long as `yarn flow` command passes, you're good.

**Comment by nirmalks** [comment]
@li-kai Ok, Thanks. Will work on it and get back.
