### ISSUE TITLE
Find free room should use the current time when the box is opened, rather than when the page is loaded 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1219]
On the Venue page, there's a button that allows students to find free classrooms. The box tries to be intelligent and use the current time (or closest future time if it is currently outside office hours). 

However, currently the box always uses the time when the page is loaded, rather than when the box is opened. This is because the current implementation calls `defaultSearchOptions()` when the component `state` is initialized. If the user has already been on the page for a while, then the time/date may be outdated. A good way to fix this is to update the search options when the button is clicked. Do take note not to clear any existing search options, eg. from query string. 

Component: https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/venues/VenuesContainer.jsx

**Comment by ParkourKarthik** [comment]
I'll try to contribute on this one :)

**Comment by ParkourKarthik** [comment]
@xit4 That's ok. I hope you got it done already :smile:
