### ISSUE TITLE
Create a "contribute" page to attact contributors 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1226]
NUSMods is run entirely by students, for students. This means we're constantly looking for developers, designers and feedback, and now that we have venue information we also need students to contribute location info. 

Currently we have such a page on https://nusmods.com/about, but it's a bit lame. I think we can do better, and put the dedicated contribute button on the sidebar (on desktop) to make it more prominent. Ideas for what to put on the page to attract more contributors are welcome, but here are mine 

- The blurb from the current About page and the three buttons 
- A list of locations that are unmapped, and a progress bar for how many are left 
- The top/new contributors from the [contributors page](https://nusmods.com/contributors)
- Donation link as per #1120 

To build the page you can copy an existing static page from https://github.com/nusmodifications/nusmods/tree/master/www/src/js/views/static

**Comment by ZhangYiJiang** [comment]
@hidingmode Sure! (I'm more curious how you managed to post that given GH is dropping half my requests)

**Comment by ZhangYiJiang** [comment]
- The blurb looks good. I'm not a copywriter though. Let's see if you/anyone else can come up with something better. I would want to make the buttons more visually appealing though. 
- Venue data: the file is at https://github.com/nusmodifications/nusmods/blob/master/www/src/js/data/venues.json, but you need to code split it so it doesn't try to load the entire file unnecessarily. The reason we want a list is because it's not immediately obvious from the main venues page (https://nusmods.com/venues) which venues have location data and which don't. Also can add instructions about how to use their phone's GPS to get the location automatically 
- Contributors: try to extract out the common code. Maybe move it to under `js/apis` 
- Yeah, everything is on that page, but on different places on the page

**Comment by ZhangYiJiang** [comment]
Hi there, if you don't plan to work on this issue after the exams, can you open a PR with your work-in-progress so we can take over?

**Comment by monmanuela** [comment]
Hi, I'd like to give this a try 😄

**Comment by ZhangYiJiang** [comment]
@monmanuela Maybe give @hidingmode a day or two first? I don't want you to duplicate work that's already done

**Comment by monmanuela** [comment]
Ah yup sure! :+1: I'll stay updated

**Comment by ZhangYiJiang** [comment]
You can try looking at the other good first issues. #726 and #1290 are both interesting options I feel

**Comment by hidingmode** [comment]
> Hi there, if you don't plan to work on this issue after the exams, can you open a PR with your work-in-progress so we can take over?

Sorry I don't have the time to progress on this issue. What I did was only copy the static page template, text from contributors page, the buttons from the about page. So I think my changes are not so worthy of a PR.  But if you still think I should open a PR, I will open one.

**Comment by ZhangYiJiang** [comment]
@hidingmode No, that's fine, I was just checking if you've made any more progress from when you made the comment. @monmanuela this issue is all yours :)

**Comment by hidingmode** [comment]
Alright, I'm just gonna paste here the commit with all the changes I made.
https://github.com/hidingmode/nusmods/commit/ef7901fe73e64e4bc33a0e2b36a1622a135a5137

**Comment by monmanuela** [comment]
Hi, here's how the page looks like so far:
![image](https://user-images.githubusercontent.com/35655790/49879806-bc5a8100-fe65-11e8-8cf2-91ac14e0db89.png)
![image](https://user-images.githubusercontent.com/35655790/49879870-deec9a00-fe65-11e8-9db6-3f0a0870e240.png)

I am unsure about how to get the list of unmapped venues. If I understand it correctly, [https://github.com/nusmodifications/nusmods/blob/master/www/src/js/data/venues.json](https://github.com/nusmodifications/nusmods/blob/master/www/src/js/data/venues.json) contains only mapped venues, but where can I find the venues that do not have location data yet? (Currently the progress bar is hardcoded to 75%)

Work left to be done:
- [ ] Prettify the buttons
- [ ] Show the list of unmapped venues

Any feedback or suggestion is appreciated! :smiley:

**Comment by ZhangYiJiang** [comment]
A list of all venues can be found in the venueBank. You can access it via redux via `state.venueBank.venueList`. It is used for global search - https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/layout/GlobalSearchContainer.jsx#L116

**Comment by ZhangYiJiang** [comment]
By the way, you can create a work-in-progress PR so we can take a look at the code.
