### ISSUE TITLE
Add support for customizing width and height to exporter service 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1227]
As part of #1003, before we can build the frontend for this, we need first a way for the service to return images of different sizes. To do that, we can let the service accept some additional query params and pass that to the render method. 

To get started, take a look at https://github.com/nusmodifications/nusmods/tree/master/export for the instructions to setting up the service. If you have any question, just @ me since I built this.

**Comment by JingYenLoh** [comment]
Can I give this a shot?
