### ISSUE TITLE
Missing contributors on contributors page

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1237]
Our contributors page (https://nusmods.com/contributors) lists the GitHub usernames of people who have contributed to the project. However, only 30 contributors are listed even though we [have more](https://github.com/nusmodifications/nusmods/graphs/contributors).

The page ([source](https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/static/ContributorsContainer.jsx)) gets its data from a GitHub API ([docs](https://developer.github.com/v3/repos/#list-contributors), [results](https://api.github.com/repos/nusmodifications/nusmods/contributors)). This API returns only 30 contributors for some reason.

Try to find a way to retrieve the remaining contributors. If this is impossible, try seeing if a newer GitHub API supports this.

**Comment by aaronjparsons** [comment]
https://github.com/nusmodifications/nusmods/pull/1238
