### ISSUE TITLE
Upgrade Raven  packages 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1244]
Sentry moved their Raven exception capture library to a monorepo https://github.com/getsentry/sentry-javascript, deprecating their old package names in the process. As far as I can tell the API should be mostly the same, although some functions are renamed / moved into different namespaces. Migrating should be simple. 

We currently use `raven-js` in `www` (migrate to `@sentry/browser`) and `raven` in  `export` (migrate to `@sentry/node`).

**Comment by JingYenLoh** [comment]
Would there be potential conflicts with #1227 , which I'm currently working on?

**Comment by ZhangYiJiang** [comment]
@JingYenLoh I don't see any reason why it should. Merge conflicts of this sort usually aren't hard to resolve anyway.

**Comment by JingYenLoh** [comment]
Hi, can I work on this?

**Comment by ZhangYiJiang** [comment]
@JingYenLoh Sure!
