### ISSUE TITLE
Remove bots from contributors page

### ISSUE THREAD

**Issue by liaujianjie** [nusmodifications/nusmods#1246]
### Describe the bug

The bots are showing up in the [contributors page](http://latest.nusmods.com/contributors).

### Expected behavior

The bots shouldn't be there

### Screenshots

![image](https://user-images.githubusercontent.com/3143132/47341970-09776d80-d6d5-11e8-9284-42d139af6e0f.png)

**Comment by ZhangYiJiang** [comment]
I've been meaning to fix this. It should be as simple as filtering the contributor by name. Do you want to give it a go?

**Comment by liaujianjie** [comment]
Yeah I'll take it!
