### ISSUE TITLE
Exam timetable should show new month if first day is on weekend

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1287]
Our exam calendar uses a calendar style UI to display exams date and times. As is usual in calendars, we only display the month if it is the first day on the calendar, or if the month changes. Unfortunately the logic for the latter is not correct - it only checks for `date === 1`, but not if the date is on a weekend, and thus not shown. This is happening this semester - as can be seen in the image below, Nov is correctly shown on the first square, but because Dec 1 is on a weekend, Dec is not shown anywhere, which is incorrect. 

![screenshot from 2018-11-12 10-38-16](https://user-images.githubusercontent.com/445650/48323461-48ab3580-e667-11e8-8ea1-cf6af3b6ba5e.png)

The logic for this can be found at https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/timetable/ExamCalendar.jsx#L88

**Comment by steffenvan** [comment]
I would like to handle this issue, if it's still available.

**Comment by steffenvan** [comment]
Just as side node: if there is a module which exam is on the 1st of December, it will display the date 

<img width="867" alt="screenshot 2018-11-13 at 01 55 16" src="https://user-images.githubusercontent.com/22645031/48365967-6d46f200-e6e7-11e8-9d25-aee334d52ade.png">

**Comment by ZhangYiJiang** [comment]
Yes, that’s intended. We don’t want to show Saturdays and Sundays if there are no exams on those days. The bug is that if there’s no exams on those days and they are hidden, the “Dec” part is never shown.

**Comment by ZhangYiJiang** [comment]
@steffenvan Hi, have you made any progress on this? If you have but don't have the time to continue, you can create a work-in-progress PR to share your code. Thanks!

**Comment by steffenvan** [comment]
Hi Zhang, 

I have unfortunately not had super much time to look at it throroughly, and I’m afraid that the small amount of code I’ve written won’t be of any help. I will be gone the next 3 weeks, so it’s best to re-open this issue again! I apologise for any inconvenience this may cause! 

Best,
Steffen
