### ISSUE TITLE
Add error handling inside service worker 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1292]
Currently our service worker code is mostly a black box. We catch on the install registration Promise, but in our Sentry log we only see generic errors like "Failed to register a ServiceWorker: ServiceWorker script evaluation failed" with no stack trace and no insight into what is actually failing. 

To fix this it seems we can add a global error handler *inside* the service worker https://stackoverflow.com/questions/37736322/how-does-global-error-handling-work-in-service-workers#37784386. We'll have to use `importScript` to load RavenJS from inside the service worker, then simply run `captureException` like in the code from this issue https://github.com/getsentry/raven-js/issues/1123

To do this, we can have Workbox load the script from the generated service-worker JS file. See https://github.com/nusmodifications/nusmods/blob/master/www/static/service-worker-notifications.js for an example of this. 

Note that we do still need to test if this is effective - it is possible that since this is loaded asynchronously, the error handler may not attach quickly enough to catch errors like the initialization error above.

**Comment by emer7** [comment]
Hi! I would like to try this issue 😄 🙏

**Comment by ZhangYiJiang** [comment]
@emer7 Please go ahead! You can join us on [Telegram](https://t.me/NUSMods) if you have any questions or problems setting up

**Comment by emer7** [comment]
![image](https://user-images.githubusercontent.com/21377166/51400834-54920700-1b84-11e9-9cc5-e6adc0e27ee1.png)
Hi, is this also what is called as generic error?
Just trying to purposefully create an error (I tried registering non-existent scriptUrl)

**Comment by ZhangYiJiang** [comment]
@emer7  No, that's a bit more useful than what we get right now and would be more useful.

**Comment by emer7** [comment]
> We'll have to use `importScript` to load RavenJS from inside the service worker, then ...

@ZhangYiJiang Hi just want to clarify, when you mention load RavenJS does it mean loading Sentry from a CDN and then configuring it with the DSN or loading `utils/error`?

Because if it is to load `utils/error`, then there might be some problem as `importScripts` cannot import ES6 module (Service Worker also still has bad support for ES6), and hence will need to find other way to circumvent this

**Comment by ZhangYiJiang** [comment]
You have to load it from the CDN. You can't load `utils/error` in service worker (at least not without a lot of difficulty) - the code is written with the assumption it will be bundled via Webpack, so trying to load it directly via `importScripts` will not work. As an aside service worker scripts actually have better than "average" ES6 support just because the browsers that support it are all newer, so most newer features can be used without transpilation. You just can't use `import` in them.

**Comment by emer7** [comment]
Will it be okay to have a multiple Sentry instance?

**Comment by ZhangYiJiang** [comment]
Service worker code runs in a different context from the main browser code (see the paragraph on worker context: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API). There shouldn't be any issue.
