### ISSUE TITLE
Replace stateless PureComponent with functional component + React.Memo 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1312]
[React 16.6 was released about a month ago](https://reactjs.org/blog/2018/10/23/react-v-16-6.html), and one of the bigger new features is `React.memo`, a HOC that does the same thing as PureComponent for functional components. 

Currently we have a number of components using PureComponent for performance reasons. This HOC should allow us to use stateless functional components instead. There's no need to do this urgently, but we can gradually switch to using the new HOC.

**Comment by yuntongzhang** [comment]
I would like to try on this issue!

**Comment by ZhangYiJiang** [comment]
@yuntongzhang Go ahead! If you have problem setting up the project you can talk to us on Telegram https://telegram.me/nusmods
