### ISSUE TITLE
Add Patreon link

### ISSUE THREAD

**Issue by donjar** [nusmodifications/nusmods#1327]
Come on man, I will definitely pledge if you make one!

**Comment by ZhangYiJiang** [comment]
We actually have an [OpenCollective page](https://opencollective.com/nusmods ). The fee structure is about the same as Patreon, and is more appropriate for us, which is why we never considered using it.

**Comment by ZhangYiJiang** [comment]
That’s why we have #1226 :) We don’t actually have a lot of plans about how to spend the money because our infra costs are very low.

**Comment by donjar** [comment]
Awesome! As the OpenCollective page says, we can definitely buy you lots of
Yong Tau Foo.
