### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#133]
Things to mention:
- [ ]  `&nbsp;` in html/templates
- [ ] jshint
- [ ] dev channel in hipchat
- [ ] scss and js style
- [ ] newline at end of file
- [ ] possible credit with modules like CP3108A/B for more ambitious undertakings

**Comment by ngzhian** [comment]
CONTRIBUTING has been created, definitely needs some work on it, @ahbeng @9gix whenever you have time take a look at it? :)

**Comment by yangshun** [comment]
This is a good start

- https://secure.phabricator.com/book/phabcontrib/article/contributing_code/
- https://reactjs.org/docs/how-to-contribute.html
