### ISSUE TITLE
Retain input value after blur on Downshift component

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1350]
[Downshift](https://github.com/paypal/downshift) is currently used in several places, including the add module select dropdown and global search on the top right of every page. The default Downshift behavior is to clear the input on blur, but this doesn't make for great user experience because the user could potentially lose some input. 

According to the docs, there doesn't seem to be any parameter for this, so I think we may have to tap into stateReducer, or make inputValue a controlled property.

**Comment by juxd** [comment]
Hello, I would like to try my hand at this issue.

If I'm reading the code correctly, most (if not all) of the Downshift components except for the global search either already has this implemented or does not require it. Should I just add this input value retention for the global search bar?

**Comment by ZhangYiJiang** [comment]
@juxd Sure, you can take the issue. The problematic behaviour exists in pretty much everywhere Downshift is used. Basically Downshift clears the input value when the input is blurred. This happens in global search, the add module drop down menu, and in the DropdownFilter component used for the module finder. If you need clarification feel free to comment here or ask on Telegram
