### ISSUE TITLE
Feature: Filter by Modules Available for Lecture Bidding

### ISSUE THREAD

**Issue by 9gix** [nusmodifications/nusmods#136]
It would be good to see a new checkbox in the filter panel that filter the bidding availability. Something like the following.
- [ ] Available for bidding

Since, you could get the current bidding round why not add this filter option.

Not sure if we could get the resource, But it is currently available in the web http://www.cors.nus.edu.sg/Reports/openbid_3A_20142015s1.html

**Comment by yangshun** [comment]
The value of this feature does not justify the development cost. Closing this.
