### ISSUE TITLE
Slother Integration

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#140]
As discussed with @Sunxperous on Friday, we could try integrating [Slother](https://github.com/Sunxperous/slother) as well as introducing it to NUSMods users by having a button or dialog in the UI to send a timetable directly to Slother. This could be implemented by having something like a `/add?url=http://nusmods.com/timetable/2014-2015/sem1?AR1327[LEC]=1&AR1327[TUT]=1` endpoint which might present a confirmation dialog. The dialog could be in an iframe instead of a redirect for better user experience.

This could be an alternative model for integration with some NUS-related projects where it makes more sense than consolidating codebases (See also #75).

cc: @jasontanma @Sunxperous @yeesian

**Comment by yangshun** [comment]
Closing in favor of #141
