### ISSUE TITLE
NUSModerator: Automate calculation of start date of academic year

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#1434]
### Is your feature request related to a problem? Please describe.

Right now our start date of acad year has to be updated manually (and it ends this year!). If we could automate this, that'd be great.

### Describe the solution you'd like

The start date of each academic year is defined to be the first Monday of August (Week 0 / Orientation Week). It would be good to automatically calculate it using something like moment.js rather than maintaining our own mapping.

### Describe alternatives you've considered

Retain current behavior

### Additional context

https://github.com/nusmodifications/nusmoderator/issues/2

**Comment by ZhangYiJiang** [comment]
Ah, interesting. I didn't know this was how terms are defined in NUS 

> Commences on first Monday of August each year.

Source: http://www.nus.edu.sg/registrar/calendar.html

**Comment by ZhangYiJiang** [comment]
We won't want to actually use Moment because it doesn't make a lot of sense to add a large dep just to do one bit of math. Maybe write a small script that generates the dates instead?

**Comment by taneliang** [comment]
@Lessthanfree is working on this

**Comment by Lessthanfree** [comment]
I would like to work on this issue
