### ISSUE TITLE
Scroll timetable when lesson is clicked so the lesson remains on screen 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1447]
### Is your feature request related to a problem? 

When the user clicks on a lesson with a lot of options, the current lesson will move to a new location instantly. This will disorientate the user, especially if there are a lot of options. A classic example is GER1000. 

### Describe the solution you'd like

We can scroll the page such that the lesson is still where the mouse is. The mental model for this is that the rest of the timetable is moving, but the lesson remain where the user just clicked/tapped. Currently the new lessons above the selected one pushes it down. To do this we can capture the location of the clicked lesson relative to the viewport, then after next render update scroll such that the same relative scroll from viewport is maintained (the math is left as an exercise to the reader) 

### Describe alternatives you've considered

Another way to solve this is to use animation, aka. #1348.

**Comment by dvrylc** [comment]
Hi can I work on this?

**Comment by ZhangYiJiang** [comment]
@dvrylc Please do! If you have issues setting up or anything else at all feel free to chat to us on Telegram
