### ISSUE TITLE
Provide a way(button) for user to hide the sidebar

### ISSUE THREAD

**Issue by franklingu** [nusmodifications/nusmods#146]
right now sidebar will come into the main page by default and there is no way to hide it. but for a user who is interested in time table only, the sidebar is occupying space without much use. so the user should be able to hide the sidebar to have a bigger view of the timetable/module finder/preference settings

**Comment by yangshun** [comment]
Current version of sidebar is extremely thin. We no longer need to consider hiding functionality.
