### ISSUE TITLE
Show bus stop info on school map

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1497]
### Is your feature request related to a problem? Please describe.

It can be useful to see the nearest bus stop in NUS so you can take the internal shuttle bus. Currently the only element on the map is the marker. 

### Describe the solution you'd like

We can query OSM for bus stop data, but they are not well maintained, and a bit hard to edit. it is possible to query them using an API called [Overpass](https://wiki.openstreetmap.org/wiki/Overpass_API).

An alternative is to maintain manually a list of bus stops. The bus stops and bus routes don't change a lot, so it may not be worth writing the script to pull the data.

Displaying the bus stops on the map is also a bit tricky, but as long as we can find a suitable icon it should be relatively straightforward. If we can get data on the roads we may even be able to draw the route, though that's a stretch goal. 

### Describe alternatives you've considered

Google Maps don't have ISB, so that's not a viable alternative.

**Comment by dvrylc** [comment]
[This](https://nextbus.comfortdelgro.com.sg/eventservice.svc/busstops) is the endpoint that the official NUS bus app uses for the list of bus stops. It has the co-ordinates for all the bus stops so that might be useful for this feature.
