### ISSUE TITLE
Replace usage of immutability-helper with immer

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#1534]
As per title, in www/, we're using both immer and immutability-helper. That is not ideal, and since immer is the better replacement, we should remove usages of immutability-helper.

**Comment by rrtheonlyone** [comment]
Hi, can I take this issue? @li-kai @ZhangYiJiang

**Comment by li-kai** [comment]
Sure! Feel free to reach out to any of us for help on [telegram](https://telegram.me/nusmods).
