### ISSUE TITLE
Affix sidebar on module page breaks when navigating from a module page to another module page

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#159]
Steps to reproduce:
1. Go to a module page, [/modules/ACC2002](/modules/ACC2002) for example.
2. Scroll to the bottom of the page.
3. Click on the search bar and navigate to another page.

The sidebar loses its affix functionality.

**Comment by yangshun** [comment]
@xbili if you are interested you can try tackling this too :smile:

**Comment by xbili** [comment]
I'll look into this!

**Comment by yangshun** [comment]
Fixed via #160
