### ISSUE TITLE
Documentation for APIs

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#1592]
### Is your feature request related to a problem? Please describe.

I'm frustrated when there aren't good documentation on what keys are available on objects returned by NUSMods API.

### Describe the solution you'd like

A clear and concise description of data types in a HTML document I can view in api.nusmods.com

### Describe alternatives you've considered

A README.md would be good too

### Additional context

We should explore https://typedoc.org/ and other typescript documentation generators.

**Comment by ZhangYiJiang** [comment]
Related to this I was looking at if nginx supported nicer directory index than the current one, and I found https://github.com/aperezdc/ngx-fancyindex which looks pretty good. Only problem is that I've never tried installing and enabling dynamic modules for nginx before
