### ISSUE TITLE
Footer does not stick to bottom of the page

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#169]
For pages that have short height like [http://nusmods.com/contribute/reviewers](http://nusmods.com/contribute/reviewers), the footer does not stick to the bottom. Best if we can do this: http://ryanfait.com/sticky-footer/

**Comment by wryyl** [comment]
Try propagating the height down to `div#page-content-wrapper`, which contains the footer.

```
html, body { height: 100%; }
#nm-wrapper { height:100%; }
#page-content-wrapper { min-height:100%; }
```

I don't have the dev environment set up so I can't definitively test this solution, but from brief tests using Chrome's devtools and Firefox's firebug, it seems to work without breaking other parts of the site.

**Comment by xinan** [comment]
Just tried. Seems to be working very well! Thanks! Added that in cb382fb
