### ISSUE TITLE
Venues that are not booked the entire day are not shown under 'Find free rooms'

### ISSUE THREAD

**Issue by chrisjwelly** [nusmodifications/nusmods#1700]
### Describe the bug

Certain venues are available for the entire day on certain days. The 'Find free rooms' feature will not return such venues as a result. 

### To Reproduce

1. Go to 'Venues'
2. Find a venue that is available the entire day. (e.g. COM1-B108 in AY18/19 Sem 2 is not booked for any lessons on Wednesdays)
3. Click on 'Find free rooms' 
4. Select any time range on the fully available day of the venue (e.g. Wednesday, 3PM-4PM for COM1-B108)
5. With the 'Find free rooms' feature active, type the venue name (can be a partial match or complete match) under 'Venue Search'
6. The result of the search will be : 
a) 'No matching venues found' (if complete match of the name is typed), or 
b) it may return other available venues but still without the venue with availability the entire day (if partial match of the venue name is typed)

### Expected behavior

The venue which is available the entire day should be returned as a search result if the time range selected for 'Find free rooms' is within the day when the venue is available the entire day. 

### Screenshots
Screenshot below shows the timetable for COM1-B108 where Wednesday is available the entire day
![](https://imgur.com/u4ykeAa.png)

Screenshot below is a combination of steps 3-5 of reproducing the behavior. Here, a complete match of the venue name is typed and it returns 'No matching venues found'
![](https://imgur.com/Ej2uwQO.png)

Screenshot below is also a combination of steps 3-5. However, here a partial match of the venue name is typed and it returns some available venues for the specified time range, but COM1-B108 is not among the options
![](https://imgur.com/klSNz4q.png)

Additional screenshots: 
These 2 screenshots below changes the time range to be within a day when the venue is not available the entire day (but still has some availability) . As seen in the screenshot, COM1-B108 still appears as expected for both partial match and complete match of venue name.
Complete match 
![](https://imgur.com/kxYRglt.png)
Partial match
![](https://imgur.com/jngDDrk.png)

### Desktop (please complete the following information):

* OS: Windows
* Browser: Firefox and Chrome
* Version: 66 (Firefox) and 73 (Chrome)

### Additional context

The 'Find free rooms' feature seems to work as expected for days which have lessons in the venue. I am not sure if this problem is specific to venues which are free the entire day, but I have tested and confirmed that this unexpected behavior is encountered for other venues of similar nature.

**Comment by ZhangYiJiang** [comment]
Wow, good catch. I think this is because we stripped out all `VACANT` timeslots in API v2, which means non-occupied days won't show up at all. Pretty annoying regression, we should probably add some unit tests for this too. 

The offending code is here: https://github.com/nusmodifications/nusmods/blob/fc4bd9ffed51079d282b4461bb6a80f483bf7b5b/website/src/utils/venues.ts#L39
