### ISSUE TITLE
Github API Rate Limit Exceeded

### ISSUE THREAD

**Issue by xinan** [nusmodifications/nusmods#171]
The Github API has a rate limit of 60 requests/hr for unauthenticated requests. It seems that the NUS network shares the same public IP and that limit is easily exceeded and getting message like this:

```
{
  "message": "API rate limit exceeded for 137.132.228.5. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

One way to fix this is to make the request from our server using Basic Authentication or OAuth, then make the server act as a proxy. Just like how bareNUS is done. 

Ps. Authenticated requests has a limit of 5000/hr.

**Comment by xinan** [comment]
After some researching, I found that NUS network does have quite a number of public IPs. Don't know how they're distributed. A friend staying on my upstairs does not have the same public IP as me. But a friend in Raffles Hall has the same IP with another friend using the NUS WiFi at MPSH. @.@
Anyway the limit is still a problem. Will fix that.

**Comment by paradite** [comment]
I have done similar thing for one of my project:

https://github.com/paradite/gitviz/blob/master/index.js#L86

However it was in node.js and I am not really sure what backend stack do you guys use (I see both php and node.js with browser-sync?)

**Comment by yangshun** [comment]
@paradite just node. PHP is mainly for image and PDF generation of the timetable

**Comment by yangshun** [comment]
This is not a popular page, so it's unlikely the API rate limit exceeds. Closing this off.
