### ISSUE TITLE
Upgrade Bowser and use browserlist-config for unsupported browser warning 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#1721]
### Describe the bug

We have a new browserlist config which is used for Babel and Autoprefixer in the build step, but it is not use by the browser warning, so users of supported browsers may still see the warning 

### To Reproduce

1. Go to NUSMods on Samsung browser 
2. Notice the unsupported browser warning, even though it is on our list 

![Screenshot_20190426-125045](https://user-images.githubusercontent.com/12784593/56784221-08f59600-6822-11e9-841a-2d5e511dc6a3.jpg)

### Expected behavior

The browser warning should not show 

Since we're updating the logic for this, it'll also be worthwhile to roll the Bowser 1.x -> 2.x  update (#1695) into this. The API has been changed, though it is only one line of code so it shouldn't be a huge deal.

**Comment by li-kai** [comment]
A lighter alternative using https://github.com/browserslist/browserslist-useragent-regexp would be possible too.

**Comment by ZhangYiJiang** [comment]
I'm really weary of using that just looking at the sample regex that it created. Is it going to be a lot of work mapping browsers from browserlist to what Bowser consumes?

**Comment by li-kai** [comment]
Does seem like a bit more work because we need the regex during compile time. Looking through the code, it seems like we're only using bowser for the unsupported check and for iOS detection...

**Comment by ZhangYiJiang** [comment]
Fixed by #2054
