### ISSUE TITLE
Infinite fetch-render loop on module archive page

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1724]
### Describe the bug

If the user opens an archive module URL and the module archive data is not found, the page will go into an infinite render-fetch loop.

### To Reproduce

1. Go to 'https://nusmods.com/archive/NM4228/2016-2017/crisis-communication'
1. Open dev tools. Notice the repeated requests to the archive data.

### Expected behavior

A not found error on the archive page should not trigger another attempt to fetch archive data.

### Screenshots

![Peek 2019-04-27 13-12](https://user-images.githubusercontent.com/12784593/56845089-2a23b880-68ee-11e9-8555-a56c5c9aef9b.gif)

### Additional context

The fetch request is triggered at line 36:
https://github.com/nusmodifications/nusmods/blob/5c0268778686c0da4e11548f15b26a13c6fde0df/website/src/views/errors/ModuleNotFoundPage.tsx#L29-L38

`ModuleNotFoundPage` is rendered by the snippet below, which switches repeatedly between rendering `ModuleNotFoundPage` and `ApiError`.
 https://github.com/nusmodifications/nusmods/blob/5c0268778686c0da4e11548f15b26a13c6fde0df/website/src/views/modules/ModulePageContainer.tsx#L107-L115

The rapid switching is likely caused by this:

https://github.com/nusmodifications/nusmods/blob/5c0268778686c0da4e11548f15b26a13c6fde0df/website/src/views/modules/ModulePageContainer.tsx#L158

which checks this:

https://github.com/nusmodifications/nusmods/blob/5c0268778686c0da4e11548f15b26a13c6fde0df/website/src/selectors/requests.ts#L12-L14

As the request keeps getting restarted, the request's state toggles between failure and request, causing multiple renders, and thus causes archive fetches when `ModuleNotFoundPage` renders. This is likely the cause of the infinite loop.

This bug has been present since the archive feature was implemented in #1098 (see https://deploy-preview-1098--nusmods.netlify.com/archive/NM4228/2017-2018/). This bug was not present in the PR that was merged before this (#1303, https://deploy-preview-1303--nusmods.netlify.com/archive/NM4228/2017-2018/).

**Comment by ZhangYiJiang** [comment]
Good detective work! To be fair, this bug is only triggered if the user is somehow on a non-existent archive page. This wasn't something we anticipated since the archive page is already a 404 fallback and is not usually navigatable. Let me see if I can fix this.
