### ISSUE TITLE
Negated module prereq strings result in wrong prereq trees

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1736]
### Describe the bug

Reported by a student over email.

> At the 3000-level, a significant portion of EC-coded modules have the prerequisite: "EC2104 OR ANY MA MODULE THAT IS NOT MA1301/MA1301FC/MA1301X OR MA1311 OR MA1312 OR MA1421" (emphasis my own). Examples of this include [EC3101](https://nusmods.com/modules/EC3101/microeconomic-analysis-ii) and EC3102. The intent of this is that any non-introductory MA module (e.g. MA1101R) can replace EC2104. Unfortunately, on NUSMods, this ends up being coded as EC2104 or MA13XX being taken as a pre-requisite.

### Expected behavior

NUS should be giving us machine readable prereq strings through their internal APIs soon, so this should not remain an issue for too long. Before that happens, we could support parsing such negated prereqs. However, since it is difficult to parse and display them, we could just not generate prereq trees for these mods.

### Screenshots

![39FC5C2B-7888-4F5C-8F04-70D784C1ECB5](https://user-images.githubusercontent.com/12784593/56876519-8ca9bf80-6a7a-11e9-99e8-a21e25ff4d66.jpeg)

**Comment by li-kai** [comment]
This is not an easy change, has the school given us any timeline on machine-readable prereqs?

**Comment by taneliang** [comment]
They only said a few months, but there was no timeline. I'll check with them after finals
