### ISSUE TITLE
Explain that NUSMods does not provide all information

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#174]
We received a complaint:

> for PC1144 lab session H3A, H3B, H3C, can you please have remarks on them stating that NUS students cannot take them. I trusted nusmods and managed my modules using it. Now my timetable is completely screwed up and I have to drop modules to make place for my lab sessions. I am very furious about this matter, it is catastrophic and now I left with only 16 mcs. I will bear all the consequences but please rectify this mistake so that no more people get screwed up on their timetable just because their PC1144 lab sessions.

However, official sources such as CORS will not show this information either. Students need to understand that NUSMods does not provide special information regarding modules and it's up to them to be well-informed by looking up such information themselves.

Although we are unable to keep track of these issues, we need a way to alert users of such things, potentially through crowdsourcing. Possible solutions:
- Use the comments feature
- Add a new tips section

**Comment by xbili** [comment]
Would leaving a message like that of the 'Shared Timetable' work as well?

![screen shot 2015-01-26 at 8 07 35 pm](https://cloud.githubusercontent.com/assets/4846457/5899513/05f41b18-a597-11e4-875f-258cbf111bb8.png)

Maybe show it only during the CORS bidding period when people are selecting their modules.

**Comment by yangshun** [comment]
Hmm it would be annoying to be have it there all the time. I'm thinking of creating some notification system, that shows what we message we want to convey to them, and if you dismiss it, it will never appear again. Can't think of a good way to do this without a back end leh.

**Comment by ngzhian** [comment]
localstorage for persistence? we can hash the key based on the AY and semester, so the user can dismiss it for the current sem and then it will show up again next sem

**Comment by yangshun** [comment]
Done in R's FAQ page
