### ISSUE TITLE
"\n" before "and" in prereq string results in wrong prereq tree

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1749]
### Describe the bug

Reported by a student over email.

> The pre-requisite tree and the actual pre-requisite requirements are different.
> 
> I do not know if this problem only applies to [CS4248](https://nusmods.com/modules/CS4248/natural-language-processing) or may extend out to other modules.

### Screenshots

![D2A6772B9C38464E8F5AA17E26EAB559](https://user-images.githubusercontent.com/12784593/57291150-77273c00-70f1-11e9-8fd6-733dbe165f22.png)

### Additional context

Caused by bad data. The [mod data](https://api.nusmods.com/v2/2018-2019/modules/CS4248.json)'s prereq string (quoted below) has "\n" before the "and", which causes the scraper to ignore it.

> (CS3243 Introduction to Artificial Intelligence or CS3245 Information Retrieval)\nand (ST1232 Statistics for Life Sciences, or ST2131 Probability, or ST2334 Probability and\nStatistics)

Add this test to scrapers/nus-v2/src/services/requisite-tree/parseString.test.ts to reproduce:

```
  it('parses strings with \n in them', () => {
    expect(
      parse('(CS3243 or CS3245)\nand (ST1232, or ST2131, or ST2334 Probability and\nStatistics)'),
    ).toEqual({
      and: [{ or: ['CS3243', 'CS3245'] }, { or: ['ST1232', 'ST2131', 'ST2334'] }],
    });
  });
```

**Comment by ZhangYiJiang** [comment]
The string normalization code should handle this though. Not too hard to replace `\n` and all other whitespace with spaces I think
