### ISSUE TITLE
Module description for MDG5302 is not wrapped

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#1772]
Caused by bad data. The module description has non-breaking spaces instead of regular spaces, causing the lines to not be broken.

https://nusmods.com/modules/MDG5302

The mod's data can be found at https://api.nusmods.com/v2/2018-2019/modules/MDG5302.json

![image](https://user-images.githubusercontent.com/12784593/57604217-34a0ac00-7596-11e9-882d-8a8a6d6e10c3.png)

Also reproducible on the module search page.

![image](https://user-images.githubusercontent.com/12784593/57604352-85b0a000-7596-11e9-9715-ae7bf27d3c5b.png)

## Solution

As this is caused by bad data, we will not fix it on our end but get the school to change the data instead. To be able to report them in a timely manner, the scraper should log errors to Sentry if we detect these cases, which will cause email notifications to be sent to us.

I'd suggest that we log errors when we detect module descriptions with more than 3 consecutive NBSPs not separated by spaces. If you are an external contributor, you won't have access to the internal NUS APIs, but you can still work on this by writing unit tests and making them pass. We'll then run it against the NUS APIs on our side to make sure it works.

**Comment by sciffany** [comment]
Taking this issue :)
