### ISSUE TITLE
Improve UX of Timetable display filter

### ISSUE THREAD

**Issue by tgxworld** [nusmodifications/nusmods#182]
![screenshot from 2015-02-05 07 53 28](https://cloud.githubusercontent.com/assets/4335742/6052294/1a72a9d4-ad0c-11e4-8c23-03b921468ad2.png)

@yangshun Currently, disabled filters are highlighted while active filters are disabled. This seems counter intuitive to me. On top of that, the position of it is too far away from the actual calender. 

What do you think about reversing the highlights and also moving it nearer to the calender?

**Comment by yangshun** [comment]
It's meant to look like that: http://getbootstrap.com/components/#btn-groups. The gray buttons are not disabled, they are being pressed.

I guess can make the active state as background orange with white text.

**Comment by xinan** [comment]
It is indeed quite counter intuitive. Maybe we should just reverse it?

**Comment by xinan** [comment]
Oh no, reversing it also won't work very well. Need to change some colors.

**Comment by yangshun** [comment]
This is the same issue iOS faced when iOS 7 first got released. In its control center, which icons are active?

![iOS7 control center](https://9to5mac.files.wordpress.com/2013/09/21.png?w=321&h=593&crop=1)

iOS8 has changed it to:

![iOS8 control center](http://cdn.iphonehacks.com/wp-content/uploads/2014/07/ios8-beta4-controlcenter.jpg)

But I don't find it much different. Lol.

**Comment by xinan** [comment]
Hahahaha I don't find that much different either. 
For our buttons, I had that thought last night when I saw this:


![img_0262](https://cloud.githubusercontent.com/assets/2834397/6768374/0fb08462-d0a2-11e4-94ef-89150e625834.PNG)

**Comment by yangshun** [comment]
Yes that style is actually adopted for the semesters tabs at the top of the
timetable page. Shall we change to that then?

**Comment by xinan** [comment]
Ya that the semesters tabs feels much better.

**Comment by xbili** [comment]
Closed via [#205](https://github.com/nusmodifications/nusmods/pull/205)
