### ISSUE TITLE
Exported Timetable for Special Terms Not Reflecting Modules

### ISSUE THREAD

**Issue by whneo97** [nusmodifications/nusmods#1824]
### Describe the bug

Downloaded timetable for Special Terms does not reflect added modules.

### To Reproduce

1. Add modules to Special Term I or Special Term II
2. Click on 'Download' > 'Image (.png)' or 'PDF (.pdf)' 
3. Downloaded timetable does not reflect added modules. Only module codes (of added modules) are shown under the timetable

### Expected behavior

Downloaded timetable is expected to contain the schedule for added modules. (This issue does not appear to occur for Semester I and Semester II)

### Screenshots
Intended Timetable: ![image](https://user-images.githubusercontent.com/41929699/58803716-b7bb9c00-8642-11e9-86cc-846c3f7aca15.png)
Downloaded Timetable: ![image](https://user-images.githubusercontent.com/41929699/58803699-b0948e00-8642-11e9-9872-e173d9b173ea.png)

### Desktop (please complete the following information):

* OS: MacOS Mojave Version 10.14.2
* Browser: Chrome
* Version: 73.0.3683.103

### Smartphone (please complete the following information):

* Device: Samsung Note 8
* OS: Android Version 9
* Browser: Chrome 
* Version: 74.0.3729.157

### Additional context
-

**Comment by ZhangYiJiang** [comment]
Thanks for letting us know! Turns out I forgot to switch the production config for the export service to use the new API, so it was still consuming API v1 data, which didn't have special term timetables
