### ISSUE TITLE
Change to FB Page Plugin

### ISSUE THREAD

**Issue by xinan** [nusmodifications/nusmods#188]
Facebook Like Box is deprecated and will stop working soon. 

https://developers.facebook.com/docs/plugins/like-box-for-pages

> With the release of Graph API v2.3, the Like Box plugin is deprecated and will stop working on **June 23rd 2015**. Use the new [Page Plugin](https://developers.facebook.com/docs/plugins/page-plugin) instead. The Page Plugin allows you to embed a simple feed of content from a Page into your websites.

**Comment by yangshun** [comment]
It looks great, let's use that!

**Comment by yangshun** [comment]
Closed via #204
