### ISSUE TITLE
Ugly underline once user has clicked on a link in developers page

### ISSUE THREAD

**Issue by tgxworld** [nusmodifications/nusmods#189]
![screenshot from 2015-03-31 10 27 09](https://cloud.githubusercontent.com/assets/4335742/6911248/9fa0063e-d790-11e4-964c-90d5d91ccc06.png)

Note the underlines are of different thickness

**Comment by xinan** [comment]
Do we need any underline on other places? If we don't want it to be appear anywhere, then we can set the `text-decoration` of all links to `none` hahaha.
