### ISSUE TITLE
Convert Team Page to JSON data

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#190]
The [current team page](http://nusmods.com/team) has its contents hardcoded within the [HTML template](https://github.com/nusmodifications/nusmods/blob/master/app/scripts/about/templates/team.hbs) as it's troublesome to edit the HTML for each person if we want to change the design of that page.

Ideally we should put the content in a JSON file and render it in the template using handlebars, using the same approach as the [Help module](https://github.com/nusmodifications/nusmods/tree/master/app/scripts/help).

**Comment by xinan** [comment]
Wow! This is what I'm thinking about.

**Comment by yangshun** [comment]
Lol let others do it
