### ISSUE TITLE
MA1101R Lab Slot Glitch

### ISSUE THREAD

**Issue by nlopez98** [nusmodifications/nusmods#1989]
### Describe the bug

MA1101R appears to have only 1 lab on week 12 when certain timeslots are clicked.

### Expected behavior

All slots will reflect labs on Weeks 4, 6, 10, 12 (this is only correct on 3 out of 5 at the moment). Cross refer: MA1102R labs.

### Screenshots

![image](https://user-images.githubusercontent.com/41785142/61580269-817aa300-ab42-11e9-80c9-1f827e218535.png)

**Comment by ZhangYiJiang** [comment]
This is not a bug, at least not on our end. The data we're given has exactly one session for lab C4 and C5 on 2019-11-05 and nothing else. We'll email the school about this.
