### ISSUE TITLE
Module Tombstone appears twice on removing module

### ISSUE THREAD

**Issue by dlqs** [nusmodifications/nusmods#1992]
### Describe the bug
Module Tombstone *sometimes* appears twice on removal. (I'm unable to replicate this with every combination of modules, seems to happen only half the time. But it does happen for the 4 in the screenshot)

### To Reproduce

1. Start from a empty schedule
2. Add at least 4 modules, return to timetable view
3. Remove the first one, i.e. the leftmost one in the top row
4. See two module tombstones, and only one is dismissible

### Expected behavior

Just one should show up

### Screenshots

![image](https://user-images.githubusercontent.com/31354724/61645669-b836f180-acd9-11e9-9f47-3bdd09d16cdf.png)

### Desktop (please complete the following information):

* OS: Manjaro
* Browser Firefox 67
* Version 67

**Comment by dlqs** [comment]
I believe that there is a race condition between the action REMOVE_MODULE and marking it as the tombstone. Both are async and usually removal happens first but occasionally the module is marked as the tombstone before its actually removed. Since tombstoned modules are added back in to be sorted, this results in two ModuleTombstones being shown (the original and the tombstone).

That being said, not quite sure how to fix this...

**Comment by ZhangYiJiang** [comment]
@dlqs The issue is similar to a race condition, but it's not really because everything is synchronous. The reason why it seems non-deterministic is because it is actually caused by React itself removing components with the same `key`.
