### ISSUE TITLE
nusmods is down several times

### ISSUE THREAD

**Issue by hidingmode** [nusmodifications/nusmods#2006]
### Describe the bug

slow load times and occasional down times

### Screenshots

![couldnt load](https://user-images.githubusercontent.com/7817101/61965821-61902700-affb-11e9-9825-3331d2472816.png)
![module search fail](https://user-images.githubusercontent.com/7817101/61966000-c8addb80-affb-11e9-99b0-e4599ee63d9e.png)

### Desktop (please complete the following information):

* OS: Windows 10 v1809
* Browser: Firefox
* Version: 68.0.1

**Comment by ZhangYiJiang** [comment]
We've rolled back to our old server while we investigate. Thanks for filing.
