### ISSUE TITLE
Single quotes showing as question mark in GES1021

### ISSUE THREAD

**Issue by anasm6** [nusmodifications/nusmods#2022]
### Describe the bug

Single quotes (') showing up as question marks (?) in the module summary for GES1021

### To Reproduce

1. Go to https://nusmods.com/modules/GES1021/natural-heritage-of-singapore
4. See error in the writeup

### Expected behavior

Single quotes should show as single quotes

### Screenshots

https://imgur.com/aXAInwK

### Desktop (please complete the following information):

* OS: Windows 10
* Browser: Chrome
* Version 75.0.3770.142 (Official Build) (64-bit)

### Smartphone (please complete the following information):

* Device: iPhone SE
* OS: iOS 12.1.4
* Browser: Stock browser, Safari
* Version: 12

### Additional context

Nil

**Comment by ZhangYiJiang** [comment]
This is a data issue, not a bug. We'll check with the school to see where the encoding error occurred, but this is just the school sending us `?` characters in the data

**Comment by ZhangYiJiang** [comment]
Please write to the faculty to update their module description. Most likely someone used Word, which automatically turned the quotes into smart quotes, but then somewhere between them and ModReg the system couldn't cope with that and turned them into question marks instead.
