### ISSUE TITLE
Spell out months in date strings

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#2023]
Our dates are currently formatted ambiguously. Although most of the world uses day-month-year, the US uses month-day-year, resulting in 2 possible interpretations for days <=12. We should spell out the months instead.

![image](https://user-images.githubusercontent.com/12784593/62180210-c2b05580-b381-11e9-93ce-e008814997a7.png)

![image](https://user-images.githubusercontent.com/12784593/62180233-de1b6080-b381-11e9-8616-b2ab19689870.png)

![image](https://user-images.githubusercontent.com/12784593/62180250-ea072280-b381-11e9-8229-7a4abafb1c6f.png)

**Comment by shimeilee** [comment]
Hi, may I take this issue? :)

**Comment by li-kai** [comment]
@shimeilee Sure, feel free to take this!

**Comment by ZhangYiJiang** [comment]
Do note that the same code is also used in other places. Make sure the changes make sense in those places too, or create a different function
