### ISSUE TITLE
Add clarifications to module reviews

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#2024]
Request from Registrar and RO.

## Requirements

NUS wants to communicate 2 main things to users:

1. The reviews have not been validated, and so they are not the official position of NUS or NUSMods.
2. Inform teaching faculty (and students) that the reviews are not a feedback platform.

They asked for this disclaimer:

> All postings, comments and responses contained in this section reflect the opinions and views of the author(s) and unless otherwise specifically stated, do not reflect the views or opinions of NUSMods or the National University of Singapore (NUS).

We thought we should communicate that in a clearer manner on NUSMods so that it'll read less like legalese and hopefully be more meaningful to readers.

## What we'll do

We've discussed with Registrar, and we've agreed to change the text in this screenshot:

<img width="767" alt="image1" src="https://user-images.githubusercontent.com/12784593/62180490-cdb7b580-b382-11e9-9b49-c8997d322432.png">

Draft new text:

> Hi There!
> We would like to encourage everyone who enjoyed using NUSMods to contribute back to the community by writing reviews for modules that you have taken before. Your efforts will go a long way in building up a vibrant and rich NUS community.
> 
> Please note:
> 1. Because the experience of each module will differ according to the professor teaching the module, at the start of your review, please state the semester taken and the name of the professor who taught the module in that semester.
> 2. Other students will read your review to get an idea of what taking the module will be like. If you'd like to give feedback about the module to NUS, please use the official Student Feedback system as NUS does not monitor these reviews.
> 3. The claims made in these reviews have not been verified by NUS or NUSMods. Please take all claims with a grain of salt.

**Comment by J0** [comment]
Hi @taneliang, can I take this issue?
