### ISSUE TITLE
Add relative time to ModReg notifications

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#2033]
The current date format is clear, but it's difficult to tell when the date is relative to the current time.

![image](https://user-images.githubusercontent.com/12784593/62441283-093cf000-b786-11e9-9be8-ce4e22ce1eae.png)

We should change it to something like:
“Current: **Select Modules** (Round 2) till **Wed 7th August, 12p.m.** (2 days 12 hours from now)”

Any suggestions to improve the wording are welcome.

## Key things to test

* Ensure that relative dates work in other timezones
* Show more granular time units (i.e. days, hours, min, sec) as we approach the date

**Comment by taneliang** [comment]
Taken by @j0

**Comment by davidchoo12** [comment]
You can probably can use this https://momentjs.com/docs/#/displaying/tonow/

**Comment by taneliang** [comment]
We'd rather not use Moment.js due to its weight – we use the much lighter date-fns instead :)

**Comment by J0** [comment]
oh wow @taneliang . Sorry I completely forgot about this. I think @afterdusk will be taking this issue instead since he's on SHN and he's looking for something to do.

**Comment by ZhangYiJiang** [comment]
Fixed by #2575
