### ISSUE TITLE
NUS Mods website does not load. Only white screen is shown

### ISSUE THREAD

**Issue by ZY-Ang** [nusmodifications/nusmods#2038]
### Describe the bug

[nusmods.com](https://nusmods.com) does not show anything on load. `window.location.reload(true)` and clearing of cookies does not help. On load, console outputs an `Uncaught SyntaxError: Unexpected token <` error message from within the app js bundle.

### To Reproduce

1. Go to nusmods.com
2. If on cached nusmods.com, clear using `window.location.reload(true)` or `Ctrl+F5` or clearing cookies.

### Expected behavior

White screen, syntax error, no application loaded

### Screenshots

![Screenshot 2019-08-07 11 59 31](https://user-images.githubusercontent.com/23255196/62593948-4d0d3200-b90b-11e9-8bb7-69eb6bf3fdf2.png)

### Desktop (please complete the following information):

- Chrome 76 on Windows 10
- Opera 62 on Windows 10

### Smartphone (please complete the following information):

Untested

### Additional context

Was trying to force refresh nusmods because the timetable for my classes were still stuck from AY18/19 S1. Force reload creates white screen. Force reload method was working prior to this week.

**Comment by ZhangYiJiang** [comment]
This should be fixed now. Feel free to drop a comment if it is not.
