### ISSUE TITLE
Navbar icons for external links remain highlighted after links are visited.

### ISSUE THREAD

**Issue by xbili** [nusmodifications/nusmods#212]
An example would be the NUSWhispers icon after a user visits the page. 
![screen shot 2015-05-21 at 12 27 14 am](https://cloud.githubusercontent.com/assets/4846457/7731023/4134c796-ff50-11e4-8ebf-4d02476066a6.png)

To reproduce:

1. Click on the NUSWhispers icon in navbar
2. Upon returning to NUSMods, the icon remains highlighted

**Comment by xinan** [comment]
It doesn't happen in Safari. But it does happen in Chrome.
