### ISSUE TITLE
Remove added module(s) from the drop down list

### ISSUE THREAD

**Issue by iamjackslayer** [nusmodifications/nusmods#2139]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I couldn't remove an added module directly from the drop down module list. Currently user has to close the drop down list and look for bin icon in the modules table. 

### Describe the solution you'd like
Allow user to directly remove an added module from the drop down list.

Simply tap on the module from the drop down list to remove it.

### Describe alternatives you've considered
Add trashcan icon in the each item(row) in the drop down list. 

Tap the trashcan icon in the drop down list to remove the corresponding module.

**Comment by sciffany** [comment]
Will take this issue

**Comment by ZhangYiJiang** [comment]
Fixed by #2271
