### ISSUE TITLE
Module not found error message persists after searching for a module

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#2183]
### Describe the bug

Module not found error message persists even after searching for a module.

### To Reproduce

1. Go to https://nusmods.com/modules/abc. You should see a module ABC not found message.
2. Use NUSMods' global search to search for a module. 
![image](https://user-images.githubusercontent.com/12784593/66017886-3ea85480-e50f-11e9-8b03-176b7be44756.png)
3. Select a module.
4. The module not found error page still remains, even though it is updated with the selected mod's data. 
![image](https://user-images.githubusercontent.com/12784593/66017916-70b9b680-e50f-11e9-95be-27c15b804922.png)

### Expected behavior

The module data should be displayed instead of the error page.

![image](https://user-images.githubusercontent.com/12784593/66017923-7dd6a580-e50f-11e9-86da-c0dbbcaa154a.png)

**Comment by RisingGeek** [comment]
I would like to take up this issue.

**Comment by taneliang** [comment]
Thanks @RisingGeek! Feel free to reach out if you have any issues and we'll be happy to help.
