### ISSUE TITLE
Speed up Netlify build

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#2185]
### Is your feature request related to a problem? Please describe.

Netlify is limited build time limits to their CI/CD. We need to cut down our build time.

### Describe the solution you'd like

Webpack should take less time to build in Netlify environment

- [ ] Skip timetable webpack build
- [ ] Skip timetable file size measurement
- [ ] Cache babel-loader and HtmlWebpackPlugin if possible

### Describe alternatives you've considered

See if we can skip building/use cache by checking if file changes are within /website folder.  This might break Netlify Deploy Preview though.

### Additional context

NIL

**Comment by ZhangYiJiang** [comment]
We might also want to merge in Renovate PRs more quickly, since the number of builds grows quadratically to the number of Renovate PRs, which automatically rebuild with every merge

**Comment by ZhangYiJiang** [comment]
Alternatively can Netlify just pull built assets from CircleCI? That would make the built time limit trivial I think

**Comment by ZhangYiJiang** [comment]
Fixed by https://github.com/nusmodifications/deploy-preview-bot
