### ISSUE TITLE
Duplicated removed module when remove module at Timetable page

### ISSUE THREAD

**Issue by miaoanbang** [nusmodifications/nusmods#2243]
### Describe the bug

At Timetable page, after clicking remove on one of the modules, which is not the last in the list, there will be duplicated removed module entry.
After that, click dismiss on one of the removed module, it is dismissed but the other still persist and cannot be dismissed.

### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Screenshots

Duplicated entry:
![image](https://user-images.githubusercontent.com/26129084/67541869-1c27e680-f71d-11e9-868c-ce946e85a504.png)

Only one can be dismissed:
![image](https://user-images.githubusercontent.com/26129084/67541898-3792f180-f71d-11e9-9821-e6ee93664e53.png)

### Desktop (please complete the following information):

* OS: [e.g. iOS] MacOs
* Browser [e.g. Chrome, Safari] Chrome
* Version [e.g. 22]  77.0.3865.120 

### Smartphone (please complete the following information):

* Device: [e.g. iPhone 8]
* OS: [e.g. iOS 12.0.0]
* Browser [e.g. Stock browser, Safari]
* Version [e.g. 22]

**Comment by ZhangYiJiang** [comment]
This has been fixed in https://github.com/nusmodifications/nusmods/pull/2101. The change has not yet been deployed.
