### ISSUE TITLE
Highlight the current date in the exam calendar if in range

### ISSUE THREAD

**Issue by jonchan51** [nusmodifications/nusmods#2328]
### Is your feature request related to a problem? Please describe.

Just a random thought. While most people will know what the current date is, I think it would be good to have some sort of highlight/indication of the current date in the exam calendar so looking at the exam calendar does not require any thinking, a user would know what the current date is at a glance without any other reference. Not sure if this would be useful or easy to implement though.

### Describe the solution you'd like

If the current date is within the range of the exam calendar view, the current date grid could be highlighted / outlined / marked / colored.. many possible alternatives, just different from the other grids. If it isn't in the range, then it would look the same as it does right now.

**Comment by liujiajun** [comment]
Hi, this sounds like a good feature and I am interested in taking this. 
I am thinking of adding a badge saying "Today" beside the date. Is this okay?

**Comment by ZhangYiJiang** [comment]
Fixed by #2449
