### ISSUE TITLE
Migrate CS1010FC module reviews to CS1010X

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#233]
[CS1010FC](https://nusmods.com/modules/CS1010FC) has been rebranded as [CS1010X](https://nusmods.com/modules/CS1010X). Prof @benleong requested that we transfer the module reviews from CS1010FC over to CS1010X.

**Comment by benleong** [comment]
Not rebranded lah. NUS RO just decided to change the course code.

**Comment by ngzhian** [comment]
By reviews, you mean the ones on disqus?

**Comment by yangshun** [comment]
Yes. It's not an NUSMods thing. I'll send u the disqus credentials

**Comment by ngzhian** [comment]
I actl tried it, but don't think there's a way for disqus to migrate the threads....

**Comment by yangshun** [comment]
I think we have to manually move them and the links to the original author will be broken (we did that once during migration). Not crucial already actually; I added a link back to CS1010FC page. Let's close this 😄

**Comment by yangshun** [comment]
Have manually copied the threads from CS1010X to CS1010FC page (:
