### ISSUE TITLE
USP Module ULS2206 Timetable Error

### ISSUE THREAD

**Issue by yingchen0505** [nusmodifications/nusmods#2367]
### Describe the bug

Discrepancy between the timetable shown in NUSMods and the information on USP official website. 

### To Reproduce

1. Go to semester 2 timetable
2. Add ULS2206 
3. ULS2206 appears on Tues & Thurs 4-6pm. However, it should be 12-2pm according to USP official website at: http://www.usp.nus.edu.sg/curriculum/module-timetable/inquiry-tier-semester-2-academic-year-2019-2020/

### Expected behavior

Information corresponds with http://www.usp.nus.edu.sg/curriculum/module-timetable

### Desktop (please complete the following information):

* OS: Windows 10
* Browser: Chrome
* Version: 79.0.3945.79 (Official Build) (64-bit)

**Comment by taneliang** [comment]
Seems like the USP website you linked to has been updated with the dates NUSMods had :) We couldn’t have fixed this ourselves anyway since we get our timetable data directly from NUS.
