### ISSUE TITLE
ST2131 has lesson 1200-1200hrs

### ISSUE THREAD

**Issue by SwampertX** [nusmodifications/nusmods#2382]
### Describe the bug
There is a timetable cell for a certain module (ST2131) that cannot display properly, for a certain tutorial time slot. I have not checked if this can be extended to other modules/slots.

### To Reproduce
I have reproduced this in both Firefox with addons disabled.

1. Go to "Semester 2" on the Timetable page.
2. Add **ST2131** as a module.
3. Select tutorial slot 3.
4. The timetable cell is partially filled.

![image](https://user-images.githubusercontent.com/17807016/71422577-33079c80-26be-11ea-9c3e-4323bcbf2338.png)

### Expected behavior

The timetable cell should be fully filled.

### Screenshots

Added above.

### Desktop (please complete the following information):

* OS: Ubuntu 19.10
* Browser: Firefox Nightly
* Version: 72.0a1

### Smartphone (please complete the following information):

* Device: Xiaomi A2 Lite
* OS: Android 9
* Browser: Firefox Preview
* Version: 3.0.1

### Additional context
My gut feeling is should be reproducible across different browsers. Do tell me if this is a duplicate!

**Comment by ZhangYiJiang** [comment]
It looks like (according to the school at least) the lesson really does have a start and end time of 1200hrs. We can probably flag data anomalies like this in our scraper, but what you can do is send an email to the faculty in question asking them to check their data on ModReg

**Comment by taneliang** [comment]
Thanks for reporting this!

As @ZhangYiJiang said, this isn't a bug with NUSMods. Please click this button on the [module's page](https://nusmods.com/modules/ST2131/probability) and follow the link to report this error to the faculty offering this mod.

![0E25520B-9AC9-43EE-9153-C8C4230AF51D](https://user-images.githubusercontent.com/12784593/71427914-2e5fda00-26f8-11ea-8c41-d6d9bc92cc7a.jpeg)

I've found a related bug though, and I've filed a separate issue: #2383. Closing this as it's a data issue.
