### ISSUE TITLE
Google Calendar Import Fails For .ics File Exported

### ISSUE THREAD

**Issue by KaranKamath** [nusmodifications/nusmods#239]
Timetable used: http://modsn.us/nmFl8

Steps to reproduce this problem:

1. Export to .ics using "Export" dropdown
2. Go to your Google Calendar
3. "Other Calendars" dropdown -> Import Calendar
4. Select file to import
5. Click "Import"

![screen shot 2015-08-19 at 10 15 46 pm](https://cloud.githubusercontent.com/assets/3609286/9358882/e28c2d0c-46c0-11e5-82ad-81f74bbbacac.png)
![screen shot 2015-08-19 at 10 15 59 pm](https://cloud.githubusercontent.com/assets/3609286/9358883/e2e0ac38-46c0-11e5-8c58-449a637599cb.png)

**Comment by ahbeng** [comment]
@KaranKamath Could you try again please? Using your link I was able to import both to both iCal and Google Calendar. If it's still broken could you link the .ics file so we could compare? Otherwise it might have been a temporary Google Calendar issue.

**Comment by KaranKamath** [comment]
https://s3-ap-southeast-1.amazonaws.com/nusmods-ics/My+NUSMods.com+Timetable.ics

Tried with Safari and Chrome, but likely to be a machine specific issue, as it seems to work for others.

**Comment by ngzhian** [comment]
closed because unreproducable
