### ISSUE TITLE
FAB modal page layout bugs

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#2398]
### Describe the bug

FAB modal things aren’t displayed correctly (see screenshots)

### To Reproduce

1. Go to https://nusmods.com/modules/ACC1002/financial-accounting or https://nusmods.com/modules on a phone
2. Click on the FAB

### Screenshots

![856DF446-9792-4DD9-9C57-E5C27F19CEE6](https://user-images.githubusercontent.com/12784593/71616835-371e4780-2bf3-11ea-91f6-82883fc5846e.png)
![955FC0D8-06F5-4F23-B1B8-F7E55C0A1D1F](https://user-images.githubusercontent.com/12784593/71616849-49988100-2bf3-11ea-9f13-12a0cfe3cf35.png)

### Smartphone (please complete the following information):

* Device: iPhone 11
* OS: iOS 13.3
* Browser: Safari

**Comment by shimeilee** [comment]
For reference: https://github.com/nusmodifications/nusmods/pull/2269 might have caused the bug. Build 2268 (merged before it) was ok, and subsequent builds from 2269 have this module finder bug. 

This issue might be specific to mobile ie cannot be replicated on web browser -> limiting the viewport. 

I would like to try this issue :)

**Comment by taneliang** [comment]
Oops my bad. Thanks for looking into this!

**Comment by ZhangYiJiang** [comment]
I can repro on Firefox in responsive design mode, no need to get a phone for this
