### ISSUE TITLE
URL shortener does not paste correctly in Pushbullet

### ISSUE THREAD

**Issue by myrtleTree33** [nusmodifications/nusmods#240]
When shortened URL is pasted into Pushbullet, e.g. http://modsn.us/sFC45 , URL expands to the long version of URL (which is not entirely clickable).

**Comment by xbili** [comment]
Hi there @myrtleTree33, thanks for reporting! 

Does other shortened links such as bit.ly have the same issue on Pushbullet as well?

**Comment by yangshun** [comment]
Not reproducible.
