### ISSUE TITLE
NUS Mods Mobile App No Longer Appears To Be Supported?

### ISSUE THREAD

**Issue by whneo97** [nusmodifications/nusmods#2402]
### Describe the bug

NUS Mods does not load and cannot be found on the Playstore or NUS Mods website after uninstalling.

### To Reproduce

1. Open the NUS Mods Mobile App. (observed on Android device).
2. White Screen is shown that does not load.

*b. Uninstall the NUS Mods application.
*c. Search for NUS Mods application in the Playstore or via the NUS Mods website.
*d. NUS Mods application cannot be found and redownloaded.

### Expected behavior

NUS Mods home page with timetable was expected to be shown, but white screen was observed for around a week. NUS Mods app was expected to be able to be reinstalled after uninstalling.

### Screenshots

NIL

### Desktop (please complete the following information):

NA

### Smartphone (please complete the following information):

* Device: Galaxy Note 8
* OS: Android V9
* Browser NA
* Version NA

### Additional context

NIL

**Comment by ZhangYiJiang** [comment]
I'm confused. NUSMods was never offered as a mobile app on the Play Store. If you did install something from the store, the store will show it if you go to My apps & games > Library, which will show you a list of apps that you've previously installed on any of your devices. It would be great if you can share a link to what you had installed before

**Comment by whneo97** [comment]
> I'm confused. NUSMods was never offered as a mobile app on the Play Store. If you did install something from the store, the store will show it if you go to My apps & games > Library, which will show you a list of apps that you've previously installed on any of your devices. It would be great if you can share a link to what you had installed before

Well this is really strange, sorry I'm unable to find it under library either. :/ I'd been using this application with the NUSMods logo and web features (eg. theme) for the past three semesters now. When an NUSMods link is clicked on from my phone, I had the option to import the calendar into the app as well. Only recently when the app was unable to load properly did I decide to reinstall it, only to find that it appears to no longer be available? 

This is what the interface looked like from old screenshots.

![20200102_103601](https://user-images.githubusercontent.com/41929699/71649736-0dc4ff00-2d4c-11ea-9bdf-c03e02f0a82c.jpg)
![Screenshot_20200102-103715_Gallery](https://user-images.githubusercontent.com/41929699/71649739-10bfef80-2d4c-11ea-843d-7bfdfa1c65b6.jpg)
![Screenshot_20200102-103727_Gallery](https://user-images.githubusercontent.com/41929699/71649741-14ec0d00-2d4c-11ea-8425-d2af912444d5.jpg)
![Screenshot_20200102-103742_Gallery](https://user-images.githubusercontent.com/41929699/71649744-17e6fd80-2d4c-11ea-8462-34bf009948e6.jpg)

**Comment by ZhangYiJiang** [comment]
Ah, got it. This is because we removed the service worker we were using to enable offline support since not many people relied on this feature and it was difficult to maintain. A side effect of this is that Chrome mobile doesn't consider NUSMods a proper Progressive Web App (https://developers.google.com/web/fundamentals/app-install-banners/#criteria) anymore, which means it doesn't display the app install banner. 

You can still add to your home screen NUSMods by going to the menu and clicking on 'Add to home screen', though this will add the site to the homepage as a bookmark, which means the Chrome logo will show on the corner, which is slightly annoying.

**Comment by whneo97** [comment]
> Ah, got it. This is because we removed the service worker we were using to enable offline support since not many people relied on this feature and it was difficult to maintain. A side effect of this is that Chrome mobile doesn't consider NUSMods a proper Progressive Web App (https://developers.google.com/web/fundamentals/app-install-banners/#criteria) anymore, which means it doesn't display the app install banner.
> 
> You can still add to your home screen NUSMods by going to the menu and clicking on 'Add to home screen', though this will add the site to the homepage as a bookmark, which means the Chrome logo will show on the corner, which is slightly annoying.

Hi, okay thanks so much for the clarification!!
