### ISSUE TITLE
Hide whole modules from timetable

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#248]
Received a PM via NUSMods FB page:

> Hey NUSMods, thanks for doing the timetable for us. A feedback i have is to make a 'hide' function for modules placed on the calendar. This will help to reduce clutter when we are trying to see the various combinations our timetable can become. I have like 10mods on the timetable cause those are what im thinking of and its becoming more difficult to see. Hope this helps!

**Comment by xinan** [comment]
We may implement this by setting the classes's group number to `-1` in the url params. Something like:
```
...&CS4231[LEC]=-1&...
```
Then for any classes that has group number `-1` we hide it.

Btw if we are gonna do this I think we should allow users to choose whether to hide everything of the module, or just one or more classes of it. For example, keeping only 1 tutorial while hiding lectures and other tutorials can be very useful for TAs.

**Comment by yangshun** [comment]
Sad, I set a lecture to -1 and it disappeared. Have to delete and readd the module :(

But sounds like a plan.

**Comment by xinan** [comment]
Of course we will have an option to re-display them :expressionless:

**Comment by xinan** [comment]
This sounds more useful, how about doing this tmr instead?

**Comment by yangshun** [comment]
@_@ discuss again. Either way we should get our code merged one day, don't want it to go to waste :X

**Comment by yangshun** [comment]
@ngzhian if you are interested you can try this (:

**Comment by ngzhian** [comment]
Let's do this in v3 alpha instead? Might be a good reason to entice ppl to try/test v3 :)

**Comment by yangshun** [comment]
Oh yes I mean do this in v3 not v2. We shouldn't be adding features to v2 anymore (:
