### ISSUE TITLE
[Design] Group by Faculty

### ISSUE THREAD

**Issue by 9gix** [nusmodifications/nusmods#25]
Why the courses are no longer grouped in the new release?

The issue with this design is that I couldn't browse for the courses under a certain school.
For example: I wanted to browse for all module under "School of Business", or "School of Computing", I have to find out what are the courses from school of computing and school of business. Such as:
1. Information System
2. Computer Science
3. Financial Accounting
4. Strategy & Policy
5. etc..

![screenshot from 2014-07-07 14 31 42](https://cloud.githubusercontent.com/assets/493668/3491938/6d302854-05a0-11e4-9de7-706b5a8308cb.png)

**Comment by ngzhian** [comment]
Does this involved mapping the more specific department names to the faculty names, and the mapping can be found here: http://api.nusmods.com/2015-2016/1/facultyDepartments.json ?

**Comment by ahbeng** [comment]
Spot on! I vaguely recall experimenting with UX for a collapsible checkbox tree, but can't find the code, maybe it was for a previous iteration. I think the minimal implementation would be just the grouping, without any additional checkboxes. IIRC in the past, faculties had their own checkbox, which would select all the departments underneath if checked.

**Comment by ngzhian** [comment]
Woots, getting somewhere :) Any comments on the "undefined"? Seems like we have 2 departments:
- Division Of Environmental Science & Engg
- Office Of Student Affairs

Call it others?

<img width="339" alt="screen shot 2016-07-23 at 12 34 16 am" src="https://cloud.githubusercontent.com/assets/1749303/17076672/3bba8566-506d-11e6-8d61-75645db7ff93.png">

**Comment by ahbeng** [comment]
Looks great, "Others" SGTM!
