### ISSUE TITLE
ghit.me bdage doesn't show up on github page

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#253]
what's that supposed to be? ghit.me doesn't seem to be anything, can we remove it?

**Comment by yangshun** [comment]
It is supposed to show how many users visited this Github project. Seems to be down at the moment. I'll monitor this and if the service is closed I'll remove it.

**Comment by yangshun** [comment]
It's up again already. 
![screen shot 2016-02-03 at 1 33 03 pm](https://cloud.githubusercontent.com/assets/1315101/12773868/b709fe28-ca7a-11e5-8b8b-27386e3874a9.png)
