### ISSUE TITLE
Contributors page leads to "We can't load venues..."

### ISSUE THREAD

**Issue by dlqs** [nusmodifications/nusmods#2536]
### Describe the bug

The link https://nusmods.com/contributors leads to "We can't load venues ..."

### To Reproduce

1. Click on our contributors link at the bottom of page or access https://nusmods.com/contributors

### Expected behavior

Should show contributors

### Screenshots

![nusmods com_contributors (1)](https://user-images.githubusercontent.com/31354724/75745008-ec36c280-5d50-11ea-9aa2-bde7d105ea98.png)

### Desktop (please complete the following information):

* OS: Manjaro Linux
* Browser: Firefox 72, Chromium 79

**Comment by dlqs** [comment]
https://github.nusmods.com/repo/contributors (alias for https://api.github.com/repos/nusmodifications/nusmods/contributors) is up but doesn't seem to be returning anything

**Comment by taneliang** [comment]
Thanks for reporting this! Turns out the server behind our reverse proxy ran out of disk space. It's working again now. The separate fix for the misleading error message is in the open PR #2537.
