### ISSUE TITLE
Unexpected Behavior from the action buttons.

### ISSUE THREAD

**Issue by 9gix** [nusmodifications/nusmods#26]
When I click the show-hide action of a particular module, a random outcome appear on the timetable.
In the screenshot, you see the module ES1102, get displayed multiple times.

After this behavior, I also can't remove some of the other module on my list.

![screenshot from 2014-07-07 15 47 33](https://cloud.githubusercontent.com/assets/493668/3492495/12d15512-05ab-11e4-88a1-82a88d4aaf24.png)

**Comment by yangshun** [comment]
No longer relevant.
