### ISSUE TITLE
Do we really need a "like" button for each module at /modules ?

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#260]
I find usage really low, and (not tested experimentally) feel that so many iframes slow down the page slightly :P 
See picture:
![1](https://cloud.githubusercontent.com/assets/1749303/12953890/4ea7618a-d057-11e5-8c0d-714c5405d94e.PNG)

**Comment by yangshun** [comment]
Hmm this has been discussed before. Ok let's remove it from the module finder list. Thanks

**Comment by ngzhian** [comment]
Yay for less facebook! :D
