### ISSUE TITLE
Tab to search in chrome address bar

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#262]
It would be cool if we type in nusmods and press tab and we can search for a mods on nus mods :)
The way to implement it is specified pretty clearly here:
https://www.chromium.org/tab-to-search.

Might require adding a new url (to handle search) that does a redirect to one of the module pages.

**Comment by xinan** [comment]
I think `https://nusmods.com/modules/<ModuleCode>` would work but currently if the module doesn't exist we just show a blank page.

**Comment by yangshun** [comment]
Closed via #270
