### ISSUE TITLE
FB has no preview image when sharing module links

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#265]
e.g.
<img width="521" alt="screen shot 2016-07-05 at 9 28 21 am" src="https://cloud.githubusercontent.com/assets/1749303/16592032/9c9d1818-4293-11e6-9949-9788d3bdd38e.png">

**Comment by yangshun** [comment]
Fixed via e7c40a6

<img width="484" alt="screen shot 2016-07-06 at 7 15 40 pm" src="https://cloud.githubusercontent.com/assets/1315101/16616197/46bb46ce-43ae-11e6-9c9f-e1f4d0e00314.png">
