### ISSUE TITLE
Write a script to generate cors schedule

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#271]
The json files are in:
https://github.com/nusmodifications/nusmods/tree/master/app/scripts/cors, right now it's manually written, write a script to crawl it from cors website.

**Comment by Kowalski985** [comment]
Hi there! I'm interested in helping out with this issue and I've already finished most of the code for the web crawler. I just have a question, does round 2A always has 2 open bidding periods? I hard coded that part in for now and I'm not sure if I should change it to make it a bit more general.

**Comment by li-kai** [comment]
@Kowalski985 Hi Kyle, were you part of Infocomm Ambassadors? 

Anyway I'm not sure if round 2A always had it that way. It would be nice if you had some code to show us so we can guide you along. [Write a gist here](https://gist.github.com/) and link it to us 😄

**Comment by yangshun** [comment]
Hey @Kowalski985 thanks for your interest! You can also submit a PR and we can comment on it. Might be easier that way (:

**Comment by yangshun** [comment]
Closed via #324
