### ISSUE TITLE
Implement Covid zoning as indexable lesson / module metadata 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#2748]
### Is your feature request related to a problem? Please describe.

It should be possible to combine our crowdsourced venue latlon with NUS Covid zoning https://emergency.nus.edu.sg/downloads/NUS_Campus_Zonal_Map.pdf so that students can see which zone a lesson is in, and search by zones on the module page 

### Additional context

The scraper will need to load venue data to access the coordinates. We'll also need to manually draw out a polygon enclosing the different zones.

**Comment by agnesnatasya** [comment]
Hii, can I clarify about this? The desired feature is to add a filtering component in ModuleFinder according to zoning, and it uses the data from `data/venues.json` to categorise them?  For the 'manual draw out of the polygon, does it mean that we need to hardcode the latitude and longitude borders of the different zones?

Thank you!!

**Comment by ZhangYiJiang** [comment]
ModuleFinder uses ElasticSearch as the backend, so to implement this we will need to do it on the scraper instead of just the website frontend. The scraper will need to load data/venues.json and map of each venue there to their zone. We do need to hard code the borders of the different zones (preferably also in a data file so it can be updated without changing the code), but we only need the boundaries where they touch each other, since the other edges can be larger than the campus (we're not using the boundaries for visualizing the zones, only to categorize each venue). The BTC and Outram campus can just be covered by a large rectangle. 

The more interesting question is where the zone should be in the data. We can add the zone property to the `Venue`, but for ES to be able to filter modules, the `Module` object will need also need a zone property. It might also be useful to add it to `Lesson`, though that is duplicating some information, it might be worth not having to separately look up this information in a separate file.

**Comment by davidchoo12** [comment]
I quickly drew up the zoning separation lines on Google MyMaps: https://www.google.com/maps/d/edit?mid=1YvYaNRFCLXS23eFux7gc4fihhxaab4Gm&usp=sharing
You can check the coordinates of the lines' points by exporting it as KML file.
Is this what you're looking for?

**Comment by ianfromdover** [comment]
Can this issue be closed since the zoning system has now been decomissioned?
