### ISSUE TITLE
Increase the contrast of navigation links

### ISSUE THREAD

**Issue by jeffsieu** [nusmodifications/nusmods#2770]
## Problem

The contrast of navigation bar links is poor, leading to readability issues, especially in bad lighting conditions.

### Current state

Poor text contrast of 2.15 on light mode and 2.74 on dark mode (Doesn't fulfill WCAG 2.0 Guidelines)

![image](https://user-images.githubusercontent.com/8487294/88276566-d894f400-cd11-11ea-8626-8b54b71e76a4.png)

![image](https://user-images.githubusercontent.com/8487294/88276123-1d6c5b00-cd11-11ea-9af6-d0750d85fe9c.png)

### Proposed solution

Increase the contrast of navigation bar links, as shown below.

![image](https://user-images.githubusercontent.com/8487294/88276932-712b7400-cd12-11ea-85e4-c5bc02a2852e.png)
![image](https://user-images.githubusercontent.com/8487294/88276345-776d2080-cd11-11ea-82c8-ac6a2ce22283.png)

**Comment by taneliang** [comment]
Fixed by #2786
