### ISSUE TITLE
A wrong URL will cause the app to reach an undefined state

### ISSUE THREAD

**Issue by tysng** [nusmodifications/nusmods#2801]
### Describe the bug

When reading the module information from the URL, the app doesn't check whether the imported module belongs to the current semester. This cause modules that aren't offered in the current semester to be added to the timetable. 

### To Reproduce

1. Go to https://nusmods.com/timetable/sem-1/share?CS4215=TUT:2,LEC:1

### Expected behavior

The list of modules should be empty, since CS4215 is not offered in Semester 1. 

### Screenshots

<img width="867" alt="Screenshot 2020-08-04 at 12 06 33 AM" src="https://user-images.githubusercontent.com/42670338/89203045-788e2f80-d5e6-11ea-8d80-26a64c723f2b.png">

The module is selected for the current semester, but it doesn't show up on the timetable, since it's not offered in the current semester.

### Desktop (please complete the following information):

MacOS, Chrome Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by taneliang** [comment]
Interesting! Thanks for reporting this. I don't think we'll want to fix this though, since it isn't our goal to support user-modified URLs
