### ISSUE TITLE
Babel?

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#281]
So we can write ES2015 code :)

Out of curiousity, found out that facebook/react uses browserify, grunt, and gulp. They do this thing where they babel-fy all their source code, then use browserify to bundle them up, we can probably do something like this? But I'm not sure how well that will work with watchify.

**Comment by yangshun** [comment]
@ngzhian Sure, why not, but if it's too much effort to add then probably not worth it

**Comment by ngzhian** [comment]
Note for future: how facebook does it is run each source file through babel (https://github.com/facebook/react/blob/master/gulpfile.js#L81), then run the result through browserify.

https://www.npmjs.com/package/gulp-babel

**Comment by ngzhian** [comment]
deprecated in favour of webpack, and also v3 \o/
