### ISSUE TITLE
Unable to export timetable as ics file

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#282]
Reported by JiEn Lee via Facebook:

> Hi! I don't seem to able to export the .ics file for my timetable: https://nusmods.com/timetable/2016-2017/sem1?LL4009V[SEM]=1&LL4076V[SEM]=1&LL4077V[SEM]=1&LL4244V[SEM]=1

> Could you see if the funciton is working?

> I tried various browsers. All not working. PDF/.jpg export is working.

**Comment by ngzhian** [comment]
This is the error:
<img width="746" alt="screen shot 2016-07-25 at 11 12 28 pm" src="https://cloud.githubusercontent.com/assets/1749303/17127832/6582224e-52bd-11e6-915d-e8274fe2ac64.png">

**Comment by ngzhian** [comment]
OH lol, we didn't update academicCalendar.json :P

**Comment by yangshun** [comment]
😵 nice catch, so fast! We need to come up with a reference document on the maintenance stuff that we need to do every semester / year.

**Comment by ngzhian** [comment]
good idea on the reference doc, tracking that in #284 :)
