### ISSUE TITLE
Doc on what to do whenever there is a new sem

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#284]
E.g.
1.  we need to update `academicCalendar.json`,
2. Add cors timetable
3. uncomment the html for CORS alerts

First suggested https://github.com/nusmodifications/nusmods/issues/282#issuecomment-235173209

**Comment by yangshun** [comment]
Come up with a reference document on the maintenance stuff that we need to do every semester / year so that new members of the team can help in maintaining.

@ngzhian you so fast, i was halfway creating the issue lol

**Comment by ngzhian** [comment]
@yangshun LOL sorry i sitting at home watching tv that's why got time to do this HAHA

**Comment by yangshun** [comment]
I don't think I have the capacity and context to take on this task. @ZhangYiJiang and @taneliang could you all work on this together with @li-kai ?
