### ISSUE TITLE
Missing module - EC3373

### ISSUE THREAD

**Issue by jeeminbang** [nusmodifications/nusmods#2858]
### Describe the bug

Hi for semester 2 AY2020/21, the econ department is hosting EC3373 Asean Economies. (https://www.fas.nus.edu.sg/ecs/undergraduate/modules.html)

But cannot find details to this mod in nusmods. 

### To Reproduce

1. Go to nusmods and type EC3373 and mod doesn't appear.
2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Can you add details to this module further? Because it is confirmed that it will be taught in semester 2 by the department.
I don't think this is a desktop or smartphone issue but just missing info!

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. Chrome, Safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone 8]
* OS: [e.g. iOS 12.0.0]
* Browser [e.g. Stock browser, Safari]
* Version [e.g. 22]

**Comment by ZhangYiJiang** [comment]
Please reach out to the faculty directly. You can find the contact information on ModReg website. NUSMods directly use information provided by the school, so we cannot add more information for any modules
