### ISSUE TITLE
Feature Request: Add Weekends and Self-Study Slots

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nusmodifications/nusmods#2893]
### Describe the solution you'd like

I would like to request for the timetable to be expanded to include the following:

- Saturday and Sunday slots
- Options to "block out" time slots for self-revision

I believe that this would better help fellow students plan their own revision times on the same timetable that they generated.
Thanks!

EDIT 1:
To add on, I would also like to suggest having the option to toggle time slots that span a longer time compared to the default view with no modules loaded (E.g. maybe default view can show from 0800 to 2100). Again, it's to facilitate self-study planning.

**Comment by taneliang** [comment]
Thanks for the request!

I don't think we'll want to do this as a calendar can do all of that better than we ever can with our limited resources.

NUSMods can already export your timetable to a calendar file for you, so you should be able to do everything you want in one of the many calendar apps out there.
