### ISSUE TITLE
Alert row above timetable is annoying.

### ISSUE THREAD

**Issue by evansb** [nusmodifications/nusmods#290]
I'm using ad blocker to remove them now. Isn't there any way to store the dismissal state in cookie or something so that they won't appear again?

**Comment by yangshun** [comment]
```
localStorage.hideAlerts = 'true'
```

**Comment by evansb** [comment]
Well that helps me and the rest of us who know how to use JS console, but what about the rest of us, and what about mobile browsers?

If you intend to make that row permanent to promote other nusmodifications project, I think it should be placed in a non obtrusive location, such as below the tip of the day.

Just a suggestion...
