### ISSUE TITLE
Exporting timetable in dark mode does not produce the visually correct headers

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#291]
This happens when the user tries to export in jpg/pdf.

![13898320_10210495474803522_2093950411_o](https://cloud.githubusercontent.com/assets/1315101/17463822/b7cf7c74-5d01-11e6-82a6-8e959aa8039f.jpg)

**Comment by ZhangYiJiang** [comment]
Fixed by https://github.com/nusmodifications/nusmods/pull/428
