### ISSUE TITLE
Vertical Mode tiles are not stacked vertically.

### ISSUE THREAD

**Issue by JingYenLoh** [nusmodifications/nusmods#2920]
### Describe the bug
Timetable in vertical mode does not stack the tiles vertically - they're stacked horizontally in a single row.

### To Reproduce

1. Go to https://nusmods.com/timetable/sem-1
2. Click on 'Vertical Mode'

### Expected behavior

The tiles should be stacked vertically.

### Screenshots
![image](https://user-images.githubusercontent.com/22059033/96536129-f567a600-12c5-11eb-8e6f-58dbcf9fc3cf.png)

### Desktop (please complete the following information):

* OS: Arch Linux
* Browser Firefox
* Version 82

### Smartphone (please complete the following information):

* Device: OnePlus Nord
* OS: Some version of OxygenOS
* Browser Firefox
* Version No idea what version it is anymore

### Additional context

How does the web work LOL

**Comment by taneliang** [comment]
Caused by #2547. I'll fix this

**Comment by taneliang** [comment]
The fix has been deployed. Thanks again @JingYenLoh!
