### ISSUE TITLE
Python should be in list of prerequisites

### ISSUE THREAD

**Issue by davis12529** [nusmodifications/nusmods#296]
Specifically, the python version used in conjunction with ansible.

Apparently there are reported compatibility issues with ansible 2.1 and python 3.x (https://github.com/ansible/ansible/issues/16013).

I am on python 3.4 and I had the same issue of "NameError: name 'urllib2' is not defined" when trying to  run ansible-playbook during vagrant provisioning.

**Comment by ngzhian** [comment]
PR appreciated :) maybe can update README.md to say that we want python 2.7?

**Comment by davis12529** [comment]
Sure thing, was not sure of the python version :)
