### ISSUE TITLE
Line indicator for day time

### ISSUE THREAD

**Issue by davis12529** [nusmodifications/nusmods#297]
This is inspired by most calendar apps. Instead of shaded area of an hour slot, we can have a vertically line in the slot instead that correspond to current time. This would be more precise at time-telling and it might be more obvious to users that we are indicating current day time.

The idea of implementation would be a div that is positioned absolute to avoid clashing with one or more module cells and allow the line to overlap on top. 

However, this means that the position and the height of the line would have to be dynamically determined through js/jquery, since the height of any day is determined by the most number of overlapping modules in a slot in order to 1. position the line in the correct day row 2. have the correct height. This have to be done in cases the height of the timetable would change e.g. detachment of module.

<img width="1036" alt="screen shot 2016-08-18 at 10 53 04 am" src="https://cloud.githubusercontent.com/assets/6311446/17763148/58be4a94-6549-11e6-8256-dec01da072f9.png">

**Comment by ngzhian** [comment]
This looks great! Colour can be a bit less glaring, and also need to pick a colour for dark mode :) Looking forward to a PR! :D
@mauris what do you think?

**Comment by mauris** [comment]
Sounds great. Initially wanted to follow what Google Calendar offers, but back in the #249 PR, I wasn't 100% sure how to modify the app via Marionette/Backbone (the PR was from very long ago). Definitely doable. Will support. :+1:

**Comment by davis12529** [comment]
Will refer to #249, thanks!

**Comment by xinan** [comment]
Closed by #249

**Comment by mauris** [comment]
@xinan, i think this is an improvement over the current one 😃  

@davis12529 ?

**Comment by yangshun** [comment]
@xinan this issue is not done 😂

**Comment by davis12529** [comment]
yeah it's not done yet. sorry, flooded with my AI mods 😅

**Comment by yangshun** [comment]
@davis12529 how's ur AI mod coming along?

**Comment by davis12529** [comment]
@yangshun Sorry for late reply, the semester was crazy. Now I am rushing for launch for my startup... 

This can be opened up for newcomers who are interested. If not, hopefully the next good time for me to look at this issue is post-launch and the product is stable

**Comment by yangshun** [comment]
@davis12529 It's ok, everyone has their commitments and priorities, it's understandable. All the best for your startup (:

**Comment by mauris** [comment]
I'll take a look at this again.

**Comment by yangshun** [comment]
We'll do without this in v3.
