### ISSUE TITLE
Vertical UI + upgrade front-end framework

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#300]
As part of the assignment, we won't have time to move the whole app onto React. We propose to only work on the timetable builder page, and if time allows, the individual module page and the module listing page.

The goal is to **render the entire timetable using React**.
1. Pass current state (probably currently in Backbone) into a root `<Timetable/>` React component
2. React renders timetable (horizontal or vertical doesn't matter right now)*
3. Pass callbacks into `<Timetable/>`, callbacks  fire when user makes changes to timetable and will update current state in Backbone

Additionally we could make use of Redux to help us manage state, in that case:
1. On app load, hydrate the store with data that is in Backbone (which it got from localstorage)
2. `<Timetable/>` will get state from store and render
3. User's changes to timetable fires actions, reducers make changes to the store
4. (Might not be needed) Somehow sync this new timetable state to Backbone (if other Backbone components need the exact state of timetable)

Also all these can be hidden behind a switch, so we preserve the current timetable layout, and then with a switch user can go to the vertical layout view.

(Side note on drag and drop: it doesn't work _that_ great on mobile, we might want to consider other UX for shifting time slots around, such as tapping. Check out [modify.sg](https://www.modify.sg/) for inspiration.)

*Whether we choose to render the Timetable vertically or horizontally as part of the upgrade is an orthogonal discussion. We can upgrade the framework and change the presentation at the same time or one after another.

References:
https://www.modify.sg/

Master task: #299

**Comment by li-kai** [comment]
Here's a very early prototype I made in [Codepen](http://codepen.io/likai/pen/NrNGyr).

As it only contains CSS, it'll give you guys a general idea of how it works. One big note is that I am not using tables here because you will end up trying to make the table into a list anyway.

**Comment by ngzhian** [comment]
This is deprecated in favour of v3!  Go v3!
