### ISSUE TITLE
`GlobalSearch` `option`s have poor readability in screen readers

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#3010]
See test cases in GlobalSearchContainer.test.tsx.

Context:

> Ooof, this is not ideal for screen readers. We should at the very least add a space here, and maybe using some flexbox shenanigans reverse the order of these in the DOM so that it reads more naturally

_Originally posted by @ZhangYiJiang in https://github.com/nusmodifications/nusmods/pull/3007#discussion_r533916966_

**Comment by bingcheng45** [comment]
@taneliang and @ZhangYiJiang I have made a pull request for this issue, do review and let me know if further changes are required.
