### ISSUE TITLE
Replace `ScrollToTop` with `useScrollToTop`

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#3034]
`useScrollToTop` was added in #3007 to replace the `ScrollToTop` component. It's currently still used in 2 class components (`ModulePageContent` and `SettingsContainer`), which need to be converted to functional components before we can delete `ScrollToTop`.

This issue exists so that we remember to remove `ScrollToTop` the codebase.

### Steps

1. Convert `ModulePageContent` and/or `SettingsContainer` to function components (both should be easy to convert).
1. Replace `<ScrollToTop />` with a `useScrollToTop()` call.
1. Delete `ScrollToTop` from the codebase.

**Comment by teikjun** [comment]
I can work on it! :D

**Comment by taneliang** [comment]
Sure, thank you! :D
