### ISSUE TITLE
Unable to export timetable to .ics file

### ISSUE THREAD

**Issue by brandoncjh** [nusmodifications/nusmods#3036]
### Describe the bug

Unable to export timetable to .ics file using the Download drop-down menu. On clicking the button, nothing happens.

### To Reproduce

1. Go to 'https://nusmods.com/timetable/sem-1'
2. Click on 'Download' button next to 'Share/Sync' button
3. Select option to export as iCalendar (.ics) file

![image](https://user-images.githubusercontent.com/54733974/101461236-8e857580-3975-11eb-9093-3ff3dbcb63c8.png)

### Expected behavior

A download of .ics file should be initiated, just as in the case of pdf.

![image](https://user-images.githubusercontent.com/54733974/101461305-a2c97280-3975-11eb-9bc3-a6b97ec3c7b7.png)

### Desktop:

* OS: Windows 10
* Browser: Chrome 
* Version: 86.0.4240.198 (Official Build) (64-bit)

### Additional Information

Same issue occurs when attempting to export in [Sem 2](https://nusmods.com/timetable/sem-2) as well.

**Comment by chrisgzf** [comment]
Thanks for the report! Triaging now.
