### ISSUE TITLE
Half hour lessons details are truncated

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#304]
So there are actually half hour lessons and we don't do a good job of displaying them. Good thing is that at least the full lesson details are displayed upon hover.

<img width="554" alt="screen shot 2016-09-10 at 4 42 47 pm" src="https://cloud.githubusercontent.com/assets/1315101/18409266/aa7873bc-7775-11e6-8b51-4f68f01e3a36.png">

Lesson payload:

```
ClassNo: "A1"
DayText: "Saturday"
EndTime: "1300"
LessonType: "Sectional Teaching"
StartTime: "1230"
Venue: "dRm2"
WeekText: "Every Week"
```

**Comment by li-kai** [comment]
An easy fix would be to use `word-break: break-all;` for the lesson code. It'll be ugly, but at least it'll work.

**Comment by yangshun** [comment]
Take note of this in v3.

**Comment by yangshun** [comment]
v3 does not truncate, it simply lets it overflow. I think it's ok to do that.
