### ISSUE TITLE
Kill unused/unpopular features

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#305]
Based on Google Analytics data, the following are not quite being used and we should kill them in v3:
- News - https://nusmods.com/news
- Bookmarks

**Comment by ngzhian** [comment]
-1 on killing bookmarks, seems like we have users -> #347

**Comment by yangshun** [comment]
Hmm Vishnu could be just testing it out, and it's only one user. But let's revisit this after gathering some user data for Sem 2.

**Comment by yangshun** [comment]
Has been done (:
