### ISSUE TITLE
Prerequisite Tree not showing

### ISSUE THREAD

**Issue by mauris** [nusmodifications/nusmods#306]
Thought I haven't seen the prereq tree for some time already. I went through a few modules that should have the prereq tree, but it's no longer showing. There are no errors in console, nor any non-200 http responses. 

![screenshot 2016-09-13 16 42 45](https://cloud.githubusercontent.com/assets/996939/18467180/7f04ff4e-79d1-11e6-84e9-5fe19a9f6732.png)

**Comment by yangshun** [comment]
Sadly something is up with the parsing script in https://github.com/nusmodifications/nusmods-api :( We are aware of it but haven't had time to dig into it.

**Comment by mauris** [comment]
@yangshun I see. didn't see an issue, so created one here. will take a quick look.

**Comment by yangshun** [comment]
@mauris haha thanks a lot! (:

**Comment by yangshun** [comment]
@mauris we found the cause. it was disabled on purpose by Beng because the task was taking up too much memory. Might have to find a more efficient solution or break the grunt task into stages.

**Comment by ngzhian** [comment]
It's showing now :)
