### ISSUE TITLE
Port developers page to v3

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#309]
_From @yangshun on September 11, 2016 16:38_

https://nusmods.com/contribute/developers

Should also integrate the content from https://nusmods.com/contribute into this page, minus the Reviewers part. 

_Copied from original issue: nusmodifications/nusmods-v3#11_

**Comment by zameschua** [comment]
Yo I'm interested! But is there a nice template from react-virtualized? Or it will be nicer to make our own template?

**Comment by yangshun** [comment]
What has this issue got to do with react-virtualized? 🤔

**Comment by zameschua** [comment]
I thought maybe can use some components from there haha. Ok I'll try working on this!

**Comment by yangshun** [comment]
When a page requires rendering of lists with large amount of items (in the magnitude of hundreds/thousands), and you don't want that amount of items to be present in the DOM as it takes a toll on performance, react-virtualized is used for only smartly only including the items that are present on screen in the DOM. In our case, the number of developers/contributors we have is still quite small and manageable enough that we don't require that library.
