### ISSUE TITLE
Bug: Export .ICS file

### ISSUE THREAD

**Issue by cjunxiang** [nusmodifications/nusmods#3091]
### Describe the bug

Export ics file not working as expected

### To Reproduce

1. Populate your timetable
2. Click on `Download`
![image](https://user-images.githubusercontent.com/26619858/102982024-d515cb00-4544-11eb-8fa1-c3c2b97a7bdf.png)

3. Click on `iCalendar file`
4. See error:
![image](https://user-images.githubusercontent.com/26619858/102981530-0c37ac80-4544-11eb-8f02-184ad8cb455a.png)

### Expected behavior

Expected to successfully generate .ics file and trigger download

### Desktop (please complete the following information):

- Linux Mint 20
- Browser: Brave and Microsoft Edge

### Smartphone (please complete the following information):

- Device: Xiaomi CC9
- OS: MIUI12
- Browser Chrome & Stock xiaomi browser

### Additional context
Suspected error @ package parsing nusmods type into ical type.

**Comment by devrathc** [comment]
hred url is missing for the ics option....can someone fix it?
![image](https://user-images.githubusercontent.com/4910452/103081469-f644ed00-4612-11eb-9337-c57138b1c752.png)

**Comment by cjunxiang** [comment]
> href url is missing for the ics option....can someone fix it?
> ![image](https://user-images.githubusercontent.com/4910452/103081469-f644ed00-4612-11eb-9337-c57138b1c752.png)

hmm weird. works on local master br. Possibly fixed by https://github.com/nusmodifications/nusmods/pull/3037 but not yet pushed to prod.

**Comment by taneliang** [comment]
You're right, #3037 was merged but wasn't deployed 🤦 I'm deploying now, and so the fix should be live within roughly 30 min. Sorry for the trouble, and thanks for the detailed report!
