### ISSUE TITLE
&amp; in module descriptions

### ISSUE THREAD

**Issue by dlqs** [nusmodifications/nusmods#3100]
### Describe the bug
Some module descriptions render `&` as `&amp;` e.g. https://nusmods.com/modules/PC1222/fundamentals-of-physics-ii

![image](https://user-images.githubusercontent.com/31354724/103362917-d327ab00-4af4-11eb-9da3-bd23467345d0.png)

### To Reproduce
I used `jq` to count modules with `&amp;` in the description:
```
curl -X GET "https://api.nusmods.com/v2/2020-2021/moduleInfo.json" | jq '[ .[] | select(.description|test("&amp;")) ]' | jq length 

18
```
Remove `| jq length` to see the actual modules

### Expected behavior

& appears as &

### Desktop (please complete the following information):
Manjaro, Firefox 84

### Additional context
I took a look at `/scrapers` and I don't think this is caused by any code there. Perhaps the NUS API is returning these `&amp;`s? If it's possible, I'm interested in fixing this. Perhaps this could be as simple as an additional `.replace("&amp;", "&")`?

**Comment by ZhangYiJiang** [comment]
Interesting. Yes, we can double check on our end because we can access the raw API data but I expect nonsense like this from NUS. We should probably also unescape other entities while we're at it

**Comment by dlqs** [comment]
I tried to find the other HTML entities with a regex:
```
curl -X GET "https://api.nusmods.com/v2/2020-2021/moduleInfo.json" | jq ' .[] | .description | match("(&(?:[a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});)"; "ig") | .captures[0].string ' | sort | uniq -c 

      1 "&#224;"
      1 "&#246;"
     30 "&amp;"
    105 "&quot;"
```

So we just need to handle `&amp;` and `&quot;` (the first two are à and ö respectively).

We could either
 - do 4 `.replace`s for each entity and hope NUS doesn't send more our way
 - use [lodash's unescape](https://lodash.com/docs/4.17.15#unescape) which handles `&amp;` and `&quot;`, and `.replace` the other 2
 - use a full fledged package like [he](https://github.com/mathiasbynens/he#hedecodehtml-options)

thoughts?

**Comment by taneliang** [comment]
I’ll double check that NUS APIs are returning those escaped strings, but I’m pretty sure it’s coming from them.

If so, I vote for a complete solution like he since that’ll solve this once and for all 😄

We’ll probably want to implement this on the scraper, so if you’re adding deps you may want to hold off making your PR until #3125 is merged to avoid conflicts.

You won’t have access to the NUS APIs, but it should still be possible to implement this by writing tests for it. We can run this against the NUS APIs for you.

**Comment by taneliang** [comment]
Yep, looks like the `&amp;` etc came from NUS.

![image](https://user-images.githubusercontent.com/12784593/103472980-8c74d200-4dce-11eb-93dd-702fd281799a.png)
