### ISSUE TITLE
Port venue information page to v3

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#315]
_From @yangshun on September 11, 2016 15:4_

https://nusmods.com/venues/COM1-0114
- [ ] Search venue
- [ ] Venue timetable section
  - Should try to reuse `<Timetable>` component for rendering the venue timetable.
- [ ] Venue information section

_Copied from original issue: nusmodifications/nusmods-v3#4_

**Comment by zameschua** [comment]
I'm interested!

**Comment by taneliang** [comment]
Implemented in #498
