### ISSUE TITLE
Make NUSMods into a Progressive Web App

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#319]
Thanks @ngzhian for sharing this: https://infrequently.org/2016/09/what-exactly-makes-something-a-progressive-web-app/

Some other articles: https://medium.com/@owencm/designing-great-uis-for-progressive-web-apps-dd38c1d20f7#.h9vyvzq9n

**Comment by ngzhian** [comment]
https://github.com/GoogleChrome/lighthouse will be helpful too :)

**Comment by li-kai** [comment]
We're scroing 100% on pwa metric now. We pwa now.
