### ISSUE TITLE
Prerequisite tree right-to-left progression is confusing

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#3202]
### Is your feature request related to a problem? Please describe.

Some module pages ([example](https://nusmods.com/modules/YCC2137/scientific-inquiry-2%23prerequisites)) have prerequisite trees, where a given modules' dependents and prerequisites are displayed on the module's left and right respectively. However, this is counter-intuitive to people who expect a left to right progression.

![30FD5527-AFF8-46D4-98BD-D78081C8796E](https://user-images.githubusercontent.com/12784593/105841738-1439af00-6010-11eb-8278-460ad16c7ca6.jpeg)

### Describe the solution you'd like

We should probably flip the tree to show dependents on the right.

### Describe alternatives you've considered

@li-kai any idea why we did it this way?

**Comment by li-kai** [comment]
I think the original thinking is people want to know the dependencies rather than the dependents. You're right, it's a little confusing to display it this way. Top to bottom is more intuitive but it's hard to do in css.

**Comment by sciffany** [comment]
I'd like to take on this issue please!

**Comment by sciffany** [comment]
> I'd like to take on this issue please!

This is harder than I thought

**Comment by alvynben** [comment]
hey @schalkneethling do you mind if I take this up? I think I've created a working version with reverse ordering.

**Comment by alvynben** [comment]
I've created a pull request for this issue above.

**Comment by chrisgzf** [comment]
Hey @alvynben, thanks for the contribution! However since @sciffany already has a working implementation in #3263, we'll review her version first. (I think there was a miscomm somewhere above.) If you'd like to, you can review her PR too! I'm going to close your PR first to avoid confusion (we can reopen it again if the need arises). Sorry about that!

**Comment by zehata** [comment]
I have taken this issue and opened a PR, but I would favour closing this issue and creating a new one for the same but with an option in the settings that allow users to choose their preference
