### ISSUE TITLE
Timetable scrolling stops after redirect

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#323]
Steps to reproduce on iPhone Safari:
1. go to [v3.nusmods.com](v3.nusmods.com)
2. scroll the responsive timetable (yay)
3. go to the footer, and click on any of the links
4. go back to v3 and try scrolling the timetable again, it doesn't work

I don't think it's css.

**Comment by yangshun** [comment]
Ok I'm able to reproduce this on iOS simulator. Sigh looks like an obscure bug.

**Comment by yangshun** [comment]
@li-kai Can you see if this still happens on the new implementation 😂

**Comment by li-kai** [comment]
@yangshun Yes it does. When you press on a module, it becomes scrollable again though. Probably some styles not getting re-init when going back.

**Comment by li-kai** [comment]
Closed due to #444
