### ISSUE TITLE
Update ModReg Data for AY21/22 S1

### ISSUE THREAD

**Issue by chrisgzf** [nusmodifications/nusmods#3292]
Better late than never right?

Note: This is slightly time sensitive (i.e. if we do it too late, there is no point). Let's try to complete it before Select Tutorials / Labs Round 0.

# Steps

1. Follow https://github.com/nusmodifications/nusmods/pull/2764
2. Test it make sure it works by setting your system time
3. Update [MAINTENANCE.md](https://github.com/nusmodifications/nusmods/blob/master/MAINTENANCE.md) to include this step under "Every Semester"

If anybody wants to take this up, drop a comment below!

**Comment by bnjmnt4n** [comment]
I'd like to take this up.

**Comment by chrisgzf** [comment]
Sure @bnjmnt4n! Let me know if you face any problems!

**Comment by bnjmnt4n** [comment]
Opened a PR at #3293.
