### ISSUE TITLE
Include a check to see what aspect of course curriculum is fulfilled based on modules

### ISSUE THREAD

**Issue by kieron560** [nusmodifications/nusmods#3298]
I think this is gonna be a really huge feature with a lot of work to do, but it definitely would be nice for students to somehow input their course (i.e computer science), and then this is reflected perhaps at the bottom, where the modules needed to graduate would be checked off if it were reflected in the ModPlanner.

For example, if the all the foundational modules were in the ModPlanner, then the foundational requirement would be ticked accordingly (or the modules completed would be ticked accordingly). Or if I as a CS Major completed my focus area modules (lets say I completed my 3 primary focus area modules), then this would be reflected too by showing what focus areas I have completed, or what electives do I still need to take etc.

But I understand this would be really tough due to the scale to include every single course structure since there will be so many different variations of curriculum out there. But definitely would be a major leap for NUSMods in my opinion!!

**Comment by chrisgzf** [comment]
Duplicate of #359, gonna close this for now.

p.s. I know it's difficult for people to see old issues like #359, but hopefully when I clean up the issues more, these older threads will start to surface again.
