### ISSUE TITLE
Colorpicker for timetable modules

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#331]
As a start, we can shamelessly copy modify.sg's module colorpicker. The newly selected color should be persisted in the Redux store, which has the theme persisted across sessions via `localStorage`.

Clarification: The user should only be allowed to pick one of the 8 colors in their selected theme.

<img width="196" alt="screen shot 2016-09-28 at 1 23 24 pm" src="https://cloud.githubusercontent.com/assets/1315101/18901583/c8c6fab6-857e-11e6-9b5c-732f04723d5e.png">

**Comment by li-kai** [comment]
As a note, [react color](https://casesandberg.github.io/react-color/) has a pretty awesome series of color pickers. Their circle implementation is a little better UX wise as compared to mine.

**Comment by yangshun** [comment]
Wew nice find. Sadly we can't allow free colors (we only allow users to pick one out of the 8) in a given theme. Given that constraint, probably there isn't much value in using it (we can easily write our own).

I like the "Block" and "Twitter" one in particular.

<img width="199" alt="screen shot 2016-09-28 at 1 55 10 pm" src="https://cloud.githubusercontent.com/assets/1315101/18902108/310b40ba-8583-11e6-96fd-cf800444f45c.png">
<img width="108" alt="screen shot 2016-09-28 at 1 54 59 pm" src="https://cloud.githubusercontent.com/assets/1315101/18902109/31103020-8583-11e6-8310-ebbdbae5c105.png">

**Comment by li-kai** [comment]
The twitter one looks good. We can probably adapt some UX tips by highlighting the color currently chosen too.

**Comment by yangshun** [comment]
Fixed via #345
