### ISSUE TITLE
CHS Mods are displayed as "CollegeofHumanitiesandSciences"

### ISSUE THREAD

**Issue by chrisgzf** [nusmodifications/nusmods#3321]
CHS Mods are displayed as "CollegeofHumanitiesandSciences"
![image](https://user-images.githubusercontent.com/4933577/124743797-a8f5f080-df50-11eb-9054-e20b88480f3f.png)
![image](https://user-images.githubusercontent.com/4933577/124743875-c1660b00-df50-11eb-982a-5956b0d0e4a4.png)

Possibly scraper related.

### To Reproduce

See https://nusmods.com/modules/HSH1000/the-human-condition

**Comment by chrisgzf** [comment]
Well this is kinda annoying (from NUS API)

![image](https://user-images.githubusercontent.com/4933577/124825883-c190f580-dfa6-11eb-8c5c-b05218e911b9.png)

**Comment by ZhangYiJiang** [comment]
We already have a bit of code that helps clean up these names - https://github.com/nusmodifications/nusmods/blob/13612ffa0561c4765e4f2110f28707a3d8348ee8/scrapers/nus-v2/src/tasks/GetFacultyDepartment.ts#L32. It's awkward and we should definitely report this to NUS, but detecting this with a bit of heuristic is not too hard I think. The `of` is annoying though, so we can't just do this naively. We also have a list of stop words for titleize which we can re-use for this purpose https://github.com/nusmodifications/nusmods/blob/master/scrapers/nus-v2/src/utils/data.ts#L29

**Comment by RussellDash332** [comment]
It seems to be fixed already
![image](https://user-images.githubusercontent.com/63991775/127779657-d130086f-c072-4e2a-958c-43e93d270356.png)

**Comment by chrisgzf** [comment]
Yeap thanks for pointing it out @RussellDash332! We've contacted RO and they managed to change the description!
