### ISSUE TITLE
Planner could use archived module data to return links, instead of saying 'No data on this module'. 

### ISSUE THREAD

**Issue by sharadhr** [nusmodifications/nusmods#3325]
Modules inserted in the planner for past years could take data directly from said year's archive, and return a link to the module information. As a stretch goal, populate the drop-down boxes too as the user types.

Hence, for instance, a 4th-year student in AY21/22 could fill in the modules they took in their first year (AY18/19), and the links for the module would automatically link to the archived data for that module, for that year. This is especially relevant now, since _dozens_ of past modules were deprecated for the upcoming year, due to FoS and FASS combining into CHS.

Sounds reasonable enough; I might get to it when I can.

**Comment by chrisgzf** [comment]
Thanks @sharadhr! Do feel free to leave a comment here / in the NUSMods telegram chat if you need any help, etc.
