### ISSUE TITLE
Support hiding of specific classes rather than entire modules

### ISSUE THREAD

**Issue by over-fitted** [nusmodifications/nusmods#3326]
### Problem

As a Teaching Assistant I would only be required to teach a single tutorial slot for my module. As such displaying the lecture slots of the module would result in unnecessary clutter. The current solution is to hide the entire module/not include it in my timetable but I would like to have the specific tutorial remain visible.

Similar issue occurs where a module does not have a live lecture in certain slots (i.e. recordings only like MA1101R first lectures) where displaying the lecture slot is unnecessary

### Solution

 I see two possible solutions:

a) give the option to hide slots by type. For example hide the 2 hour lecture slot for this mod, or the first lecture of the week, or all lectures etc.

b) allow user to select their slots but then hide their chosen slots on a slot-by-slot basis

**Comment by chrisgzf** [comment]
Thanks for the report @over-fitted! Closing this for now. Refer to #3334 instead.
