### ISSUE TITLE
Planner doesn't work with GESS modules

### ISSUE THREAD

**Issue by Berted** [nusmodifications/nusmods#3328]
### Bug Description

GESS-prefixed modules cannot be placed into the planner.

### To Reproduce

1. Go to 'Module Planner'
2. Click on 'Add Modules'
3. Type in any GESS-prefixed module (i.e. GESS1029)
4. Module doesn't appear.

### Expected behavior

GESS-prefixed module appears.

### Desktop:

- OS: Windows
- Chrome Browser
- Version 91.0.4472.124

**Comment by andlimey** [comment]
Anyone else working on this? I don't mind investigating the issue.
