### ISSUE TITLE
NUSMods Beta, Module planner not displaying year 2 - year 4

### ISSUE THREAD

**Issue by Magmanat** [nusmodifications/nusmods#3351]
### Describe the bug

Used the beta program to try to plan mods for year 2-4 of study but only year 1 is shown.

### To Reproduce

1. signup for NUSMods Beta
2. Click Planner on the sidebar
3. Start planning your mods, but year 2-4 is not shown, hence not able to drag mods there to plan
4. 
### Expected behavior

Expected to have years 2-4 shown with sems 3-8 there so that mods could be planned ahead of time
![image](https://user-images.githubusercontent.com/74498975/132542855-7e89b653-2c78-4b5c-be62-916f3c0b81b6.png)

### Desktop (please complete the following information):

- OS: Windows 10
- Browser Opera GX ( Tried with Chrome and also same issue observed)
- Version Latest as of date of writing

### Smartphone (please complete the following information):

no smartphone

**Comment by bnjmnt4n** [comment]
Hey @Magmanat you can click on the settings button at the top right and choose your graduating year to enable display of the remaining years. Not sure why there's isn't a sensible default for this - probably unintentional?

**Comment by Magmanat** [comment]
Thanks for telling me about this! 
Yes this is probably unintentional, perhaps they could update it such that it provides a default generic which assumes a 4 year study period.
