### ISSUE TITLE
Allow removal of yellow warnings in Planner

### ISSUE THREAD

**Issue by rish-16** [nusmodifications/nusmods#3369]
### Is your feature request related to a problem? Please describe.

The UI gets very cluttered when I add a module to the Planner but haven't filled up the prereq mods from previous AYs. There's this yellow warning box that pops up below the module title/detail. It'd be nice to make it collapsible.

### Describe the solution you'd like

A cross ("X") at the top of the yellow warning box would be nice. Once clicked, it means I acknowledge that there will be some issue/problem (eg: have to take prereq mods). It can either remain yellow but collapsed (only mod title/MCs seen) **OR** go back to being green. That way, I can see all my mods at a glance so I can share it with friends or plan the future AYs better. 

![image](https://user-images.githubusercontent.com/20137995/145148761-e3b23a4f-a673-4ca0-95d4-46ac0638014c.png)

### Describe alternatives you've considered

There's no way to remove it unless I put in all the prereq mods in the previous AYs on the Planner. 

Thank you for your consideration!!!

**Comment by seanlowjk** [comment]
@rish-16 @chrisgzf I was trying it out and it seems that this does not take much engineering effort. 

https://user-images.githubusercontent.com/42912708/147061651-2d1924f1-29fc-44b9-8cfc-f06075258ff0.mp4

I have done a simple mock-up below! Do feel free to check it out. 

@chrisgzf given that there are other kinds of conflicts, such as semester conflicts and exam conflicts, would it be ok to add toggles as well? >< psps

**Comment by rish-16** [comment]
Hey, thanks Sean. This is exactly what I'm looking for!

**Comment by chrisgzf** [comment]
@seanlowjk

> given that there are other kinds of conflicts, such as semester conflicts and exam conflicts, would it be ok to add toggles as well?

IMO not necessary. The other conflicts are quite reliably detected and would provide useful feedback to the user that has very low risk of being inaccurate / disruptive. I think your current implementation is fine! 😄
