### ISSUE TITLE
Examination dates for AY21/22 Semester 2

### ISSUE THREAD

**Issue by yuyitan** [nusmodifications/nusmods#3372]
### Describe the bug

Examination dates for AY21/22 Semester 2 is different from what is stated in the NUS calendar.

### To Reproduce

1. Go to 'Timetable'
2. Click on 'Exam Calendar'
3. See dates error

### Expected behavior

Examination period should be from 25 April (Monday) to 7 May 2022 (Saturday).

### Screenshots

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/77650951/145745476-fa0a907c-8f4b-42f8-9e7b-039f1c3e62d0.png">
<img width="482" alt="image" src="https://user-images.githubusercontent.com/77650951/145745490-78b031fb-6466-4b22-86d0-dff6de1249ee.png">

### Desktop (please complete the following information):

- OS: Windows 10
- Browser: Chrome
- Version: Version 96.0.4664.93

**Comment by chrisgzf** [comment]
Thanks for the report! But I'm afraid I'm not understanding the issue correctly here. In the screenshot above, it does say that Examination weeks are from 23 Apr to 7 May. You also have a ST2334 exam on 23 Apr 9am, which fits the data shown in the PDF. Do you mind pointing out what the issue might be?

**Comment by yuyitan** [comment]
My bad, I think I misinterpreted the timetable as I thought the examination would only occur during Exam Week 1 instead of the previous Saturday. Please close my issue, thanks!
