### ISSUE TITLE
Inconsistency in the shape of the timetable block

### ISSUE THREAD

**Issue by ireneliee** [nusmodifications/nusmods#3398]
### Describe the bug

Not sure if this is intended but there is inconsistency in the shape of timetable block. Some of the blocks have rounded corners and some of them have sharp corners. 

### To Reproduce

1. Just add multiple random module blocks
2. They would have different corners...

### Expected behavior

For them to have consistent shape? Either rounded or sharp corner is fine!

### Screenshots

<img width="344" alt="Screenshot 2022-06-29 085421" src="https://user-images.githubusercontent.com/77621546/176348760-26c2e548-f328-47c8-b17f-2ff872722ceb.png">

### Desktop:

- OS: Windows
- Browser Chrome
(Use 2 different computers and I can easily reproduce the same effect)

**Comment by yqiyao** [comment]
Not a bug. The rounded corner blocks are events with multiple time slots available, the square ones are not.

**Comment by chrisgzf** [comment]
Hey @ireneliee, like what the commenter above has mentioned, the role of the rounded corners is to indicate to users that the timetable slot is clickable (i.e. there are multiple timeslots).
