### ISSUE TITLE
bug: able to add negative modular credits to custom module

### ISSUE THREAD

**Issue by tohhengxing** [nusmodifications/nusmods#3402]
### Describe the bug

You can add negative MC when creating a custom module in module planner

### To Reproduce

1. go to module planner
2. add a custom mod
3. click add data
4. input a negative number

### Expected behavior

should not allow negative number to be added

### Screenshots

https://user-images.githubusercontent.com/102740235/180600693-18652abe-4674-446a-a24a-6ab29eb05820.mp4

**Comment by wr1159** [comment]
I believe this issue has been resolved and can be closed

**Comment by kokrui** [comment]
Thanks for the catch @wr1159!
