### ISSUE TITLE
NUSMODs for TAs

### ISSUE THREAD

**Issue by FeanTMX** [nusmodifications/nusmods#3404]
### Is your feature request related to a problem? Please describe.

A clear and concise description of what the problem is. Eg. I'm always frustrated when [...]
Hi, as an undergraduate TA, I would like to suggest that nusmods can have a functionality to add tutorials/ labs only, since lectures are generally irrelevant to TAs. If possible, I would like to see a function which introduces modularity, so that if I can add one or more tutorial slots that I am tutoring, or only include labs and not tutorials if I am tutoring for labs (vice versa).  I will really be very very thankful if there is such a functionality.

**Comment by HollaG** [comment]
Hacky workaround for now:
1) Export the timetable as a link
2) Remove the specific lecture slot from the link
3) Re-import and save the timetable

for e.g.:
https://nusmods.com/timetable/sem-1/share?CS1101S=TUT:09F,REC:11B,LEC:1
becomes
https://nusmods.com/timetable/sem-1/share?CS1101S=TUT:09F,REC:11B

**Comment by FredericChow00** [comment]
Can I ask how do you remove the specific lecture slot from the link?
