### ISSUE TITLE
Update the bus routes

### ISSUE THREAD

**Issue by yimqiy** [nusmodifications/nusmods#3407]
### Is your feature request related to a problem? Please describe.

Update the new bus routes (E, K) since 2021.

**Comment by zwliew** [comment]
This has been fixed in https://github.com/nusmodifications/nusmods/commit/a83078c79fb79c3cc7eabde386faae5182cd0a31. Soon, we plan to merge an even more comprehensive bus navigation feature (https://github.com/nusmodifications/nusmods/pull/3712)!
