### ISSUE TITLE
Download links for timetable is not working

### ISSUE THREAD

**Issue by sikai00** [nusmodifications/nusmods#3415]
### Describe the bug
Upon clicking the download link for a timetable, an error page appears.
<img width="276" alt="image" src="https://user-images.githubusercontent.com/63795894/195529550-dad31401-1340-46a5-9c70-7b2c3a8ec202.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/63795894/195530136-a5c147ab-3bf4-4528-bdd9-8d322d6fa81a.png">

### To Reproduce

1. Go to 'timetable'
2. Click on 'Download', then any of the options e.g., 'Image'

### Expected behavior

The image is downloaded to my local folder.

### Screenshots

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/63795894/195530136-a5c147ab-3bf4-4528-bdd9-8d322d6fa81a.png">

### Desktop (please complete the following information):

- OS: MacOS 12.6
- Browser Chrome
- Version 106.0.5249.119 (Official Build) (arm64)

**Comment by chrisgzf** [comment]
Fixed in https://github.com/nusmodifications/nusmods/pull/3417. It should work now, thanks for the report!

(Will close this issue after the PR is merged.)
