### ISSUE TITLE
Hidden courses on Timetable builder are exported and visible when imported

### ISSUE THREAD

**Issue by HollaG** [nusmodifications/nusmods#3444]
### Is your feature request related to a problem? Please describe.

Hidden courses on NUSMods Timetables are shared even when they're hidden. When the shared link is opened, the hidden courses become visible, which may confuse people when they share their timetables with others -- the timetable will look fuller than it actually is

### Describe the solution you'd like
Hidden mods should not be visible when imported

### Describe alternatives you've considered

There are two solutions I thought of:
1) don't include hidden mods in the share URL generation
2) include the hidden mods in the share URL generation, but add a new query parameter which will be an array of the course codes that are hidden

### Additional context

Reproducing - hide a course on timetable builder, export it and import in Incognito - the hidden course is now visible

I'm able to implement the fix for this, depending on which solution is better, I'm not sure at the moment!

**Comment by zwliew** [comment]
I think the 2nd solution would be a great addition :D

**Comment by HollaG** [comment]
Alright, I'll attempt to do it now

**Comment by kokrui** [comment]
Fixed in #3445
