### ISSUE TITLE
Bus timings do not load

### ISSUE THREAD

**Issue by wilsonwid** [nusmodifications/nusmods#3448]
### Describe the bug

Bus timings at available bus stops are not displayed. Furthermore, there seems to be outdated bus services as brought up by #3407.

### To Reproduce

1. Go to [nusmods.com/venues/](https://nusmods.com/venues/)
2. Select any venue close to a bus stop, and select said bus stop.

### Expected behavior

The popout should display timings for currently available bus routes.

### Screenshots

<img width="1728" alt="image" src="https://github.com/nusmodifications/nusmods/assets/87320062/70f02e35-b971-4b55-9278-047709cb01ca">

### Desktop (please complete the following information):

- OS: MacOS
- Browser: Chrome

### Additional context

There are also outdated bus stops and new services (service E and K come to mind) are not displayed.

**Comment by zwliew** [comment]
Cause: The old NextBus API that we were using was taken down and replaced by nnextbus.nus.edu.sg.

The new API requires auth.

**Comment by jloh02** [comment]
has anyone sniffed out the packets and see how we can replicate this from nextbus app using nnextbus.nus.edu.sg api?

**Comment by jloh02** [comment]
Found an open endpoint that's used by `sets.netlify.app`. There are other endpoints to get the timings for each bus stop. Not sure if we want to delve into using this though

https://urchin-app-jluem.ondigitalocean.app/api/bustimings/allstops/National%20University%20of%20Singapore

**Comment by SuibianP** [comment]
https://github.com/SuibianP/nus-nextbus-new-api

**Comment by zwliew** [comment]
This has been fixed in a83078c79fb79c3cc7eabde386faae5182cd0a31. Soon, we plan to merge an even more comprehensive bus navigation feature in PR #3712!
