### ISSUE TITLE
Possible issue in exam clash checking function?

### ISSUE THREAD

**Issue by weiseng18** [nusmodifications/nusmods#3449]
### Describe the bug

CM2112 has a 120 minute exam according to the module list data from [here](https://api.nusmods.com/v2/2023-2024/modules/CM2112.json). However, the timetable does not seem to detect an exam clash.

![image](https://github.com/nusmodifications/nusmods/assets/20338724/95c7d3e1-0b94-4e13-b3d0-c4519c2456c3)

From my brief understanding, CM2112 is a core module for Chemistry majors, and HSI2001 can be used to fulfil Scientific Inquiry 2, so hopefully this is a reasonable combination.

### To Reproduce

Add CM2112 and HSI2001 to the timetable in Semester 2.

### Expected behavior

Exam clash warning should appear

### Additional context

From briefly looking through the code, it seems that this code is responsible for detecting exam clashes.

```js
// Find all exam clashes between modules in semester
// Returns object associating exam dates with the modules clashing on those dates
export function findExamClashes(modules: Module[], semester: Semester): ExamClashes {
  const groupedModules = groupBy(modules, (module) =>
    get(getModuleSemesterData(module, semester), 'examDate'),
  );
  delete groupedModules.undefined; // Remove modules without exams
  return omitBy(groupedModules, (mods) => mods.length === 1); // Remove non-clashing mods
}
```

From what I understand, this function considers a clash to be two exams starting at the same time. This is usually a reasonable assumption assuming that exams start at a fixed time (9am/1pm/5pm or 9am/2.30pm), but it appears that there may be counterexamples, so it is important to check the exam duration as well.

Another test case: SH5110 (5pm) and FE5222 (7pm) in Sem 1 but SH5110 has a 2.5 hour exam.

**Comment by weiseng18** [comment]
Implementation idea:

Note that `examDate` is a string like this: `2023-09-23T08:00:00.000Z` and `examDuration` is a number like this: `120`

1. Convert `examDate` to GMT+8 (to make it easier to detect clash)
2. Perform `groupBy` on a key containing `examDate` and `examDuration`, e.g. `` `${examDate}_${examDuration}` ``
3. For each key like `${date}T${time}Z_${duration}`, extract `date`, `time`, `duration`.
4. For each date
    - For every pair of time and duration, form the time interval
    - We can check for interval overlaps using `.getTime()` and inequalities
    - The reason why `examDate` is changed to GMT+8 is so that we can do a $O(n^2)$ brute force check that is simple to understand, just on the intervals for a specific date
5. If any overlap is found, then all the relevant modules in the `groupBy` have an exam clash.

This assumes that any exam clash can only involve two exams that happen on the same day, which is probably a sane assumption.

**Comment by zwliew** [comment]
> Hi, if no one else is taking this issue, I would like to attempt it? I'm currently working on a similar implementation of the algorithm above, i.e. checking clashes within groups of examdates with the same date, by comparing time intervals of the exams.

Go ahead!

**Comment by Irminrics** [comment]
I was planning on fixing this issue but seems like EssWhyy has fixed the issue. I'm wondering if there is any issue with the fix since it has not been approved or reviewed since a month ago?

**Comment by kokrui** [comment]
@weiseng18 thanks for the issue! after some reworking we've landed https://github.com/nusmodifications/nusmods/pull/3560 and it's now in production instance
