### ISSUE TITLE
Show total number of active units in Timetable

### ISSUE THREAD

**Issue by HollaG** [nusmodifications/nusmods#3459]
### Is your feature request related to a problem? Please describe.
When planning timetables, it might be helpful to see the total number of active units, instead of just the total number.

![image](https://github.com/nusmodifications/nusmods/assets/31369072/68bb8b9f-db8a-4ba5-8387-17eab84342ed)

For example, only 12 Units are active here.

### Describe the solution you'd like

Add an extra line above 'Total Units: 28 Units' to say 'Active Units: 12 Units'

### Describe alternatives you've considered

Possible to add as a bracket e.g. 'Total Units: 28 Units (12 active)' ?

### Additional context

Saw feature request from this [Reddit thread](https://www.reddit.com/r/nus/comments/14q5o1r/comment/jqlpxpf/?utm_source=share&utm_medium=web2x&context=3)

**Comment by zwliew** [comment]
Resolved in #3460
