### ISSUE TITLE
Open mods and venues in new tab in global search

### ISSUE THREAD

**Issue by jloh02** [nusmodifications/nusmods#3466]
### Is your feature request related to a problem? Please describe.

As a user, I am able to click on mods (for e.g. in timetable) to navigate to the module's page. I can also open it in a new tab. However, when using global search, opening modules/venues in new tab is not possible.

### Describe the solution you'd like

- Switch from using React history router with downshift's `onChange` listener to react-dom `Link`
- This allows pushing of new routes without reloading the entire page
- Remove the callback prop from `GlobalSearchContainer` to `GlobalSearch` as `modulePage` and `venuePage` can be referred to directly in `Link`'s `to` property

### Describe alternatives you've considered

- Switch to `<a>` tag (Not ideal as reloads entire dom)

### Additional context
NIL

**Comment by zwliew** [comment]
Resolved in #3468
