### ISSUE TITLE
Prettify unwieldy phrasing in prereq tree

### ISSUE THREAD

**Issue by chuabingquan** [nusmodifications/nusmods#3469]
### Is your feature request related to a problem? Please describe.

The current prereq tree looks unwieldy in cases where courses are prefixed with `minimally` and `course starting with`.

<img width="612" alt="Screenshot 2023-07-28 at 5 56 40 PM" src="https://github.com/nusmodifications/nusmods/assets/12640352/944fb017-326d-426c-8323-b7baa2f77059">

<img width="620" alt="Screenshot 2023-07-28 at 5 56 20 PM" src="https://github.com/nusmodifications/nusmods/assets/12640352/4aa052a2-7f98-4383-924b-cac5dd976e52">

### Describe the solution you'd like

We could modify the CSS of the prereq tree item to make `minimally` and `course starting with` appear as follows:

<img width="547" alt="Screenshot 2023-07-28 at 6 01 10 PM" src="https://github.com/nusmodifications/nusmods/assets/12640352/4139f743-6781-42ae-aaf2-3737369f1e9f">

### Describe alternatives you've considered

I've discussed two alternatives with @chrisgzf, namely:
1. Appending "X"s to the course code of prereq tree items that begins with `course starting with` (i.e. `MA11X`, `MA11XX`)
2. Same as the first, but with "*"s instead of "X"s (i.e. `MA11*`, `MA11**`)

In general, both solutions aren't optimal as they introduce ambiguity. For the first option, there exist course codes which ends with an "X". As for the second option, it's unclear if "*" would be correctly interpreted to mean what we intend. This leaves us with the proposed solution, which seeks to avoid these ambiguities by retaining the prefixes for the clarity they provide, while making them aesthetically more compact for ease of readability.

**Comment by zwliew** [comment]
I agree that the prereq tree needs to be improved. Another issue is that the hoverable and clickable button area only exists for the module code (i.e. "CS2030S"), instead of the entire colored region (i.e. "CS2030S (minimally A-)".

Are you working on this? If not, I plan to fix it.

**Comment by chuabingquan** [comment]
Please, go ahead!

**Comment by chuabingquan** [comment]
> I agree that the prereq tree needs to be improved. Another issue is that the hoverable and clickable button area only exists for the module code (i.e. "CS2030S") instead of the entire colored region (i.e. "CS2030S (minimally A-)").
> 
> Are you working on this? I'd like to take this if you aren't.

Please, go ahead!
