### ISSUE TITLE
Fix bookmarks

### ISSUE THREAD

**Issue by burnflare** [nusmodifications/nusmods#347]
I just tried bookmarking modules on both Safari and Chrome but the module doesn't actually get bookmarked.

<img width="141" alt="screen shot 2016-11-14 at 4 05 16 pm" src="https://cloud.githubusercontent.com/assets/104150/20257375/29193558-aa84-11e6-9a2b-030ee4f67f57.png">
<img width="189" alt="screen shot 2016-11-14 at 4 05 21 pm" src="https://cloud.githubusercontent.com/assets/104150/20257377/29e9d5fa-aa84-11e6-9b50-760f192a658d.png">

**Comment by ngzhian** [comment]
fixed!
