### ISSUE TITLE
Reset Timetable

### ISSUE THREAD

**Issue by joeng03** [nusmodifications/nusmods#3471]
### Is your feature request related to a problem? Please describe.

Users might want to reset their timetable to the empty state.

### Describe the solution you'd like

A "Reset Timetable" button with a confirmation dialog, placed beside the "Download" button

### Describe alternatives you've considered

Currently, the user could either 

i. Delete the modules one by one manually to reset the timetable to the empty state. (Cumbersome)
ii. Clear the cache (This may clear other settings/data as well)

**Comment by EssWhyy** [comment]
Hi, I've linked a PR for this feature request, please help to review and feedback, thank you.
