### ISSUE TITLE
Import timetable "undo" does not work

### ISSUE THREAD

**Issue by leslieyip02** [nusmodifications/nusmods#3475]
### Describe the bug

After importing a timetable shared via URL, the "UNDO" button in the notifcation does not undo the import.

### To Reproduce

1. Go to the "Timetable" tab and click the share "Share/Sync" button
2. Copy the URL, and open it in a different window
3. Click "Import"
4. Wait for the notification and click "UNDO"

### Expected behavior

The undo button should reset the timetable to the previously saved state.

### Video

https://github.com/nusmodifications/nusmods/assets/90888680/ddcc6e13-f8c4-4a5a-9098-0102916d9430

### Desktop (please complete the following information):

- OS: Windows 11
- Browser: Tested on Chrome and Firefox
- Version: 22H2

### Additional context

This is where the "undo" notifcation is dispatched:

https://github.com/nusmodifications/nusmods/blob/b7c679edd76f9cbda44172c26955979f22c723e7/website/src/views/timetable/TimetableContainer.tsx#L60-L69

**Comment by zwliew** [comment]
Fixed in #3492
