### ISSUE TITLE
ESC Key not cancelling slot modifying on some specific slots 

### ISSUE THREAD

**Issue by HollaG** [nusmodifications/nusmods#3484]
### Describe the bug

In some (so far, only found 1) courses, when modifying a lesson slot (after clicking on the slot in the timetable), pressing the ESC key does not cancel it.

Seems to only occur when clicking on very specific slots.

### To Reproduce

1. Import this timetable in incognito 
https://nusmods.com/timetable/sem-1/share?CS2103T=LEC:G15

2. Click on the 1hr slot between 1100 - 1200 (important, as clicking the 2hour slots works somehow...?)
3. Try to press ESC to cancel
4. Timetable fails to quit modifying mode

### Expected behavior

Timetable should quit modifying mode

### Screenshots

![image](https://github.com/nusmodifications/nusmods/assets/31369072/2e16ae11-7357-4303-84f1-ea589d465828)
The buggy slot

### Desktop (please complete the following information):

Bugged behaviour on Windows observed
- OS: Windows 11
- Browser: Chrome, Firefox
- Version 115.0.5790.111 (Chrome), 116.0 (Firefox)

This bug does NOT occur on:
OS: MacOS 13.3.1
Browser: Safari
Version: 16.4 (18615.1.26.110.1)

### Smartphone (please complete the following information):

Not applicable on mobile

### Additional context

This bug also occurs for slots G11, G18, G22 and only when starting modification of slot from the 1hr timeslot.

This is such an obscure bug and I have no idea why it happens, the `onKeyUp` handler in TimetableContent.tsx is not even firing.
However, it DOES fire if you press the 'd' key (which opens the Download menu)

**Comment by jloh02** [comment]
In buggy modify mode, keybindings in `KeyboardShortcuts` still work but not all causes the `onKeyUp` handler in `TimetableContent.tsx` to fire.

Does not fire: `/`, `?`, `o`, `x`
Fires: `d`

Perhaps the reason it fires is due to the focus shifting as `d` causes the focus change to the download button
