### ISSUE TITLE
Escape button shortcut to close colorpicker

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#350]
Add escape button shortcut to close colorpicker for modules.

**Comment by zameschua** [comment]
I'm interested!

**Comment by yangshun** [comment]
Go ahead, it's yours!

**Comment by yangshun** [comment]
Some guidelines regarding this task - The event listener should be added upon mounting of the timetable view, and removed before unmounting of the view. The event listener should fire the dismiss colorpicker action (can't remember the name). 

The removal is to prevent duplicate adding of events, aka pressing escape once but firing the action more than once.
