### ISSUE TITLE
Module terminology still present archived modules banner

### ISSUE THREAD

**Issue by wongzw** [nusmodifications/nusmods#3522]
### Describe the bug

Module terminology still observed in banner for archive modules. It should be referred as a course instead of a module for consistency with the rest of the website. 

### To Reproduce

1. Go to any module that is not being offered this AY (e.g. https://nusmods.com/archive/MKT4813/2020-2021/design-thinking-business-innovations)

### Expected behavior

The banner should read "You are looking at archived information of this **course**" instead of "You are looking at archived information of this module"

### Screenshots

![image](https://github.com/nusmodifications/nusmods/assets/53685088/60db5eda-5364-4143-86b5-1be23afebf93)

**Comment by zwliew** [comment]
Thanks for reporting this!

**Comment by zwliew** [comment]
Related issue: 
![Screenshot 2023-08-09 at 12 37 28 AM](https://github.com/nusmodifications/nusmods/assets/4538946/2cf596f3-0bb9-44ee-80c2-5191cda1a7c6)

**Comment by zwliew** [comment]
Resolved
