### ISSUE TITLE
Migrate to Webpack 2

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#358]
Let's migrate again even before we launch 🎉

**Comment by ngzhian** [comment]
this might be helpful http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/

**Comment by li-kai** [comment]
I tried webpack 2, although webpack may be in rc, some of the plugins aren't ready yet.

https://github.com/webpack/extract-text-webpack-plugin/issues

Should I still push my webpack-2 branch and wait for the issues to be fixed?

**Comment by yangshun** [comment]
Yes can push first (:

Good that we know it's not production ready yet.

**Comment by li-kai** [comment]
Closed by #394
