### ISSUE TITLE
Venue data update for E-Learn_B

### ISSUE THREAD

**Issue by zwliew** [nusmodifications/nusmods#3586]
- Room Name: LT35
- Floor: 1
- Location: [1.2952035103792303, 103.7730199098587](https://www.openstreetmap.org/?mlat=1.2952035103792303&mlon=103.7730199098587#map=19/1.2952035103792303/103.7730199098587)

**Venue does not exist in current version**

**Update proposed:**

```json
"E-Learn_B": {
  "roomName": "LT35",
  "floor": 1,
  "location": {
    "x": 103.7730199098587,
    "y": 1.2952035103792303
  }
}
```

**Comment by chrisgzf** [comment]
Invalid
