### ISSUE TITLE
prerequesite tree not working

### ISSUE THREAD

**Issue by emsyou002** [nusmodifications/nusmods#3621]
### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Desktop (please complete the following information):

- Browser [e.g. Chrome, Safari]

### Smartphone (please complete the following information):

- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 14.0.0]
- Browser [e.g. Stock browser, Safari]

**Comment by chrisgzf** [comment]
Which page are you referring to?

**Comment by ravern** [comment]
Closing due to lack of detail. Please re-open this issue and edit the description or open a _new_ issue if the problem persists.
