### ISSUE TITLE
BMS5502 in list but no timetable lesson slots

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#364]
> Originally reported on facebook page

http://api.nusmods.com/2016-2017/modules/BMS5502.json

Seems like we don't have history for this module, might want to dig into why, it's probably an IVLE fault

**Comment by yangshun** [comment]
According to CORS there's no such module. There is, however, [BMS5502A](http://api.nusmods.com/2016-2017/modules/BMS5502A/index.json). Perhaps BMS5502 was renamed to BMS5502A? Will the scraper drop non-existent/outdated modules or will it do a merge? @li-kai @ahbeng

**Comment by yangshun** [comment]
I think this has been fixed.
