### ISSUE TITLE
Incorrect PreReq Tree for CS3282

### ISSUE THREAD

**Issue by RyanCheungJF** [nusmodifications/nusmods#3649]
### Describe the bug

I believe this is an incorrect prereq tree as CS3282 has traditionally only required CS3281. Furthermore, this prereq tree shows that the module requires 2 modules from every focus area, which suggests it is probably wrong.

Because of this issue, it affects several other CS modules to have incorrect prereq trees as well.

E.g.

![image](https://github.com/nusmodifications/nusmods/assets/63341400/8ab749c2-65ed-4db2-a6bb-8075ac65f546)

### To Reproduce

1. Go to [here](https://nusmods.com/courses/CS3282/thematic-systems-project-ii)

### Expected behavior

CS3282 should only require CS3281 I believe. It also looks like the prereq tree for CS3281 might also be broken.

### Screenshots

![image](https://github.com/nusmodifications/nusmods/assets/63341400/e6814e95-b26a-4c66-9103-8091a860b8ad)

![image](https://github.com/nusmodifications/nusmods/assets/63341400/638bfa25-b4e3-480b-a4df-34beeee7597f)

**Comment by Fidget-Spinner** [comment]
Generally the prereq tree is generated from data we get from NUS, which means in this case NUS should correct their data, not us.
