### ISSUE TITLE
Allow filtering courses by Grading Basis

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3664]
This has historically been a very common request, and as of last year (https://github.com/nusmodifications/nusmods/pull/3427) we finally have a field from the API to definitively tell us whether a course is letter-graded or CS/CU.

Let's do it!

Relevant files:
* https://github.com/nusmodifications/nusmods/blob/master/website/src/views/modules/ModuleFinderSidebar.tsx
* https://github.com/nusmodifications/nusmods/blob/master/website/src/types/modules.ts

**Comment by chew01** [comment]
Had a cursory look and I think the gradingBasisDescription will also need to be indexed in ElasticSearch else we are not able to aggregate that data.

**Comment by kokrui** [comment]
Yep! I'm thinking it may be easiest to just include the grading basis as an attribute of `ModuleInformation`

(as an aside, the different types defined in https://github.com/nusmodifications/nusmods/blob/master/scrapers/nus-v2/src/types/modules.ts should really be better-documented)

**Comment by chew01** [comment]
Re: documentation I think Swagger was meant to cover that at one point but it's clear that the schema there is outdated too 😅 If time permits (and the project is more active again) this is a good thing to work on

**Comment by kokrui** [comment]
let's goooooooooooo @chew01 🚀🚀🚀
