### ISSUE TITLE
Include Room Name in Venue Search

### ISSUE THREAD

**Issue by jloh02** [nusmodifications/nusmods#3686]
### Is your feature request related to a problem? Please describe.
When searching for venues, a user may only be told the name of a venue e.g. SR15 and not the unit. Currently, the only way to figure out the location of the room is by google searching NUS websites. This feature request proposes to allow users to find the unit number by simply searching the venue name in NUSmods

### Describe the solution you'd like
Include searching of room name (including abbreviations such as SR for seminar rooms)

### Describe alternatives you've considered
Include room names into all venue codes (although this will make it look very long and hence not ideal)
- [COM3-01-21](https://nusmods.com/venues/COM3-01-21) should include the SR number for example `COM3-SR12-01-21`

**Comment by mongj** [comment]
hi can I take this?
