### ISSUE TITLE
Move planner out of "beta"

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3689]
Our planner (https://nusmods.com/planner) has been "in beta" for around 5 years. While it doesn't have all the features it was planned to have at the start, it is useful enough (and used enough) (according to our analytics)

The big feature that was holding us back was graduation requirement validation. The best implementation looks like at https://nusplanner.com/ https://github.com/nus-planner/ right now, where people can contribute requirements in a DSL (or eventually somehow generate it from what-if reports).

There's some discussion here (https://github.com/nusmodifications/nusmods/issues/359) on creating such a grad requirement validator that may or may not be integrated in NUSMods. We're happy to support that work but for now let's set our planner free!

**Comment by wr1159** [comment]
Hi I am interested in this issue

**Comment by kokrui** [comment]
Go for it! @wr1159
