### ISSUE TITLE
Venue Search results should highlight matched substrings

### ISSUE THREAD

**Issue by mongj** [nusmodifications/nusmods#3720]
### Is your feature request related to a problem? Please describe.
Venue Search currently filters the list of venues according to what the user input into the search bar, but does not show which part of the result is actually being matched.

### Describe the solution you'd like
Matched substrings should be highlighted, similar to how it's implemented in the search bar in desktop view.
![Screenshot 2024-04-17 at 8 40 42 PM](https://github.com/nusmodifications/nusmods/assets/87565927/93d3afef-3c7d-418e-a65c-246d8d5467c9)

**Comment by kokrui** [comment]
Resolved in #3722
