### ISSUE TITLE
[NIT] Auto clear search bar after entering module code

### ISSUE THREAD

**Issue by btjm123** [nusmodifications/nusmods#3723]
On the `TimeTable` page, the module search bar does not automatically clear after pressing `Enter`. 

As a user, I would like to be able to add module codes sequentially by pressing Enter after entering each code - without the need to manually backspace/clear the search bar.

![Animation](https://github.com/nusmodifications/nusmods/assets/19306879/52f78579-7086-4a7e-962f-21a8496098d5)

**Comment by kokrui** [comment]
This makes sense to me! Happy to hear more opinions from users (e.g. does anyone regularly add courses by common prefix? or is there another use case for this?)

Otherwise, if anyone wants to implement this then go ahead!

**Comment by jloh02** [comment]
+1! Even if one were to add by common prefixes, clearing the input on enter seems like a more intuitive expected behavior to me

**Comment by leslieyip02** [comment]
Hi, I would like to work on this!
