### ISSUE TITLE
Update happypack to include loaders in config

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#374]
As of v3, happypack no longer infer the loaders argument, have to manually add it in.

https://github.com/amireh/happypack#loaders-arraystringobjectpath-string-query-string
> Inferring loaders has been officially removed as of HappyPack 3.0 and will not be re-introduced (in its previous form, at least) as it has proven to be too costly for the gain it provided.

**Comment by KenLSM** [comment]
It seems like happypack is not being used in this project anymore
#397

**Comment by li-kai** [comment]
@KenLSM Yep that's right. Thanks for highlighting this!
