### ISSUE TITLE
DSA2101 missing tutorials in Sem 1 timetable

### ISSUE THREAD

**Issue by yxinsee** [nusmodifications/nusmods#3745]
### Describe the bug

DSA2101 tutorial slots are missing from Sem 1 timetable

### To Reproduce

1. Go to 'Timetable'
2. Add 'DSA2101' as Course
3. See error

### Expected behavior

There should be tutorial slots available.

### Desktop (please complete the following information):

- OS: macOS
- Browser: Chrome
- Version: 126.0.6478.127

**Comment by ravern** [comment]
Thank you for bringing this up! We appreciate the effort to help improve NUSMods.

Unfortunately, we aren't in control of the data that is served to the platform, that's handled by your faculty / course administrators. Could you please email them to check if there are indeed supposed to be tutorials for Sem 1 but they aren't being displayed? Reason being, it is possible that there are no tutorials in one sem but tutorials in another.

If they claim the data they entered is correct, please feel free to re-open this issue and call it out.
