### ISSUE TITLE
FT5001, FT5002, FT5003, and FT5004's units are not consistant with the units shown on SoC website

### ISSUE THREAD

**Issue by TGtongga** [nusmodifications/nusmods#3746]
I found out that FT5001, FT5002, FT5003, and FT5004's units are all 2 as shown on SoC's official website https://www.comp.nus.edu.sg/cug/soc-sched/

However, on NUSMods, they are 4 units courses.

**Comment by ravern** [comment]
Thank you for bringing this up! We appreciate the effort to help improve NUSMods.

Unfortunately, we aren't in control of the data that is served to the platform, that's handled by your faculty / course administrators. Please contact them to verify that the data was entered correctly by them into the system.

If that's verified, please feel free to re-open this issue and call it out.
