### ISSUE TITLE
Missing timetable for CS2101

### ISSUE THREAD

**Issue by verakohh** [nusmodifications/nusmods#3748]
### Describe the bug

Missing timetable for CS2101 Sem 1. I can see the timetable in sem 2 but not sem 1. i think the timetable for sem 2 might be wonky too(see image provided below)

### To Reproduce

You can either see the missing timetable by searching for CS2101 and scrolling down to the timetable,
<img width="1104" alt="image" src="https://github.com/nusmodifications/nusmods/assets/102044785/01419ba2-c7b0-4b35-8d59-6785cb3fdba4">
 or you can go to timetable, add CS2101 as a course and it won't appear in your timetable.

### Expected behavior

I want to see the timetable

### Screenshots
<img width="1104" alt="image" src="https://github.com/nusmodifications/nusmods/assets/102044785/4ef2a16b-e93c-4bd8-b35a-328ebcc3d8a4">
<img width="1347" alt="image" src="https://github.com/nusmodifications/nusmods/assets/102044785/fb78e14a-f701-4ca2-a878-12c33c6aca9e">
<img width="979" alt="image" src="https://github.com/nusmodifications/nusmods/assets/102044785/5afa7afd-62b4-4753-b371-6ae48e5e692e">

### Desktop (please complete the following information):

- OS: sonoma 14.5
- Browser arc, chrome.
- Version not too sure

**Comment by Wxy2003-xy** [comment]
I can reproduce this.

According to module information retrieved from nusmod api, there indeed isnt any timetable info provided for cs2101 in sem1
![Image 11-7-24 at 17 57](https://github.com/nusmodifications/nusmods/assets/134219782/8d91e3d5-d502-4a5e-a306-9508a4e2f54a)

**Comment by kokrui** [comment]
Thank you for bringing this up! We appreciate the effort to help improve NUSMods.

Unfortunately, we aren't in control of the data that is served to the platform, that's handled by your faculty / course administrators. Please contact them to verify that the data was entered correctly by them into the system.

If that's verified, please feel free to re-open this issue and call it out.

**Comment by kokrui** [comment]
For what it's worth, as someone who took and TA-ed CS2103T + CS2101 recently, this was the case in the past and was intentional -- CS2101 slots are part of CS2103T's slots since lecture groups are shared across the courses
