### ISSUE TITLE
Add button to silence planner module conflicts

### ISSUE THREAD

**Issue by leslieyip02** [nusmodifications/nusmods#3751]
### Is your feature request related to a problem? Please describe.

I took UTC1702G in Sem 2 of AY23/24, but since it is only available in Sem 1 this year, there is a warning.

![Screenshot 2024-07-26 181858](https://github.com/user-attachments/assets/b45a68b7-1ca3-4a99-a13b-d258d024b158)

### Describe the solution you'd like

I think it could be helpful to have a button to silence warnings. I am also willing to work on this feature.

### Describe alternatives you've considered

I don't know how the logic to fix the issue above would work unless module availability data from previous years is stored somewhere.

**Comment by zwliew** [comment]
Instead of using course availability data from previous years, a simple fix could be to disable the warning for courses in the past. For example, since it is now 2023/2024 Sem 2 is in the past, we can disable the warning for UTC1702G (and any other courses) placed in that semester.
