### ISSUE TITLE
iCalendar File export does not account for public holidays in Singapore

### ISSUE THREAD

**Issue by staceytay** [nusmodifications/nusmods#376]
The calendar file generated includes lessons on public holidays but there should be no classes then.

**Comment by yangshun** [comment]
@staceytay Regarding this, there’s no way for us to know right? We don’t want to be hitting a public holidays API

**Comment by staceytay** [comment]
@yangshun I was thinking maybe maintaining, i.e. manually saving and updating it every year, a list of current public holidays that could be taken from http://www.mom.gov.sg/employment-practices/public-holidays#Year-2017 and checking against this list when generating the .ics file.

I'm no entirely sure how the .ics file gets created though.
