### ISSUE TITLE
Comments section is broken on Firefox

### ISSUE THREAD

**Issue by electronicvan** [nusmodifications/nusmods#3766]
Review and Discussion section does not load on Firefox Desktop and Mobile versions.

**Comment by itstrueitstrueitsrealitsreal** [comment]
Any screenshots of the issue? Also, which version of firefox are you using that causes the issue?

**Comment by electronicvan** [comment]
Screenshot:
![image](https://github.com/user-attachments/assets/9f788d9f-25ba-4a23-a4f5-6dd483c13b36)
Version:
![image](https://github.com/user-attachments/assets/3056dadb-9624-467a-9005-0c80fc92387c)

`Edition	Windows 11 Home
Version	23H2
Installed on	‎6/‎8/‎2024
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0
`

**Comment by SpookyYomo** [comment]
Hi @electronicvan, please check if you have Enhanced Tracking Protection on.
![image](https://github.com/user-attachments/assets/d9fdf4ba-9899-41a6-bfde-9000aaaf9073)

Disabling it for me renables Disqus.

**Comment by electronicvan** [comment]
That solves it for me, thanks @SpookyYomo.

**Comment by jloh02** [comment]
Let's continue tracking this under #3782
