### ISSUE TITLE
[Bug-Planner] Planning mods for future years do not show prerequisites on NUS Planner 

### ISSUE THREAD

**Issue by vrisdng** [nusmodifications/nusmods#3767]
### Describe the bug

Only mods that are put in the red highlighted zone (which I believe to represent 'current year') will be shown their prerequisites, but not anymore when you move to future years. 

### To Reproduce

1. Go to 'NUSMODS'
2. Click on 'NUS Planner'
3. Choose 'Settings' and set it to any years for 'Matriculated in' and any future years for 'Graduating' (For me I chose AY23/24 and In 3 years)
4. In my example, I selected module CS2109S for Year 2, prerequisites are shown and worked correctly. But when I moved this module to Year 3, prerequisites are not shown. 

### Expected behavior

Prerequisites should also be shown for future years apart from the current year, because users would want to be able to plan their modules for their entire tenure. If this is an intended feature, I think that restricting the module to have to be in the red highlighted area to show their prerequisites would not be practical for users e.g: What if they intend to take the module in Year 3 and want to see what prerequisites they need to clear and make adjustments accordingly? 

### Screenshots

<img width="1303" alt="Screenshot 2024-08-12 at 10 34 00 PM" src="https://github.com/user-attachments/assets/6621784d-f78e-4d52-9f9a-d5b05d328e58">

<img width="1195" alt="Screenshot 2024-08-13 at 12 15 48 AM" src="https://github.com/user-attachments/assets/bbc0a5c6-b785-44d9-b9a3-f2716f94ba5d">

### Desktop (please complete the following information):

- OS: MacBook Air
- Browser: Chrome

**Comment by zwliew** [comment]
Thanks for reporting! It'll be fixed in #3770.
