### ISSUE TITLE
Error: There was a problem submitting your feedback. Please try again later. 

### ISSUE THREAD

**Issue by derpbenji** [nusmodifications/nusmods#3769]
Error: There was a problem submitting your feedback. Please try again later. 

Unable to submit location information correction for venues.

1. Go to 'Venues'
2. Click on 'SDE-LT423'
3. Click on ‘Help us improve this map’
4. Click on ‘Problem with venue data’
5. Input ‘Email’
6. Input ‘Room Name’
7. Input ‘Floor’
8. Move Map Marker to correct location
9. Click on ‘Submit’
10. See error: “ There was a problem submitting your feedback. Please try again later.”

### Expected behavior

I expected my feedback to be submitted as the location of the current venue is wrong. However my feedback did no go through.

### Desktop (please complete the following information):

- OS: iOS 
- Browser: Opera GX
- Version 2.4.1

### Smartphone (please complete the following information):

- Device: iPhone 13 Pro Max
- OS: iOS 17.6.1
- Browser: Opera GX
- Version: 2.4.1

**Comment by jinxuan-owyong** [comment]
Same here, wanted to update SDE3-LT424

![image](https://github.com/user-attachments/assets/eac51ca9-ce46-4cc2-9714-1f7f32161191)

![image](https://github.com/user-attachments/assets/5c1ea550-4a4a-40fa-a13a-12bbdd4ed03e)

**Comment by kxing28** [comment]
Hey, others are trying to update this location too! I went to Tembusu on first day of class and couldnt find SDE3 🙃

The issue seems to occur during this POST from line 132 of `website/src/views/venues/VenueLocation/ImproveVenueForm.tsx`
```
axios
      .post(config.venueFeedbackApi, {
        venue,
        reporterEmail,
        floor,
        latlng: location,
        room: roomName,
      })
 ```

**Comment by zwliew** [comment]
Thanks for reporting. The service we used to handle venue updates shut down, so we're going to have to find a different way to host it. We'll fix it soon!

**Comment by theman-oj10** [comment]
Hi I will look into this!

**Comment by zwliew** [comment]
This has been fixed as of https://github.com/nusmodifications/nusmods/commit/4b98020c3f946c367155ca1891cf7b153ab5bbd1
