### ISSUE TITLE
No spacing between "Help us map this venue" button and timetable

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3773]
When viewing the details for a venue with no coordinate / location details, a "Help us map this venue" button is shown above the timetable of classes for the venue. However, there is no spacing between those 2 components, which looks odd

<img width="979" alt="image" src="https://github.com/user-attachments/assets/3806fdf5-6d5e-4b79-8d9c-bc76b0470ae1">

**Comment by g0at1** [comment]
Hi @kokrui, I took care of the spacing problem.
