### ISSUE TITLE
Course search page has filters section overflowing to below courses

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3774]
On the course search page (https://nusmods.com/courses), the "refine by" panel on the right sometimes ends up below the course search results. It would be helpful to figure out what causes this and fix it.

https://github.com/user-attachments/assets/23d283d5-2f87-434f-bfd1-0a976cddbf5a

Example in prod: https://nusmods.com/courses?p=4&sem[0]=1&sem[1]=2&sem[2]=3&sem[3]=4&mcs[0]=9

**Comment by theman-oj10** [comment]
I will look into this!

**Comment by zwliew** [comment]
Fixed in #3812
