### ISSUE TITLE
Replace occurrences of Google Groups email 

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3777]
We used to use a Google Groups forum (`nusmods<at>googlegroups<dot>com`) to take public questions / requests, and have the email `mods<at>nusmods<dot>com`. However, we've since decided that we should prefer all communications take place via `mods<at>nusmods<dot>com` for various reasons, and that we should eventually deprecate the Google Group.

We should take the first step towards doing that by replacing all occurrences of the old email with the new email on the website!

**Comment by shelialia** [comment]
Hi, I would like to take this issue.

**Comment by zwliew** [comment]
Resolved in #3795
