### ISSUE TITLE
Replace occurrences of "Module" with "Course" on the website

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3778]
While the maintainers don't intend to change occurrences of "Module" with "Course" in the codebase for now, it's useful to replace any such occurrences that appear on the website / UI.

Most obvious ones should have been replaced a year ago, but I can still find some examples.

For example, the settings modal of the planner:

<img width="688" alt="image" src="https://github.com/user-attachments/assets/aed8af6e-8186-4d7a-ba81-509ee478e499">

It would be helpful to find more occurrences and fix these occurrences.

**Comment by hua-en** [comment]
Hello @kokrui, I would like to contribute!
