### ISSUE TITLE
App crashes upon navigation between modules

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#378]
Steps to reproduce:

1. Open incognito mode (to ensure no local cache)
2. Navigation to a module via the nav bar search, e.g. CS1231
3. Click the back button
4. Try to navigate to a new module that is not CS1231.
5. Inspect console for error.

![screen shot 2017-01-13 at 11 35 33 am](https://cloud.githubusercontent.com/assets/1315101/21917661/6eb6a864-d984-11e6-9e2b-17b954f8ef8a.png)

**Comment by ngzhian** [comment]
feels like a race:

<img width="873" alt="screen shot 2017-01-14 at 12 10 22 pm" src="https://cloud.githubusercontent.com/assets/1749303/21952263/76654fba-da52-11e6-9cb8-327ef15db03c.png">

i put the console.log statements right before `return` in `render` method of ModulePageContainer.

**Comment by ngzhian** [comment]
I think it could be related to this:

<img width="867" alt="screen shot 2017-01-14 at 12 37 18 pm" src="https://cloud.githubusercontent.com/assets/1749303/21952407/37ba5ba8-da56-11e6-8a66-19fdd4a14d14.png">

Check out the first "called render", `module` is `undefined` but `fetchModuleRequest.isSuccessful` is `true`.
It seems like when we transition to a new module page, the module is set to undefined before we set the fetchModuleRequest to pending.

**Comment by li-kai** [comment]
Fixed since not sure when, but it's fixed, so it's all good. 😆
