### ISSUE TITLE
Incorrect venue data for E4-02-06

### ISSUE THREAD

**Issue by yangyi-zhu** [nusmodifications/nusmods#3781]
As of writing this, the location of E4-02-06 is shown to be next to LT6 on the map.
![图像_2024-08-20_115715485](https://github.com/user-attachments/assets/4b37c022-956a-474f-bf2e-c73be753329e)

The correct location of the lab should be on the Southeastern end of the building close to the Kent Ridge Crescent.
![image](https://github.com/user-attachments/assets/05b71343-eaa8-41a7-9760-d01e6a1c9c55)

**Comment by avellinwong01** [comment]
I would like to work on this

**Comment by Shaokey** [comment]
I will also work on this!!!

**Comment by zwliew** [comment]
Resolved in #3800
