### ISSUE TITLE
SDE3 venues wildly incorrect

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3783]
The data for a bunch of SDE venues, including:

- [ ] https://nusmods.com/venues/SDE3-BARM
- [ ] https://nusmods.com/venues/SDE3-LT421
- [ ] https://nusmods.com/venues/SDE3-LT422
- [ ] https://nusmods.com/venues/SDE3-LT423
- [ ] https://nusmods.com/venues/SDE3-LT424 (this could possibly be correct, but worth checking again)

look very wildly wrong. I personally know little about SDE but some of these LTs are placed in Tembusu College / Central Library which feels unlikely to me.

It'd be great if someone could track down and update the data for these venues!

**Comment by kokrui** [comment]
https://github.com/nusmodifications/nusmods/blob/master/website/src/data/venues.json

**Comment by yk-tuturu** [comment]
Hello, will attempt to improve this issue by shifting the coordinates to within SDE3. Not a complete fix as I don't know the exact coordinates of the venues.
