### ISSUE TITLE
Remove unused links from footer

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3786]
Right now, our footer lists a bunch of links

<img width="992" alt="image" src="https://github.com/user-attachments/assets/93077fae-889c-45e2-b1ee-c4917dd34f38">

We no longer use our Facebook page + Twitter page + Blog, and we no longer check messages sent via Messenger.

Therefore, we should remove these links from our footer!

**Comment by Franqsanz** [comment]
Hello @kokrui, I would like to contribute!
