### ISSUE TITLE
Remove FB Messenger from Feedback modal

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3788]
We display a Feedback modal at various places in NUSMods.com to solicit feedback

<img width="640" alt="image" src="https://github.com/user-attachments/assets/a235e2e9-2d00-4087-b66b-0fcf2c12aab9">

We no longer use Facebook Messenger as a feedback channel, so we should remove that button from the component

https://github.com/nusmodifications/nusmods/blob/59b78cc98376ed4ce3d3e20086614b9e92a46ad2/website/src/views/components/FeedbackModal.tsx#L18-L41

**Comment by mug1wara26** [comment]
working on this
