### ISSUE TITLE
Add NUSMods Telegram Channel to the site

### ISSUE THREAD

**Issue by kokrui** [nusmodifications/nusmods#3790]
We actively use a Telegram Channel for communications these days, but it's existence isn't very obvious from NUSMods.com itself.

We should consider adding the link to our Footer and/or in the Contributing page!

**Comment by Unknown15082** [comment]
I would like to work on this.

**Comment by Lwantstostophim** [comment]
i need someone from telegram to help asap theres tons of people and channels posting selling trading csam of a friend who was 14 at the time and emailing telegram and reporting does nothing

**Comment by zwliew** [comment]
Resolved in #3797
