### ISSUE TITLE
Add telegram button to contribution page

### ISSUE THREAD

**Issue by mug1wara26** [nusmodifications/nusmods#3794]
Since the telegram channel is not well advertised, it should be added to the contribution page.
![image](https://github.com/user-attachments/assets/1fb2ed67-b68e-4b9e-9acc-4426b5b75b7d)

**Comment by mug1wara26** [comment]
working on this

**Comment by kokrui** [comment]
I'm happy for this to be implemented and merged, though if we get insane amounts of spam from crawlers etc. we might have to revert this in future

**Comment by mug1wara26** [comment]
Also working on replacing all other mentions of messenger with telegram

**Comment by mug1wara26** [comment]
Fixed in https://github.com/nusmodifications/nusmods/pull/3792

**Comment by zwliew** [comment]
Fixed in #3792
