### ISSUE TITLE
Dark theme for color picker

### ISSUE THREAD

**Issue by jloh02** [nusmodifications/nusmods#3815]
### Is your feature request related to a problem? Please describe.

The color picker in timetable should support dark theme.

<img width="294" alt="image" src="https://github.com/user-attachments/assets/a1bcaed7-d8dd-4f32-9445-0f71f5204a21">

### Describe the solution you'd like

Adapt the picker based on theme user selected theme

### Additional context
`website/src/views/components/ColorPicker.tsx`

**Comment by JoarHansson** [comment]
I would like to give this a try. Could you assign me?

**Comment by jloh02** [comment]
@JoarHansson Go ahead and start on it. Please work on it promptly and open up a PR accordingly thanks!

**Comment by Ray7788** [comment]
Hi there, sorry to trouble you. But it looks everything works well? It works on my device(both Chrome and Safari))
