### ISSUE TITLE
Fix SASS deprecation warnings during build

### ISSUE THREAD

**Issue by zwliew** [nusmodifications/nusmods#3819]
Currently, when building the web app with `yarn build`, the build process spews a lot of warnings, mostly regarding deprecated SASS features.

Any help with fixing these deprecation warnings is much appreciated!

**Comment by shiva-karthick** [comment]
Hi, I would like to take up this issue. :)

**Comment by ravern** [comment]
> May I please confirm if the previous references satisfy this PR?

Can I clarify what you mean? The previous PR does make some progress towards reducing the warnings produced, but there are still some warnings that require more significant changes to fix, which are detailed in #3823 PR description. Also, we're not accepting PRs that silence the warnings, which was why #3820 was closed.

That being said, you're welcome to take up this PR!

**Comment by zwliew** [comment]
This has been fixed with the previous PR #3823 along with some dependency updates.

**Comment by shiva-karthick** [comment]
> This has been fixed with the previous PR #3823 along with some dependency updates.

Thanks for the update :)
