### ISSUE TITLE
Modules in Special Term do not show up in Today page

### ISSUE THREAD

**Issue by ravern** [nusmodifications/nusmods#3830]
### Describe the bug

After adding modules to my Special Term timetable, they do not show up in the Today page.

### To Reproduce

1. Add some modules with timeslots to your Special Term timetable (I'm using this one https://nusmods.com/courses/GES1002T/global-economic-dimensions-of-singapore)
2. Visit https://nusmods.com/today?date=2025-06-06 with the date query parameter to simulate the date of NUSMods
3. Module does not appear in the today page

### Expected behavior

The module appears on the today page, just like how regular semester modules do.

### Screenshots

<img width="2672" alt="image" src="https://github.com/user-attachments/assets/d618c46e-e889-4995-baa2-4930872ab0f5">

### Desktop (please complete the following information):

- OS: macOS
- Browser: Arc
- Version 1.61.2

### Additional context

Seems tangential to #3757.

**Comment by ravern** [comment]
https://github.com/nusmodifications/nusmods/blob/6588b48768449247e7d6a6c98e25755136c32f1d/website/src/utils/timetables.ts#L362-L364

This should be `isEqual(current, startOfDay(date))`

**Comment by xinyuwang-nus** [comment]
> https://github.com/nusmodifications/nusmods/blob/6588b48768449247e7d6a6c98e25755136c32f1d/website/src/utils/timetables.ts#L362-L364
> 
> This should be `isEqual(current, startOfDay(date))`

fixed in https://github.com/nusmodifications/nusmods/pull/3814/commits/a43106ac9fd1c17f4de4a571ee57b1b5238df322
