### ISSUE TITLE
Set up uptime alerts

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#384]
nusmods.com went down at 2am today (CPU spike, reason unknown) and we only discovered about its unavailability at 10am. Had to do a power cycle on the droplet to restart it.

Would be good to set up some form of monitoring like pingdom to inform us if and when it's down.

**Comment by ngzhian** [comment]
I set up https://uptimerobot.com/dashboard :)
Emails will go out to nusmods, yangshun, and myself if it goes down.
If you want to receive it / add integrations please login and set it up!
