### ISSUE TITLE
Add exam hours to timetable

### ISSUE THREAD

**Issue by yakandoit** [nusmodifications/nusmods#3876]
### Is your feature request related to a problem? Please describe.

It would be nice to show how long an exam is on the timetable page by the course name, instead of having to access the course page individually to get that info. 

<img width="524" alt="exam_hours" src="https://github.com/user-attachments/assets/4a66a7af-052c-404a-9fb7-6f3a948e3dd7">

### Describe the solution you'd like

Since exam length is already taken, we can just display it by the course info. 

### Describe alternatives you've considered

-

### Additional context

I'd like to be assigned to this

**Comment by zwliew** [comment]
This would be nice to have!
