### ISSUE TITLE
Orbital: Get your feet wet

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#389]
Hi Orbital!

If you are looking to get your feet wet 💧 , please make sure you look at #388 first. There is information regarding the proposal 📝 , and tutorials you can look through. Once you feel confident digging into the code base you may continue reading 📖 :)

To get comfortable around the codebase we suggest you do this (either by yourself or in your pairs):
- [ ] Read our [contributing guidelines](https://github.com/nusmodifications/nusmods/blob/master/CONTRIBUTING.md)
- [ ] Write some simple documentation, this can be specific to a module, method, higher level architecture overview of how NUSMods.com runs
- [ ] Create a button on the v3 navigation (this lets you play a bit with React)
- [ ] Clicking on the button brings you to a new page with your team's name and description of idea (this lets you play with react-router)
- [ ] Create a button on the timetable page that, when pressed, will clear the timetable. You should edit the actions and reducers for this (Lets you play with redux)
- [ ] Change the nav header to another colour you like! (Lets you learn how we do styling)
- [ ] Write a test to get our v3 coverage up! (you can see our coverage percentage as a little badge in the [v3 README](https://github.com/nusmodifications/nusmods/tree/master/v3) )
- [ ] Make a pull request to this project with the test you've written!

Note that these are exercises meant to help you get familiar with the code base and will not necessary be merged!

Good luck! As always, reach out to us on [Telegram](https://t.me/NUSMods) if you have any questions ❓ 

P.S. It will be great if you document your progress as you work through these tasks (and your orbital project), this will make your progress a bit slower (in terms of speed), but will help learning and retention, and probably be useful for newcomers in the future too! If you do write a blog post or anything, share them in the chat, or as a comment to this issue!

**Comment by yangshun** [comment]
Discussion will be shifted into #388
