### ISSUE TITLE
Misnamed AsyncTodayContainer

### ISSUE THREAD

**Issue by leslieyip02** [nusmodifications/nusmods#3920]
### Describe the bug

I think this should be `AsyncPlannerContainer` instead of `AsyncTodayContainer`.

https://github.com/nusmodifications/nusmods/blob/656b1447b9dbaa40befac5130d52bcad60b2341c/website/src/views/planner/PlannerContainer/index.tsx#L6-L20

It was likely copied from [here](https://github.com/nusmodifications/nusmods/blob/656b1447b9dbaa40befac5130d52bcad60b2341c/website/src/views/today/TodayContainer/index.tsx).

**Comment by kokrui** [comment]
your observation looks right to me, we'll approve a PR for this!
