### ISSUE TITLE
Orbital: Setting goals and expectations

### ISSUE THREAD

**Issue by ngzhian** [nusmodifications/nusmods#393]
First, thanks for considering NUSMods as your orbital project! We are very excited 😃  At the same time, we need to set some expectations so that all of us can have a fruitful summer ☀️ .

I've mentioned this before, and I think it bears repeating that the nusmods team has high standards 💯 . If you **expect your code to be merged** into our projects, you must understand the following:
1. We will review your pull requests **many, many** rounds to ensure code is of high quality before we merge
2. You might have to **rewrite** what you do (this probably won't happen if you ask questions in a timely manner, but if it does, we will request you do so)
3. You have to work **independently**, we cannot hand hold you to learn the stack, you have to learn it on your own, what we can do is send you pointers on where to learn

Please remember, you are free to do some NUSMods related project at your own time (without the expectations that your code will be merged). The NUSMods API is open for your consumption, so if you wish to do, for example, some sort of module visualisation project using the API, you may do so in your own project. (And in the future you can slowly work towards merging that project into nusmods if you wish to)

As always, happy to chat in the telegram group :) Happy hacking!

**Comment by yangshun** [comment]
Discussion will be shifted into #388
