### ISSUE TITLE
NUS Stackexchange [1295]

### ISSUE THREAD

**Issue by Kyomian** [nusmodifications/nusmods#399]
**NUS Stackexchange**

**Objective**

To create a forum where students are able to ask/answer questions. These Q&A will be collected in a database, and future generations of students can retrieve and view them.

By having such a forum, “good answers” will not be lost. Professors and TAs also need not have to spend extra effort answering to the same questions asked by every cohort, as they could refer students to the forum.

**How it will work?**

1. Students would register an account with the forum or use their IVLE account to sign-in.
2. The website homepage will show the different faculties/schools in NUS. In each faculty/school, there will be different modules and each module will have its own forum. Every student will have access to each forum.
3. Each forum is categorised into “Unanswered” questions and “Answered” questions. For each category, newest questions will be placed first. For each question, newest answers will be placed last, while the best answer will be placed at the top. 
4. Users are able to vote for the best answer for each question. 
5. Students are encouraged to participate in this platform to gain incentives such as CA marks. 
6. In each forum, there will be a search bar to search for a particular question using keywords. 

**Estimate of Timeline**

In May, we will concentrate on building one module forum first, construct the format for each questions and format for each answers to be stored in the database. After which, we will push and pull these data from the database. The basic interface will also be done up to facilitate the testing of the MVP functions. 

In early June, we will build the login features, the user database, and allow users to post questions/answers in the module forum (that we have created in May).  

From late June to early July, we will build more forums, and categorise them into their respective faculties/schools. In late July, we will build the search bar features. We may also add a chat function if time permits to link up individual students with the current professor that is teaching that particular module. 

In August, we will do the final touch-ups, such as making the website more aesthetically pleasing.

**Technologies**

HTML/CSS, JavaScript (Node.js, Meteor.js), MongoDB.

**Samples**

After log-in:

![new doc 2017-05-14 21 13 05_1 10152](https://cloud.githubusercontent.com/assets/28558144/26109037/da9e2e5a-3a80-11e7-8d42-22b608554bb9.jpg)

**Comment by yangshun** [comment]
This will be a good learning experience but practically speaking, using open source forums like Discourse will be a more viable option.

**Comment by li-kai** [comment]
It's all about execution. I don't think discourse/forums are the best platform for discussion. Sites like StackOverflow & Reddit are successful because upvoting content really helps quality wise.

I think the timeline here is pretty reasonable, maybe marginally ambitious. Could you explain (briefly) your choices for technologies? Do you guys have prior experience in Meteor?

**Comment by Kyomian** [comment]
Hi Li Kai, 

These are the technologies that we have learnt from the workshops in Orbital. We do not have prior experience in Meteor, though we know some HTML/CSS, JavaScript and PHP. We feel that the Meteor framework is worth knowing and using, and it is simpler too.

**Comment by yangshun** [comment]
> It's all about execution. I don't think discourse/forums are the best platform for discussion.

I don't think two/three months is sufficient for a team of two to execute a platform that is polished and engaging enough for long-term usage by the school.

I do think the scope of a fully-functioning and engaging forum is too big for a summer project. It would be good to break it down into a few milestones with various deliverables and work according to that.

**Comment by Kyomian** [comment]
Hi Yangshun,

MVP:
1. Users are able to create threads for various modules
2. Users are able to post any forms of answers to a thread.
3. Users are able to favourite a thread and view it in their "favourites" tab.
4. Login in/Logout feature

We are keeping our project modest for the purposes of Orbital. Maybe we could focus on a few faculties/schools first.

**Comment by li-kai** [comment]
Hey @Kyomian, may I know if you have applied to be mentored by us for Orbital officially? If not, are you still expecting guidance from us regarding this project of yours?

**Comment by Kyomian** [comment]
Hi @li-kai, yes! I have applied to be mentored by you guys. Have completed the form, and still awaiting for confirmation!
