### ISSUE TITLE
Migrate build system from grunt to gulp

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#40]

**Comment by ngzhian** [comment]
In lieu of the ever-changing landscape of nodejs build system, is gulp still our target? Or should we aim for webpack/<any other build framework>?
(sorry I'm a nodejs noob so I'm not too familiar with what's *really* good, I just know some buzz-framework-names)
cc @yangshun

**Comment by yangshun** [comment]
Gulp is still relevant. If we use webpack then we can do away with browserify and it'll involve a major overhaul. We can afford to migrate to gulp first, for faster build times

**Comment by yangshun** [comment]
Closed via #258
