### ISSUE TITLE
Considering adding a "Today" screen

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#401]
The "Today" screen is like a single-day column that displays the lessons you have later today. Mainly for mobile. Inspired by:

![new_app_store_three_iphones_apps_games_today](https://cloud.githubusercontent.com/assets/1315101/26812265/524f6c2e-4aa9-11e7-8c41-1463f2ea70e1.jpg)

**Comment by zameschua** [comment]
I'm interested, made something similar for my Orbital project
![image](https://user-images.githubusercontent.com/18271085/28496028-ce97b986-6f92-11e7-8484-20a37b1782e2.png)

Also suggest fixing the navbar at the bottom for mobile
https://uxplanet.org/perfect-bottom-navigation-for-mobile-app-effabbb98c0f

**Comment by yangshun** [comment]
Let's leave the today screen out first. It's not a high priority. The priority would be to achieve feature parity. Navbar at the bottom is something we want to change to. If you're interested you can create an issue for that.

**Comment by ZhangYiJiang** [comment]
Done-ish with #1236
