### ISSUE TITLE
Prerequisites tree for CS4243 broken

### ISSUE THREAD

**Issue by acruis** [nusmodifications/nusmods#408]
Link to module page: https://nusmods.com/modules/CS4243

Red boxes indicating prerequisite modules within the prerequisite tree do not contain the module code:

<img width="500" alt="screen shot 2017-07-07 at 4 31 50 pm" src="https://user-images.githubusercontent.com/8437638/27952346-2a6ab3de-6332-11e7-9bcb-2e7cf213d8e7.png">

Reproduced on Chrome 59.0.3071.115 and Firefox 54.0.1.

**Comment by yamgent** [comment]
Graph seems to screw up when the prerequisites comprise of different possible combinations of modules (e.g. `[X or Y or Z] and [A or B] and [C or [D or E]]`)

This also happens on [CS3235 Computer Security](https://nusmods.com/modules/CS3235):

![cs3235](https://user-images.githubusercontent.com/3168908/28244670-2a07ac88-6a23-11e7-9743-868f14d29003.png)

**Comment by Dartteon** [comment]
This is happening to CS4222 too (https://nusmods.com/modules/CS4222)

**Comment by li-kai** [comment]
Fixed in v3 with #451

**Comment by acruis** [comment]
👍
