### ISSUE TITLE
Fix navbar at bottom of the screen on mobile

### ISSUE THREAD

**Issue by zameschua** [nusmodifications/nusmods#411]
https://uxplanet.org/perfect-bottom-navigation-for-mobile-app-effabbb98c0f

**Comment by li-kai** [comment]
I don't think we should do it at all as it's nearly impossible, see [mobile safari limitations](https://benfrain.com/the-ios-safari-menu-bar-is-hostile-to-web-apps-discuss/). There's a reason why twitter lite's menu bar is at the top 🙁

**Comment by yangshun** [comment]
Oh wow I didn't know this since I don't use iPhone. Indeed I did wonder why Twitter Lite's menu bar is at the top. @zameschua if you feel like it, you can try to shift it to the bottom and see if it is indeed impossible. Else, we can close this issue.

Good find @li-kai !

**Comment by zameschua** [comment]
Haha thanks @li-kai!

https://www.eventbrite.com/engineering/mobile-safari-why/
Eventbrite seems to have done it but requires a workaround. I think can close for now if it's not priority.

**Comment by yangshun** [comment]
With iPhone X shifting the home button to the button, this might be a bad idea now.
