### ISSUE TITLE
SEO for SPA

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#45]
Especially important for module pages, none of which can be seen by search engines currently.

**Comment by yangshun** [comment]
Seems to be indexed by search engines now. We have the top hit for CS3230, wow!

![screen shot 2015-06-01 at 8 22 59 pm](https://cloud.githubusercontent.com/assets/1315101/7912648/08c54fb6-089c-11e5-88ef-f3d7a270f008.png)
