### ISSUE TITLE
Update React to v16 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#454]
This issue is tracking things that are blocking the upgrade to React 16 

- [x] react-disqus-thread needs to be replaced (disqus-react is the replacement, but currently blocked by https://github.com/ryanvalentin/disqus-react/pull/4)
- [ ] react-virtualized-select is throwing PropTypes and createClass warnings. This is weird because from what I can see of the  source code, the package is doing things correctly - this needs further investigation

**Comment by li-kai** [comment]
[react-virtualized-select](https://github.com/bvaughn/react-virtualized-select/) is using react-select v1.0.0-rc.2, which is still using PropTypes and createClass.
