### ISSUE TITLE
Refactor hidden modules

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#473]
Hidden modules is currently stored in `settings` object as inside the `hiddenInTimetable` array. That's not the best representation as the hidden/show state of a module should be put inside the semester's timetable instead and be specific to a semester instead of an app-wide setting. Also, there's a bug where hidden modules that get removed are still within the `hiddenInTimetable` array.

**Comment by li-kai** [comment]
I have a suggestion, we could simply use a class name similar to our color scheme like `color-nil` or something. That way, invisible can be a color in our picker, and make changes accordingly instead of separating the picker component in two parts (the square and picker).

**Comment by yangshun** [comment]
So you're saying we have a 9th color? Do we want to hide the details or simply make the cell transparent (but still show the words)?

**Comment by li-kai** [comment]
Yep, something like the top left icon 
<img width="225" alt="screenshot 2017-11-02 14 20 09" src="https://user-images.githubusercontent.com/14850387/32312477-fb99a48a-bfd8-11e7-85fb-2e0d7c12b29a.png">

We still hide the details, but that "special handling" wouldn't be in the module details component any more, but in TimetableContainer instead.

**Comment by li-kai** [comment]
Oh I forgot one more thing. Right now if they try to change a hidden modules' color, they wouldn't know why it's not changing as they're still able to open the picker. A transparent color helps us save space too, one fewer icon, less code.
