### ISSUE TITLE
Integrate Google Analytics into NUSMods R

### ISSUE THREAD

**Issue by luyangkenneth** [nusmodifications/nusmods#489]
I'm thinking we can use the [react-ga](https://github.com/react-ga/react-ga) wrapper library for this. Please let me know if you're aware of a better alternative!

#### Relevant links:
- https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
- [v2 Event Tracking - Google Docs](https://docs.google.com/document/d/126ycJnWR87LSHEm1xhxUeG5xu5jF9-c9UyaI42y90sQ/edit) (I got this from #33)

## Tracked events in v2

After examining the codebase, I found that there are 22 tracked events in v2, and 5 of them have been ported to v3 (to varying extents of similarity).

<details>
<summary>Click to expand</summary>

#### Export timetable
- [x] JPEG
- [ ] PDF
- [ ] HTML
- [x] iCal
- [ ] Excel

#### Preferences
- [x] Change faculty or new student status

#### Add module
- [x] From module page
- [ ] From module finder

#### Modules filter
- [x] Click on checkbox
- [ ] Click on hyperlink (I think this refers to the accordion headings?)

#### Misc
- [ ] Click on `Back to top` button

#### Keyboard shortcuts
- [ ] Timetable Search (`.`)
- [ ] Main Search (`\`)
- [ ] Navigate to page
- [ ] Navigate to anchor section
- [ ] Toggle dark mode (`x`)
- [ ] Change theme (`left`, `right`)

#### Bookmarks
- [ ] Add bookmark from module page
- [ ] Add bookmark from module finder
- [ ] Remove bookmark
- [ ] Access module from bookmarks
- [ ] Display bookmarks
</details>

## Next steps

I feel that v3 would need an updated set of events we want to track, given the new UI. Also, I don't think we should use the exact same messages as the tracking calls in v2, because then we wouldn't know whether a call came from a v2 or v3 session (unless we use a different tracking ID?)

So perhaps this task needs a bit more definition, and as a new contributor I'm not sure how this process works or how I can be involved. But in the meantime, I could go ahead and figure out how to integrate GA into v3, without adding any trackers.

What do you guys think? 🙂

**Comment by yangshun** [comment]
Thanks for collating this! We will add analytics *after* shipping v3.

Btw don't use `react-ga`, it doesn't contribute much value (disclaimer: I maintained it for a year) 😂

**Comment by yangshun** [comment]
@ZhangYiJiang I have created a new tracking ID for v3 - `UA-33503218-6`

**Comment by yangshun** [comment]
We might also wanna consider using https://github.com/googleanalytics/autotrack

**Comment by li-kai** [comment]
We've sinced moved to using Mamoto which is a much more privacy focused tracker: #1234
