### ISSUE TITLE
Allow simple sorting by module code/title/exam time

### ISSUE THREAD

**Issue by hongshaoyang** [nusmodifications/nusmods#492]
small feature improvement: would love if the table below could be sorted. e.g. something like dropdown arrows that allows you to sort in ascending or descending order.

![alt text](https://i.imgur.com/nJqFGQG.png)

i think it might help especially when looking at the order of your finals

edit: just realized that the mods are already sorted by finals date. but i think it might also be helpful to sort by module code as well. what do you guys think?

**Comment by ZhangYiJiang** [comment]
Hi, thanks for the suggestion! I think the feature could be useful. However, in v3 (the next version of NUSMods in active development and scheduled for launch next semester) the UI is card based, not table based, which means the we can't use the table headers. A dropdown menu would work, although currently there isn't space for one which means things need to be moved around a bit if we want to add this. 

As we're busy with making v3 ready for launch this probably won't be implemented until after launch. However, if you would like to implement this yourself, we're happy to help you get started. 

- v3 current build: https://latest.nusmods.com/timetable
- README: https://github.com/nusmodifications/nusmods/tree/master/v3

**Comment by ZhangYiJiang** [comment]
Completed by #1064
