### ISSUE TITLE
Scroll position preserved on page navigation

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#523]
Pages should be automatically scrolled to the top when they are opened, as it does not make sense to start viewing the middle of the page.

### Steps to reproduce

1. Navigate to <https://latest.nusmods.com>.
1. [Shrink browser viewport height](https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports) if necessary.
1. Scroll to bottom.
1. Click Settings. The Settings page will be loaded but you'll be at the bottom of the page.

Can be reproduced with static pages as well - switch between About, Team and FAQ.

**Comment by yangshun** [comment]
That's something I wanted to fix. I'll fix it, it's not tough.
