### ISSUE TITLE
Experiment with CircleCI and potentially migrate to it

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#525]
CircleCI seems like a good alternative to Travis CI and brings about some other features:

- [Artifacts](https://circleci.com/docs/2.0/artifacts/) to let us store our builds and we can potentially just extract the build artifacts from there without the need to run the build step ourselves during deployment 
- [Workflows](https://circleci.com/docs/2.0/workflows/) enable us to run various steps of the CI on parallel, which reduces overall duration (think Jest, ESLint and Flow checking running in parallel). In Travis now we're running them sequentially.
- Potential to integrate [BuildSize](https://buildsize.org/) to catch build size regressions in PRs.

Also, we can request for [Open Source Discount](https://circleci.com/pricing/#faq-section-linux) for more containers!

A current foreseeable downside is that CircleCI does not support build matrix, which the current Travis CI set up uses. We might or might not need it in future depending on:

- Might not - When we completely move to v3, no need to run tests for v2 anymore
- Might still - We might merge `nusmods-api` into a [monorepo](http://danluu.com/monorepo/) and we'll need build matrices again.

If we do migrate to CircleCI and need build matrices, there's [Tox](https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5) for that.

**Comment by ZhangYiJiang** [comment]
Fixed by #639
