### ISSUE TITLE
History messed up for modules and venues

### ISSUE THREAD

**Issue by li-kai** [nusmodifications/nusmods#530]
To reproduce:
1. click "modules" or "venues" and try to go back to the previous screen, you need 2 to do so.
2. click "modules", "venues", go back to "modules" then try to go forward to "venues" via history, but it is wiped.

**Comment by ZhangYiJiang** [comment]
I think I know where the bug is. Should be easy to fix - it's caused by the page calling `history.push` unnecessarily when there's no change in the URL/query string

**Comment by taneliang** [comment]
Two more:

3. Click "modules", click a module, go back, and you can't go forward.
1. Click "venues", click a venue, click another venue, go back. You're back at `/venues` with the first venue selected and you can't go forward.
