### ISSUE TITLE
Filter pane scrolling issues on iOS

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#540]
1. No inertial scrolling.
2. That glitching when scrolling around at the top of the filter pane.

Huge gif demonstrating this:
![out](https://user-images.githubusercontent.com/12784593/34211544-03f28c96-e5cc-11e7-90e3-3ee75e38e434.gif)

Bug 1 doesn't apply to Android, but bug 2 somewhat applies to Android as well - you get strange behavior when you scroll the nav bar instead of the content.

**Comment by ZhangYiJiang** [comment]
Fixed by #544
