### ISSUE TITLE
Custom faculty/department selector unusable on iPad

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#547]
1. When keyboard is down, selecting an item brings the keyboard up by focusing the text field. The text field is sometimes hidden behind the keyboard when it's focused. Focusing the text field on select is a good idea except in this situation.
![547.1](https://user-images.githubusercontent.com/12784593/34304832-0181dcac-e76e-11e7-9e29-cea0577ec18d.gif)

2. When keyboard is up, selecting an item selects something else *sometimes*. On iPad (5th generation), I couldn't reproduce this in portrait mode. May be partly caused by https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8? ![547.2](https://user-images.githubusercontent.com/12784593/34304929-7ce873c4-e76e-11e7-85fa-409606c38ba3.gif)

**Comment by ZhangYiJiang** [comment]
Hmmmm, maybe use [media interaction](https://caniuse.com/#feat=css-media-interaction) query to expose mobile (ie. FAB) UI to iPad? It's a workaround for this particular issue, but I feel that maybe that would be helpful for the rest of the UI too
