### ISSUE TITLE
Improve Bootstrap component styling in night mode 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#570]
The following UI components can be better styled in night mode: 

- [x] Alerts (background, border, font colors) 
- [ ] Form elements (border color) 
- [x] Modal and elevated elements (darken shadow, border) 
- [ ] Dropdown menu (menu item hover/selected state, elevation) 

A new set of CSS variables will need to be defined for each of these colors, then the original styles should be overriden. Alternatively, ~~~explore using Bootstrap's internal mixins to do this so we don't get duplicate CSS declarations~~~ not possible - the alert mixins uses `mix` internally, which means we can't use CSS variables as parameters.

**Comment by li-kai** [comment]
Modals too, shadows are black, the inverse should be a light gray instead
