### ISSUE TITLE
Export image button does not work on Microsoft Edge

### ISSUE THREAD

**Issue by yunpengn** [nusmodifications/nusmods#592]
Nothing changes after clicking the export image button.

Open the console, see the following error message:
![image](https://user-images.githubusercontent.com/18503402/34366604-70370f48-eae1-11e7-9032-811ac659fa23.png)

The export iCal button does not work as well.

**Comment by ZhangYiJiang** [comment]
Can reproduce. I remembered @li-kai using `msSaveBlob` in #575 at some point, but that doesn't seem to be there anymore so that PR doesn't solve this, hmmm.

**Comment by ZhangYiJiang** [comment]
May be related: https://sentry.io/nusmods/v3/issues/424358674/

**Comment by yangshun** [comment]
Hey @yunpengn , thanks for the bug report. Could you share with us why you have the need to export the timetable at this point of time?

**Comment by yunpengn** [comment]
I use this feature in the old version of NUSMods quite frequently.  Basically, I prefer to view my timetable as a local file rather than open the browser. This is more like personal preference though 😄

**Comment by yangshun** [comment]
I see, got it! Because I was thinking no one would export since their timetable hasn't been finalized. We'll look into it soon (:

**Comment by ZhangYiJiang** [comment]
#575 doesn't seem to solve this for me. We may need #596 to solve this.

**Comment by ZhangYiJiang** [comment]
Fixed by #623
