### ISSUE TITLE
Global search enhancements 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#594]
## Features / v2 parity 

- [X] Link to more results in module finder and venues page as the last result - this addresses the issue that the search shows too few results compared to v2 
- [X] Alternatively, consider making it display more results in a scrollable list 
- [x] Consider displaying module semester availability in the results - again, v2 parity 
- [X] Consider making it wider on wider screens so that module titles don't wrap 
- [ ] Enable global search on mobile 

## Bugs 

- [x] Fix search term highlighting - currently it highlights the search term verbatim, which is not how the search algorithm works

**Comment by li-kai** [comment]
@ZhangYiJiang I believe we can close this?

**Comment by ZhangYiJiang** [comment]
@li-kai That last one is important though. Maybe open a new separate issue and flesh out the design?
