### ISSUE TITLE
Manually specifying lesson groups

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#6]
From [NUSMods Facebook page](http://www.facebook.com/NUSMods):

> **Lim Chai Hou Danny**
> The last one about specifying the lec/tut/lab groups manually is available on the official builder and somewhat so in nuschedule. In the latter users can just click on individual buttons representing the different lec/tut/lab groups and the module timeslots will change accordingly. Useful for students whose groups are assigned (mainly Engin) or just quickly checking for clashes after the balloting. (Instead of displaying all the group buttons they can be hidden in a popup or something.)
> 
> **NUSMods.com · NUS CORS Module Finder & Timetable Builder (Unofficial)**
> 6. I think enhanced dropdowns, kinda like in the official builder, would be the way to go? As in that case you already know the name and it'd be faster to select it via auto-completion. But yeah needs to be somewhere where it doesn't clutter up the interface. I'm thinking like maybe a pop-out sidebar with all the dropdowns arranged vertically, then you could just type and tab through the controls quickly.
> 
> **Lim Chai Hou Danny**
> 6. Yeah, I agree with the dropdown ones. Maybe the sidebar can be minified and placed beside the listed mods at the bottom again.

**Comment by yangshun** [comment]
I think we're good with this in v3.
