### ISSUE TITLE
Pulsing TimetableCell overlapped by the day name cell

### ISSUE THREAD

**Issue by kiangkuang** [nusmodifications/nusmods#600]
The selected TimetableCell is overlapped by the day name cell during pulse animations
![image](https://user-images.githubusercontent.com/7030358/34376506-faeb1d24-eb26-11e7-9a53-7c53ff29453d.png)

**Comment by ZhangYiJiang** [comment]
Thanks for reporting this! I agree that this visual blemish is slightly annoying. However, fixing this is non-trivial, as the module also needs to stay *under* the day name when the timetable is scrolled to the right. If you would like to help us with this, we can help you get set up - just drop into [our Telegram group](https://telegram.me/nusmods) and talk to us. Thanks!

**Comment by kiangkuang** [comment]
Ah, I see the dilemma. I will see if I can do a JS solution where the z-index is set higher _only_ while not scrolled right to keep the current scrolling behavior intact.

**Comment by ZhangYiJiang** [comment]
Sure. You might want to start with the `<Timetable>` and `<TimetableDay>` components in in https://github.com/nusmodifications/nusmods/tree/master/v3/src/js/views/timetable

**Comment by taneliang** [comment]
Fixed by #616
