### ISSUE TITLE
Export image not responding

### ISSUE THREAD

**Issue by 1moresec** [nusmodifications/nusmods#619]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Clicking the export image button is not triggering further actions in Safari (but it works with Chrome, see below for the information about my device)

**If the current behavior is a bug, please provide the steps to reproduce and if possible, a minimal demo of the problem via a screenshot or a video recording (on macOS you can use QuickTime).**

Github said it doesn't support my filetype when I try to upload my screen recording mp4. Hope this issue is described clear enough.

**What is the expected behavior?**

A standard way could be a pop-up window with textfield to change name and saving datapath selection

**Further information**

- Which version of NUSMods are you currently using? (Check the footer for the version number, 20171228-4449f02)
- Did this work in NUSMods BEFORE the R release/redesign? it's a new button
- Did this work in NUSMods AFTER the R release/redesign? No
- Which browser and version are you using? E.g. Safari version 11.0.2
- Which device are you using? E.g. MacBook Pro
- Which operating system and version are you on? E.g. macOS 10.13.2

**Comment by 1moresec** [comment]
I just viewed [#592](https://github.com/nusmodifications/nusmods/issues/592) and found the similar issue. So some further information: Currently I don't need this function that much, and since I can do it with Chorme it's not a big deal in user side😄maybe the team can put a notification for Safari users for now and solve this later.

**Comment by ZhangYiJiang** [comment]
Hi, thanks for the report! We're aware of the issue. Please track #596 if you would like updates on this.

**Comment by ZhangYiJiang** [comment]
Fixed by #623
