### ISSUE TITLE
Manually curate / Crowdsource venue-building / geocoding information 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#654]
From user feedback

>  I can't even find the different abbreviations of the venue on the NUS website TT~TT
however i guess it is good to have a legend or something to show what each abbreviation stands for? Like TP, ERC, and like DV all these

I think this would be useful. Building a crowdsourced solution may be too difficult, so a stopgap measure may be something simpler, like a manually updated CSV or JSON file that we can direct students to update themselves via Google Spreadsheet/Forms or GitHub. 

The page can automatically expand abbreviations, like 

> ## Education Resource Center - Seminar Room 1 (ERC-SR1) 

or maybe include it in a tooltip, or a table on the sidebar. The data doesn't need to be perfect to be useful.

**Comment by yangshun** [comment]
That's a good idea. The data doesn't change often and it'll be worth the time to do so.

**Comment by taneliang** [comment]
We could use the [NUS Living Lab APIs](https://wiki.nus.edu.sg/display/nllapi/Room) to get some data. In fact we may even be able to download a list of ALL the rooms in NUS here https://nuslivinglab.nus.edu.sg/api_dev/api/Dept?name=&output=json.

However, that data doesn't correspond to our computed venues list exactly. Specifically:

1. There are many rooms in our computed Venues list that do not exist in the API. E.g. [dRm1](https://nuslivinglab.nus.edu.sg/api_dev/api/Room?RoomCode=dRm1)
2. There are many rooms in the API that do not exist in our list. My guess is that these are the rooms we don't really care about anyway, such as staff rooms etc.
2. There are some room locations in the API that are a bit dubious. Can't remember any off the top of my head though.
3. Some venues names in our list do not match the entries in the API. E.g. [AS1-0207](https://nusmods.com/venues/AS1-0207) and [AS1-02-07](https://nuslivinglab.nus.edu.sg/api_dev/api/Room?RoomCode=AS1-02-07). This looks like a consistent discrepancy across some faculties though, so we could write a script to format the names correctly before querying.

Could still be a good starting point though.

We could also merge the lists to come up with an integrated campus map + venue lessons view. I'm sure we can beat [NUS Campus Map's](https://map.nus.edu.sg) design

**Comment by taneliang** [comment]
With the Dept API described in my last comment, slightly less than half of our venues can be enhanced with room names and their departments. The results of this attempt can be found here: https://github.com/taneliang/NUSVenues/blob/master/results.

But not all hope is lost! I found a catalog of NUS location APIs here: https://arcgis.ami-lab.org/arcgis/rest/services. Some notes:

1. [Floor plans](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017).
    1. These include detailed floor renderings, e.g. https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/FloorplanGroup11/MapServer?f=jsapi
    1. Room shapes, e.g. [AS1-01-02](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/Cartography_UNGROUPED_14_7_17/MapServer/find?searchText=AS1-01-02&contains=true&searchFields=&sr=&layers=368&layerDefs=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&dynamicLayers=&returnZ=false&returnM=false&gdbVersion=&f=html)
1. Room locations (x, y, and even z coords!) can be found at various endpoints. However, most include some UTown data such as ERC and SRC but not the RCs. These two below seem to be the most complete, with UTown RCs included:
    1. [The POI locator API](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/POI_LOCATOR_051017/GeocodeServer). e.g. [AS1-01-02](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/POI_LOCATOR_051017/GeocodeServer/findAddressCandidates?SingleKey=AS1-01-02&SingleLine=&outFields=&outSR=&searchExtent=&f=html).
        1. Returns 3D coords and room codes, and that's about it.
        1. However, batch and fuzzy searches are supported - [an example](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/POI_LOCATOR_051017/GeocodeServer/geocodeAddresses?addresses=%7B%22records%22%3A%5B%7B%22attributes%22%3A%7B%22OBJECTID%22%3A1%2C%22SingleKey%22%3A%22BIZ1-0301%22%7D%7D%5D%7D&outSR=&f=html). However, we have to be careful as non-existent rooms like "AS1-02-02" will still match "S11-02-02".
    1. [The full NUS network API](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/FULL_NUS_NETWORK_051017/MapServer), e.g. [BIZ1-03-02](https://arcgis.ami-lab.org/arcgis/rest/services/FULL_NUS_NETWORK_051017/FULL_NUS_NETWORK_051017/MapServer/find?searchText=biz1-03-02&contains=true&searchFields=&sr=&layers=8&layerDefs=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&dynamicLayers=&returnZ=false&returnM=false&gdbVersion=&f=html).
        1. Returns (among other things): room names ("ARTIFICIAL INTELLIGENCE LAB 3"), floor numbers, room codes ("COM1-01-19"), item category (e.g. "ROOM", "BUILDING") and 3D coords if `returnZ` param is set.
        1. However, batch and fuzzy searches are not supported, although substring searches are. This means that a hacky way to dump all the data will be just to search for "A", "B", ..., "Z", "0", "1", ..., "9".
    1. Some rooms like "dRm1" still can't be found.
1. Unfortunately, the [bus route APIs](https://arcgis.ami-lab.org/arcgis/rest/services/CampusNetwork/Bus_Routing_V2/MapServer) are very outdated.
1. @yangshun has found that the APIs use the EPSG:3857 coordinate system. These can be transformed to the "usual" EPSG:4326 coordinates [online](https://epsg.io/transform#s_srs=3857&t_srs=4326&x=11551835.5587032&y=144174.5979994) and [offline](https://github.com/proj4js/proj4js). Here's also an [interesting post](http://lyzidiamond.com/posts/4326-vs-3857) describing their differences.

Given these APIs, we should be able to do the following:

1. In the short term, enhance the Venues feature:
    1. Sanitize most of the venue names (a.k.a. room codes) using the fuzzy batch search in the POI Location API.
    1. All found venues can be enhanced with 3D coordinates, room names and floor numbers using the NUS network API.
    1. We can then display room names, floor numbers, the official NUS room codes (not the inconsistent official junk CORS feeds us), and a pin on a map describing the location.
    1. It'll be nice to be able to get the building name of every room for even easier navigation. If there's no API for this, we could just manually place every room by using the building polygons and the room coordinates.
1. With much more work, implement a new Maps feature. There are many more rooms (probably around 5-10x more) than our Venues feature contains and this provides an opportunity to create many interesting features. E.g. it'll be interesting to have a feature that tells you the nearest male/female toilet to you. This may be best implemented as a mobile app as well. React Native? 😄

**Comment by ZhangYiJiang** [comment]
Done in #1106
