### ISSUE TITLE
Add more keyboard shortcuts 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#656]
v2 had a variety of keyboard shortcuts - we're using the same library ([Mousetrap](https://github.com/ccampbell/mousetrap)), so it shouldn't be too hard to add them back too. 

Shortcuts use Redux actions to effect change in the application, so you'll probably need to add those too. For focusing search, it may be possible to get away with DOM based hacks since it's really not convenient to lift focused/open state all the way up to the Redux store. 

Here's what I propose for the shortcuts 

- Help (show all shortcuts in a modal) <kbd>?</kbd>

- Go to (page) - <kbd>g</kbd> + 
  - Timetable <kbd>t</kbd>
  - Modules <kbd>m</kbd>
  - Venue <kbd>v</kbd>
  - Settings <kbd>s</kbd>
- Toggle orientation - <kbd>v</kbd>

(When <kbd>g</kbd> is pressed, the links should show what shortcuts they have, like how Office does when you press <kbd>alt</kbd>)

- Add module <kbd>a</kbd>
- Prev / Next semester <kbd><</kbd> <kbd>></kbd>
- Global Search <kbd>/</kbd>
- Local search (on module finder and venues page) (help me think of a shortcut here) 

And if you really want to be hardcore, try implementing Google search style keyboard shortcut for navigating the module finder, venues page and the module table on the timetable page. That would be fun.

**Comment by yangshun** [comment]
For focus states, we can consider using the app reducer. The app reducer is for non-persistent UI state and I think it's reasonable to add it there.

**Comment by ZhangYiJiang** [comment]
I think using Redux for this is an overkill, since that would entail two-way binding (`onFocus`/`onBlur` events on the form element dispatch events, state changes from store triggers `ele.focus()`/`ele.blur()`), whereas what we really want is to just fire-and-forget - if the element is there, focus it, otherwise do nothing. 

Downshift controlled elements are a bit trickier, since they don't necessarily have a nice DOM interface. We could have a global DOM/React instance map that's used exclusively for this that can also abstract away the difference, although it's less clean since it entails creating a global variable.
