### ISSUE TITLE
Historical CORS Bidding Data

### ISSUE THREAD

**Issue by indocomsoft** [nusmodifications/nusmods#659]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

It only shows the last semester's CORS Bidding data

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

Go into any module's page in nusmods, then scroll down to the CORS Bidding stats.

**What is the expected behavior?**

It should give an option to see the stats for previous semesters, for feature parity with v2. (to be honest, I really like the new way of presenting data, and I'd understand if it wouldn't be possible to present stats for the previous semesters in the new v3 form)

**Further information**

- Which version of NUSMods are you currently using? (Check the footer for the version number, 201XXXXX-XXXXXXX)
20180104-cdde0ba
- Did this work in NUSMods BEFORE the R release/redesign?
Yes
- Did this work in NUSMods AFTER the R release/redesign?
No
- Which browser and version are you using? E.g. Chrome 62/Firefox Quantum 57/Safari 11.1.1/etc
Chrome 63.0.3239.111 Mobile on Android
- Which device are you using? E.g. MacBook Pro/Surface Pro/iPhone X/etc
OnePlus 3
- Which operating system and version are you on? E.g. macOS 10.12.5/Windows 10/iOS 11.0.0/etc
Android 7.1.1

**Comment by ZhangYiJiang** [comment]
This looks like a data issue, not a UI issue. I remember testing this when I built the new UI - it handled historic data just fine. Data for CS1010S only has last semester's data, when I remembered it had more - http://api.nusmods.com/2017-2018/2/modules/CS1010S.json cc @li-kai

**Comment by ZhangYiJiang** [comment]
I believe this has been resolved. Thanks for the report!

**Comment by indocomsoft** [comment]
Yup, it's working now. Thanks for the quick turnaround!
