### ISSUE TITLE
It is not obvious from the module info page that a module has no exam

### ISSUE THREAD

**Issue by xinan** [nusmodifications/nusmods#660]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

On the new module info page of a single module, if the module has an exam, the exam date and time will be shown on top of the "Add to Semester X" button. However, if there is no exam for that module, no clue is given. I spent quite a while looking for exam info and in the end figured out that that is the behavior of no exam.

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

Open the module info page of a module that has no exam. E.g. [MUA2201](https://nusmods.com/modules/MUA2201/keyboard-literature-i) and [CS5218](https://nusmods.com/modules/CS5218/principles-of-program-analysis)

**What is the expected behavior?**

It should be obvious to the user that the module has no exam.

**Further information**

- Which version of NUSMods are you currently using? 20180104-cdde0ba
- Did this work in NUSMods BEFORE the R release/redesign? Yes
- Did this work in NUSMods AFTER the R release/redesign? No
- Which browser and version are you using? Mobile Safari on iOS 11.2.1
- Which device are you using? E.g. 1st gen iPad Pro 12.9
- Which operating system and version are you on? iOS 11.2.1

**Comment by yangshun** [comment]
It'll just take you five minutes at most to implement this yourself 🌝

**Comment by taneliang** [comment]
Implemented in dd279c93b28db77e3b5ba16c0c12dc135efca3e3

**Comment by xinan** [comment]
@yangshun I didn't bring my laptop back home. I only have an iPad now. Vacation mode 😌
