### ISSUE TITLE
CORS Bidding Stats by timeslots

### ISSUE THREAD

**Issue by indocomsoft** [nusmodifications/nusmods#674]
**Do you want to request a *feature* or report a *bug*?**

Feature/bug (depending on whether regression from v2 is considered a bug)

**What is the current behavior?**

CORS bidding stats is showing only the aggregate total, instead of breakdowns by lecture slots

**What is the expected behavior?**

There should be an option to show breakdowns by lecture slots

**Further information**

- Which version of NUSMods are you currently using? (Check the footer for the version number, 201XXXXX-XXXXXXX)
20180104-6acd88b
- Did this work in NUSMods BEFORE the R release/redesign? Yes/No/Unsure
Yes
- Did this work in NUSMods AFTER the R release/redesign? Yes/No/Unsure
No
- Which browser and version are you using? E.g. Chrome 62/Firefox Quantum 57/Safari 11.1.1/etc
Google Chrome 63.0.3239.84 (Official Build) (64-bit) (cohort: Stable)
Revision 8f51ed0e633e109109762a3deb18a50e8c138819-refs/branch-heads/3239@{#643}
- Which device are you using? E.g. MacBook Pro/Surface Pro/iPhone X/etc
Surface Pro 4
- Which operating system and version are you on? E.g. macOS 10.12.5/Windows 10/iOS 11.0.0/etc
Windows 10 Version 1709 Build 16299.125

**Comment by ZhangYiJiang** [comment]
Could you tell us why would you need the breakdown for each lecture slot? We chose to merge the data because for most modules the slots are different each semester so it is not useful to compare data for each slot across semesters, and the data for each individual slot is less useful compared to the data for the entire module as a whole.

**Comment by ZhangYiJiang** [comment]
To be fair that is also an assumption. Our experiences are limited to our own faculty, so if it is different for yours please let us know so we can fix NUSMods. 

If you do need the data, you can view the source of our data, which is the CORS bidding data archive - http://www.nus.edu.sg/cors/archive.html

**Comment by indocomsoft** [comment]
I think for some modules, the timeslots remain the same for the past year or two. Nevertheless, including this information might make the interface too cluttered. Perhaps you could include a link to direct people the CORS archive in case they don't know.

But overall, I don't think it is a necessary to port over this feature to NUSMods R. Thanks for the clarification on the rationale
