### ISSUE TITLE
Display module title in timetable cell

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#677]
We received many requests to display the module title in the timetable cell. Seems like we underestimated the number of people who have enough memory space to memorize their module titles.

Design a UI that allows toggling of display of module title within the timetable cells. This setting can possibly be on the timetable UI itself or in the Settings page. For simplicity we probably will not have the module title  show  on vertical mode because the layout will not work with that, and it is not necessary on other pages (for now) where the timetable component is being used.

**Comment by ZhangYiJiang** [comment]
Fixed by #709
