### ISSUE TITLE
Show number of Disqus comments in module info page side menu 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#683]
From user feedback 

> Could we have the number of reviews shown with the Reviews tab? It could save one click to the reviews section if no one comments on the module!

This should be relatively simple - create a new `<CommentCount>` component (reference https://github.com/ryanvalentin/disqus-react/blob/master/src/CommentCount.jsx), and with the common code from `<DisqusComment>` extracted out that would display the number of comments. 

The side menu items (https://github.com/nusmodifications/nusmods/blob/master/www/src/js/views/modules/ModulePageContent.jsx#L268) will probably need to be converted back to static items from a for-loop for this to work.

**Comment by wenmogu** [comment]
Can i take this issue

**Comment by taneliang** [comment]
@wenmogu Sure! Feel free to ask us if you have any questions [on our Telegram group](https://telegram.me/nusmods)
