### ISSUE TITLE
Add basic functional tests to be run on Sauce Labs

### ISSUE THREAD

**Issue by thebengeu** [nusmodifications/nusmods#70]
Sauce Labs is [free for open source projects](https://saucelabs.com/opensauce).

f6e55c3f6db02434e41c486e7f63a8eb0585fc32 fixed a bug which had caused the timetable not to display on iOS. It had not been caught as manual testing had not been done on iOS, and was deployed to production for about an hour.

Even very basic automated tests should be catch severe bugs like that and prevent it from happening again.

**Comment by ZhangYiJiang** [comment]
Fixed by #1056
