### ISSUE TITLE
Adding modules to timetable seems to lag

### ISSUE THREAD

**Issue by taneliang** [nusmodifications/nusmods#717]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Selecting a module in `ModuleSelect` lags if the module is not in the module bank.

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

1. Go to /timetable
1. Tap on "Add module to timetable" input
1. Key in some text and add any module that are not previously viewed or added (ie. not cached in moduleBank)
1. Nothing happens appears to happen 
1. The module is added after a short while (if this appears to be instantaneous, use the browser dev tools to artificially slow down your connection) 

**What is the expected behavior?**

A spinner or something similar should be displayed while the module details are being loaded, so that it doesn't look like NUSMods is frozen.

**Comment by liaujianjie** [comment]
Can I take this issue?

**Comment by ZhangYiJiang** [comment]
@liaujianjie Go right ahead. This one is a bit tricky because we're dealing with both Downshift and async state. If you need help ping us on Telegram.

**Comment by taneliang** [comment]
@liaujianjie Sure. I think we should display a spinner in the module table, that way once we merge some sync PR (#808), the timetable page won't flash when a module is added on another device.

Also, I implemented a middleware to load new module data into moduleBank here https://github.com/nusmodifications/nusmods/pull/808/commits/49a9b4ba3905cd6f26d46055e986f307b8c14df3#diff-6d6a7d452384caae82e0b6f566bffce3R11. You *might* be able to adapt it to help fix this issue.

**Comment by li-kai** [comment]
I highly prefer the optimistic version, where we immediately indicate the module is added, then reflect any error if present. I'd rather users not have to wait for n spinners when adding n modules.

**Comment by taneliang** [comment]
Even better. It'll be best if it can work with modules added remotely

**Comment by liaujianjie** [comment]
@taneliang should I branch out from your accounts branch?

**Comment by liaujianjie** [comment]
What about having the spinner where the "Added" tag is supposed to be at?

![screen shot 2018-02-22 at 10 40 39 pm](https://user-images.githubusercontent.com/3143132/36544448-7d1a32ea-1821-11e8-9b05-981183c343e3.png)

**Comment by taneliang** [comment]
@liaujianjie Nah I think you should branch from master. `accounts` was meant for sync and is not really related to this. You can cherry pick commits from `accounts` but the commit history isn't super clean (sorry).

I was thinking about putting a spinner there as well, but it'll be better to avoid spinners completely and add new mods optimistically as @li-kai suggested. Plus, putting the spinner there won't help with remotely added mods.

**Comment by ZhangYiJiang** [comment]
I agree optimistic is the way to go, although on desktop the lessons themselves can't be shown until the module is loaded, so this is a bit tricky. We need to think about the UI a bit more carefully.

**Comment by liaujianjie** [comment]
Optimistic UI usually has some form of a placeholder while the content is loading. I'm not sure how it'll work for our case.

**Comment by taneliang** [comment]
Actually it may not be the best time to fix this bug if the changes will be non-trivial.

We are planning to move to a GraphQL data API, and Apollo Client should be able to handle a lot of the logic that (I think) will have to be implemented to fix this now. The new code written for this will probably also make it harder to switch to GraphQL.
