### ISSUE TITLE
Improve 404 page info for module info pages 

### ISSUE THREAD

**Issue by ZhangYiJiang** [nusmodifications/nusmods#719]
After reviewing the 404 errors reported on Sentry, I've noticed one of the more common 404 errors happens when users try to access what seems to be a module that existed at some point in the past, but is not mounted this year. 

It may be useful to add some additional help content for the module page 404 page to address this case.

**Comment by leeyjjoel** [comment]
Hi, can I take this issue?

**Comment by ZhangYiJiang** [comment]
@leeyjjoel Sure - could you outline what do you plan to do?

**Comment by li-kai** [comment]
[Reactjs documentation](https://reactjs.org/tutorial/tutorial.html#what-is-react) is a good starting point. Take note of the props and how it interacts with the html it produces.

next, the relevant page is NotFoundPage.jsx, which is currently stateless. You would need to pass in some props which let you know where to user came from. This would likely come from [react-router](https://reacttraining.com/react-router/web/api/history), a library we use.

You will need to know if the user came from a module, but that module does not exist in our "database", which is simply `ModuleList` from the ModuleBank store. This part would be a little tougher as it involves redux, but feel free to search how we import moduleList in other components. You don't need to touch anything much more redux than that.

Lastly is just showing some message like "Module currently does not exist. It may have removed.".

Let us know if you need more clarification. 😆

**Comment by ZhangYiJiang** [comment]
Fixed by #1017
