### ISSUE TITLE
Toast disappears after spamming a keyboard shortcut

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#723]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Pressing on a keyboard shortcut shows a toast message at the bottom.

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

Keep spamming the keyboard shortcut and the toast eventually disappears, never to be seen again with further triggering of the shortcut.

I recommend just replacing the text if a toast is already shown, rather than hiding and showing again.

**What is the expected behavior?**

The toast should still appear.

**Further information**

- Which version of NUSMods are you currently using? 20180115-357758b
- Did this work in NUSMods BEFORE the R release/redesign? NA
- Did this work in NUSMods AFTER the R release/redesign? NA
- Which browser and version are you using? Chrome 63.0.3239.132
- Which device are you using? E.g. MacBook Pro 2017
- Which operating system and version are you on? macOS 10.13.2

**Comment by taneliang** [comment]
Related: The toast remains below the page content after it's dismissed, but it's visible on Macs when the page is over scrolled.

<img width="836" alt="perm" src="https://user-images.githubusercontent.com/12784593/34926357-d36d0628-f9e9-11e7-9b7d-b0daa88988a3.png">

**Comment by ZhangYiJiang** [comment]
@taneliang Known upstream issue https://github.com/material-components/material-components-web/issues/1258

**Comment by taneliang** [comment]
@ZhangYiJiang Ah. We could use this workaround for now. https://github.com/material-components/material-components-web/issues/1258#issuecomment-334368890

**Comment by Rinder5** [comment]
Hi! If this is not being worked on right now, is it ok if I attempt this?

**Comment by ZhangYiJiang** [comment]
Go right ahead. Let me know if you need help setting up or understanding the code.
