### ISSUE TITLE
Exporting .ics rounds down :30 timings to the nearest hour

### ISSUE THREAD

**Issue by louietyj** [nusmodifications/nusmods#724]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Exporting .ics rounds down :30 timings to the nearest hour

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

1. From a clean slate, add CS5330 (lecture at 6.30pm).
2. Export .ics
3. Observe that the lecture timing on the .ics file is wrongly represented as 6pm and not 6.30pm

![image](https://user-images.githubusercontent.com/11096034/34926531-080a43cc-f9eb-11e7-9dd8-f5dc0e31e497.png)

**What is the expected behavior?**

Should be 6.30pm.

**Further information**

- Which version of NUSMods are you currently using? NUSMods R version 20180115-357758b.
- Did this work in NUSMods BEFORE the R release/redesign? Yes
- Did this work in NUSMods AFTER the R release/redesign? Unsure
- Which browser and version are you using? Chrome 63
- Which device are you using? Computer with wooden circuit board
- Which operating system and version are you on? Windows 10

**Comment by ZhangYiJiang** [comment]
Fixed and deployed. Close all open tabs and refresh a few times, and this should work now
