### ISSUE TITLE
Custom colors not reflected in exported image/PDF 

### ISSUE THREAD

**Issue by mpzy** [nusmodifications/nusmods#739]
**Do you want to request a *feature* or report a *bug*?**

<ANSWER HERE>

**What is the current behavior?**

<ANSWER HERE>

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

<ANSWER HERE>

**What is the expected behavior?**

<ANSWER HERE>

**Further information**

- Which version of NUSMods are you currently using? (Check the footer for the version number, 201XXXXX-XXXXXXX)
- Did this work in NUSMods BEFORE the R release/redesign? Yes/No/Unsure
- Did this work in NUSMods AFTER the R release/redesign? Yes/No/Unsure
- Which browser and version are you using? E.g. Chrome 62/Firefox Quantum 57/Safari 11.1.1/etc
- Which device are you using? E.g. MacBook Pro/Surface Pro/iPhone X/etc
- Which operating system and version are you on? E.g. macOS 10.12.5/Windows 10/iOS 11.0.0/etc

**Comment by ZhangYiJiang** [comment]
Can you provide more information? A copy of the PDF you received that looks different, and a screenshot for comparison? In addition, which theme were you using? Do you have dark mode on? Did you change the color of any of the modules?

**Comment by taneliang** [comment]
@mpzy Welcome to GitHub! Apart from @ZhangYiJiang's questions, we'd appreciate it if you would answer the questions in the issue description as well — just hit the edit button and fill in your answers. We need more details in order to diagnose and solve your problem, as we currently are not noticing any messed up colour schemes. Thank you!

**Comment by mpzy** [comment]
Hi Yi Jiang,


Attached are the screenshots. I have chosen a particular colour for each of the module in the timetable under the Office colour scheme. However, once downloaded either as image or pdf, the colours change and is regardless of whichever colours I have chosen for my timetable. I do not have dark mode on. Sorry for the lack of information as I am not very sure of how to use the Github platform. Thanks


Yours Sincerely

Marcus Phua



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by ZhangYiJiang** [comment]
Hi, no problem. I can't see your screenshot (it seems GitHub only converts the text of your email to a comment, not the attachment), but I understand the problem now. We'll be fixing this shortly.

**Comment by ZhangYiJiang** [comment]
@mpzy This has been fixed and deployed. Thanks again for the report!
