### ISSUE TITLE
Unify efforts for NUS initiatives

### ISSUE THREAD

**Issue by yeesian** [nusmodifications/nusmods#75]
Off the top of my head, we already have:
- [ModMaven](https://github.com/ashrayjain/ModMaven)
- [Corspedia](https://github.com/weiqingtoh/corspedia) and [CORS API](https://github.com/ejamesc/cors-api)
- [NUSMorge](https://github.com/yyjhao/NUSMorge)
- [NUS Stalker](https://github.com/fuzzie360/nus-stalker) and its [python API](https://github.com/jsyeo/nus-stalker)
- [ModCrasher](https://github.com/Leventhan/ModCrasher)
- [IVLEDownloader](https://github.com/yyjhao/IVLEDownloader), [IVLE Drive](https://github.com/ashrayjain/IVLE-Drive), [IVLE Fix](https://github.com/darora/IVLE-Fix), [IVLE API](https://github.com/ymichael/ivleapi) and [modivle](https://github.com/ymichael/modivle)
- [NUSMods](https://github.com/ahbeng/NUSMods) and [cljs-nusmods](https://github.com/yanhan/cljs-nusmods)

and probably some others that I have missed. It might be worth the effort to unify some of these initiatives, and to provide a consistent API. I am opening this thread to initiate discussion.

---

Here's a proposal about how we can proceed: as a first step, it'll be a good idea to be able to separate the _view_ from the _content_. E.g. for instance,
- [NUSMods](https://github.com/NUSModifications/NUSMods) (or [modivle](https://github.com/ymichael/modivle)) as the view, with
- [NUSModsAPI](https://github.com/NUSModifications/NUSModsAPI) (or [IVLE API](https://github.com/ymichael/ivleapi)) providing an API to the content

This will make it easier for others to re-use your data (e.g. [NUSMorge](https://github.com/yyjhao/NUSMorge) and [ModCrasher](https://github.com/Leventhan/ModCrasher)). This means that cron jobs (e.g. those in [ModMaven](https://github.com/ashrayjain/ModMaven/commit/eb5910a84c49f708e2c7b971d194359234c21d52)) should be available through **NUSModsAPI**; perhaps file an issue or PR?

Why go through all the effort? As **ModCrasher** puts it:

> By building on top of NUSMods API's JSON file, we don't have to reinvent the wheel and write our own crawler and focus instead on user-facing features that make our app a pleasure to use.

---

More importantly, it's often difficult to identify the appropriate codebase to redirect new developers (who might be interested in contributing), much less to find successors. Having a clear and consistent organization allows for easier discovery of what's available (or not), whether it's a crawler, or a user-facing feature they wish to contribute.

Here's what such an organization might look like, with **NUSModifications** as the [github organization](https://github.com/NUSModifications):
- **NUSSchedule** (currently NUSMods + ModMaven?)
- **NUSBid** (CORS bidding; corspedia)
- **NUSCloud** (IVLE cloudsync)
- **NUSMaps** (for geocoding of locations -- see https://github.com/ahbeng/NUSMods/issues/51)
- **NUSSocial** (for stalking/tracking/sharing among students - e.g. stalker.fuzzie.sg and morge.yjyao.com)
- **NUSDatasets** (inspired by https://github.com/johnmyleswhite/RDatasets.jl  -- to provide access to past archives of bidding-data/class-schedule/geolocations/requirements/etc)

cc: @weiqingtoh, @ahbeng, @yangshun, @ashrayjain, @yyjhao, @khankuan, @ejamesc, @fuzzie360, @infinitus, @ngzhian, @ymichael, @cgcai, @darora, @jcheng31, @yanhan, @jsyeo

**Comment by yangshun** [comment]
NUSModifications has been a decent point of unification of NUS-related projects over the past few years. Most student projects do not stand the test of time; the only ones surviving so far (to my knowledge) is NUSMods and NUSWhispers, which are already part of NUSModifications. I believe it is ok to close this issue now.
