### ISSUE TITLE
Visual aid for POPULARITY OF TUTORIALS using heatmap techniques

### ISSUE THREAD

**Issue by cuthbertyeo** [nusmodifications/nusmods#77]
The current tutorial choices from the use of NUSMODs provides:

1) No. of different slots and hence its permutations
2) The different buildings, blocks, levels and room which is held 

Some of the common problems faced by students are:

1) The lack of knowledge of other people's choices and hence the flooding of small sized tutorial rooms when people jump (especially tutorials with no grades attached hence no attendance)

Hence i recommend that since NUSMODs is so popular amongst NUS students alike....After making our choices, is it possible for the server itself to gather all the choices of tutorial slots made by students since we usually arranged and leave it in our browsers... and our timetable reappears again when we switched on our computers or toggle between programs as our choices of timetable has already been cached. Server will make use of such caches and sum its results to tell current users of the popularity of tutorials slots involved for each particular module.

![image](https://cloud.githubusercontent.com/assets/8245609/3673309/b3fd9046-126b-11e4-8451-75faf7296673.png)

Colour would change reddder to signify that too many has chosen that slot time. OR flashes at higher frequency as our mouse cursor hovers over that slot. OR simplest method would be that of the LIKES we see in facebook where numbers would simply appear when we hover over or chose that slot with a message like this: "27 students has chosen this." , etc.

**Comment by yangshun** [comment]
Not really worth doing this considering CORS is only twice a year and lasts only 2 over weeks.
