### ISSUE TITLE
Can't sync the timetable from NUSMods into my iCalendar

### ISSUE THREAD

**Issue by yangshun** [nusmodifications/nusmods#772]
**Do you want to request a *feature* or report a *bug*?**

Bug

> Hi can someone help me out? I can't sync the timetable from NUSMods into my iCalendar. Seems like it can't differentiate odd and even weeks. 

From [NUSWhispers](https://www.facebook.com/nuswhispers/posts/1772078842862569).

Not sure if this bug report is too ambiguous. Feel free to close it if it is.

**Comment by ZhangYiJiang** [comment]
Possibly the same person as https://www.facebook.com/nusmods/photos/?tab=album&album_id=1295002143979630. 

My suspicion is that the timezone is incorrect. The way which iCal export works is it generates a repeating event, then exclude the events which fall on holidays, recess weeks, and week 1-3 for tutorials. This means that if the tz is wrong, the exclusion would not match the repeating event, which means the event would not be excluded.

**Comment by ZhangYiJiang** [comment]
Hmmm, but our test cases running on CircleCI uses a UTC env. Anyway this shouldn't be too hard to test manually.

**Comment by ZhangYiJiang** [comment]
It could just be that the calendaring software they're using doesn't support excluded events?

**Comment by ZhangYiJiang** [comment]
We have a second report, so I think we can confirm this. So far all of the theories above have been ruled out - TZ is in SGT, and the calendaring software supports excluded events (I think). 

The commonalities are that their calendar client is the macOS. One user reports v10.0, will check with the others. The files themselves are fine - I get the expected results when importing into GCal, and also Calendar v9.0. This indicates it may be a bug in Calendar itself, which would be very painful. 

Can someone with v10.0 in High Sierra confirm this?

**Comment by ZhangYiJiang** [comment]
Reopening. PR did not fix issue >_< 

We may actually have to do live debugging on their computer via remote desktop or meet them in person. This is really annoying. Why Apple whhhhyyyyy
