### ISSUE TITLE
Cannot export .ics twice

### ISSUE THREAD

**Issue by louietyj** [nusmodifications/nusmods#785]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Cannot export .ics twice

**If the current behavior is a bug, please provide the steps to reproduce. If possible, please upload a screenshot or link to a video recording (on macOS you can use QuickTime) demonstrating the problem.**

1. Start with clean slate.
2. Export .ics. Observe that an .ics file downloads.
3. Add a module, say CS4231.
4. Export .ics. Observe that _no_ .ics file downloads.

**What is the expected behavior?**

Second .ics file should download.

**Further information**

- Which version of NUSMods are you currently using? **NUSMods R version 20180126-d626f1d**
- Did this work in NUSMods BEFORE the R release/redesign? **Unsure**
- Did this work in NUSMods AFTER the R release/redesign? **Unsure**
- Which browser and version are you using? **Chrome 63**
- Which device are you using? **Wooden computer, possibly not Turing-complete**
- Which operating system and version are you on? **Windows 10 x64**

**Comment by taneliang** [comment]
Step 3 appears to be unnecessary to repro. I blame the wooden computer

**Comment by louietyj** [comment]
I blame the wooden computer too. I think I need a plastic one instead!
