### ISSUE TITLE
Maintain consistent CSS coding style using CSSComb

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#82]
We already have a [CSSComb](http://csscomb.com/) [config](https://github.com/ahbeng/NUSMods/blob/master/.csscomb.json), just need to automate checking as part of the build process. To be done after the gulp migration (#40) is completed.

**Comment by ngzhian** [comment]
should we be using something like [sass-lint](https://www.npmjs.com/package/sass-lint) instead of css lint?

**Comment by yangshun** [comment]
v3 uses style lint
