### ISSUE TITLE
[Enhancement] Include Module Workload Limits

### ISSUE THREAD

**Issue by yeesian** [nusmodifications/nusmods#83]
Related:  http://blog.nus.edu.sg/provost/2014/05/14/a-different-grading-system-in-the-first-year-for-undergraduates-part-ii/

- **CORS**: http://www.nus.edu.sg/cors/policies.html
- **Engineering**: http://www.eng.nus.edu.sg/ugrad/MS_cors_information.html
- **Business**: http://bba.nus.edu/undergrad_gradefree.html
- ...

Sounds like we're heading into dark territory here though... with [ModMaven](https://github.com/ashrayjain/ModMaven), might not be long before there are requests for degree requirements, etc xD

**Comment by yangshun** [comment]
This is beyond NUSMods scope at the moment. We try not to have to deal with stuff that pertains to individual faculties only (besides CORS bidding history).
