### ISSUE TITLE
HTML Timetable Export's Modules Table Looks Different

### ISSUE THREAD

**Issue by joey-c** [nusmodifications/nusmods#84]
Expected: to look the same as per the browser, just without the action column 
![screen shot 2014-07-25 at 12 40 56 pm](https://cloud.githubusercontent.com/assets/3621969/3697986/e7bd2342-13b5-11e4-9848-34936644ec7a.png)

Actual:
![screen shot 2014-07-25 at 12 40 47 pm](https://cloud.githubusercontent.com/assets/3621969/3697987/e951fe3a-13b5-11e4-9e0f-02e71edb9831.png)

**Comment by yangshun** [comment]
This is a small UI issue. Closing it out.
