### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#89]
- [x] What information sources does NUSMods use?
- [ ] How can I help out?
- [ ] How often is NUSMods updated?

**Comment by ngzhian** [comment]
We have a contribution page on https://nusmods.com/contribute, maybe add a link on the about page (https://nusmods.com/about) to this url?

**Comment by yangshun** [comment]
Actually probably should extract out https://nusmods.com/contact to FAQ lol.

**Comment by ngzhian** [comment]
so remove that contact link and have everything link to FAQ page, just under different fragment?

**Comment by yangshun** [comment]
Actually lemme think through this more. I'll settle this (:

**Comment by yangshun** [comment]
We had a pretty hostile FAQ page long ago 😂
