### ISSUE TITLE
Share timetable directly as an image on Facebook

### ISSUE THREAD

**Issue by ahbeng** [nusmodifications/nusmods#96]
Suggested by @yangshun

**Comment by yangshun** [comment]
Possibly make use of [domvas](http://pbakaus.github.io/domvas/)

**Comment by ngzhian** [comment]
Or https://github.com/niklasvh/html2canvas

**Comment by yangshun** [comment]
Doesn't provide much value because the shared images will be too small to actually be comprehensible. Closing this XD
